// bsptest.cpp - Entities aus einer echten Karte
#include "bhed/bsp.h"
#include "bhed/script.h"
#include "bhed/scene.h"

#include <algorithm>
#include <cstddef>
#include <cstdio>
#include <vector>
#include <fstream>
#include <sstream>
#include <string>

namespace {
int fails = 0;
void expect(const char* what, bool ok) {
    std::printf("  %s  %s\n", ok ? "ok  " : "FEHL", what);
    if (!ok) { ++fails; }
}
}  // namespace

int main(int argc, char** argv) {
    // --- Ohne Datei: das Zerlegen selbst ---------------------------------
    {
        const std::string text =
            "{\n\"classname\" \"worldspawn\"\n\"message\" \"Kamino\"\n}\n"
            "{\n\"classname\" \"info_player_start\"\n\"targetname\" \"start1\"\n"
            "\"origin\" \"128 64 32\"\n}\n"
            "{\n\"classname\" \"misc_camera\"\n\"cameraGroup\" \"cam_a\"\n}\n";
        std::vector<bhed::MapEntity> ents;
        bhed::parseEntities(text, ents);
        expect("drei Entities gelesen", ents.size() == 3);
        expect("classname erkannt", !ents.empty() && ents[0].classname == "worldspawn");
        expect("targetname erkannt", ents.size() > 1 && ents[1].targetname == "start1");
        expect("origin erkannt", ents.size() > 1 && ents[1].origin == "128 64 32");
        expect("cameraGroup erkannt", ents.size() > 2 && ents[2].cameraGroup == "cam_a");
        expect("beliebiger Schluessel abrufbar",
               !ents.empty() && ents[0].find("message") != nullptr &&
                   *ents[0].find("message") == "Kamino");
    }

    // Halbe Zeilen und Muell duerfen nicht stuerzen.
    {
        std::vector<bhed::MapEntity> ents;
        for (const char* junk : {"", "{", "}", "{\"a\"", "{\"a\" \"b\"",
                                 "{{{{", "\"\"\"\"", "{\"a\" \"b\"} {\"c\"",
                                 "{\n\"key\"\n}\n"}) {
            bhed::parseEntities(junk, ents);   // darf nur nicht knallen
        }
        expect("kaputte Eingaben ueberstanden", true);
    }

    // --- Schluessel ohne Ruecksicht auf Gross- und Kleinschreibung -------
    //
    // So macht es die Engine: g_spawn.cpp, G_ParseField() vergleicht mit
    // Q_stricmp. Ihre Feldtabelle schreibt "NPC_targetname" und "NPC_type"
    // gross, Karten schreiben mal so, mal so. Vorher verglich MapEntity::find
    // genau - und ein grossgeschriebenes "NPC_targetname" in der .ent fand
    // keinen Spawner, waehrend dieselbe Karte im Spiel lief.
    {
        std::vector<bhed::MapEntity> ents;
        bhed::parseEntities(
            "{\n\"classname\" \"NPC_Kyle\"\n\"NPC_targetname\" \"kyle1\"\n"
            "\"NPC_type\" \"kyle\"\n\"origin\" \"1 2 3\"\n}\n",
            ents);
        expect("eine Entity gelesen", ents.size() == 1U);
        if (ents.size() == 1U) {
            const bhed::MapEntity& e = ents[0];
            expect("Schluessel wie geschrieben gefunden",
                   e.find("NPC_targetname") != nullptr);
            expect("Schluessel klein geschrieben auch",
                   e.find("npc_targetname") != nullptr);
            expect("und gross geschrieben ebenso",
                   e.find("NPC_TARGETNAME") != nullptr);
            expect("es ist derselbe Wert",
                   e.find("npc_targetname") != nullptr &&
                       *e.find("npc_targetname") == "kyle1");
            expect("ein Schluessel, den es nicht gibt, bleibt leer",
                   e.find("gibtesnicht") == nullptr);
            // Klassennamen vergleicht die Engine mit strcmp, also GENAU
            // (g_spawn.cpp, G_CallSpawn). Das bleibt hier so.
            expect("Klassenname bleibt genau", e.classname == "NPC_Kyle");
        }
    }

    // --- Nicht nur NPC_spawner erzeugt Figuren ---------------------------
    //
    // code/game/g_spawn.cpp fuehrt 88 Klassennamen, die eine Figur setzen.
    // Alle beginnen mit "NPC_". Vorher erkannte die Szene nur NPC_spawner,
    // und eine Karte mit NPC_Kyle hatte null Figuren mit Modell.
    {
        bhed::MapData map;
        bhed::parseEntities(
            "{\n\"classname\" \"NPC_spawner\"\n\"NPC_targetname\" \"a\"\n"
            "\"NPC_type\" \"md_kanan\"\n\"origin\" \"0 0 0\"\n}\n"
            "{\n\"classname\" \"NPC_Kyle\"\n\"NPC_targetname\" \"b\"\n"
            "\"origin\" \"0 0 0\"\n}\n"
            "{\n\"classname\" \"info_player_start\"\n\"targetname\" \"c\"\n}\n",
            map.entities);
        bhed::collectNames(map);
        bhed::Script sc;
        std::vector<bhed::Diag> dd;
        (void)bhed::readScript(
            "//Generated by BehavEd\r\n"
            "affect ( \"a\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n}\r\n"
            "affect ( \"b\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n}\r\n"
            "affect ( \"c\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n}\r\n",
            sc, dd);
        const bhed::Scene scene = bhed::buildScene(sc, map);
        const bhed::Actor* a = scene.find("a");
        const bhed::Actor* b = scene.find("b");
        const bhed::Actor* c = scene.find("c");
        expect("NPC_spawner: NPC_type wie angegeben",
               a != nullptr && a->npcType == "md_kanan");
        // NPC_Kyle traegt keinen NPC_type - den setzt im Spiel SP_NPC_Kyle
        // auf "Kyle" (NPC_spawn.cpp; die Suche in den .npc ist ohne Gross-
        // und Kleinschreibung).
        expect("NPC_Kyle ohne NPC_type: aus dem Klassennamen abgeleitet",
               b != nullptr && b->npcType == "Kyle");
        expect("etwas anderes als NPC_* bleibt ohne Typ",
               c != nullptr && c->npcType.empty());
    }

    // --- angle UND angles ------------------------------------------------
    //
    // g_spawn.cpp fuehrt beide Schluessel auf dasselbe Feld:
    //   {"angles", FOFS(s.angles), F_VECTOR},
    //   {"angle",  FOFS(s.angles), F_ANGLEHACK},
    // "angles" nimmt alle drei Werte, "angle" nur den Gierwinkel und setzt
    // die anderen beiden auf null. Vorher las die Szene NUR "angle", und
    // eine Karte mit "angles" liess jede Figur nach Norden schauen.
    {
        auto yawOf = [](const char* ent, const char* who) {
            bhed::MapData map;
            bhed::parseEntities(ent, map.entities);
            bhed::collectNames(map);
            bhed::Script sc;
            std::vector<bhed::Diag> dd;
            (void)bhed::readScript(
                std::string("//Generated by BehavEd\r\naffect ( \"") + who +
                    "\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n}\r\n",
                sc, dd);
            const bhed::Scene sn = bhed::buildScene(sc, map);
            const bhed::Actor* a = sn.find(who);
            return a != nullptr ? a->startAngles[1] : -1.0F;
        };
        expect("angle wird gelesen",
               yawOf("{\n\"classname\" \"NPC_spawner\"\n\"NPC_targetname\" \"a\"\n"
                     "\"NPC_type\" \"kyle\"\n\"angle\" \"90\"\n\"origin\" \"0 0 0\"\n}\n",
                     "a") == 90.0F);
        expect("angles wird auch gelesen",
               yawOf("{\n\"classname\" \"NPC_spawner\"\n\"NPC_targetname\" \"a\"\n"
                     "\"NPC_type\" \"kyle\"\n\"angles\" \"0 270 0\"\n\"origin\" \"0 0 0\"\n}\n",
                     "a") == 270.0F);
        // Stehen beide da, gewinnt der spaetere - die Engine arbeitet die
        // Schluessel der Reihe nach ab.
        expect("stehen beide da, gewinnt der spaetere",
               yawOf("{\n\"classname\" \"NPC_spawner\"\n\"NPC_targetname\" \"a\"\n"
                     "\"NPC_type\" \"kyle\"\n\"angles\" \"0 270 0\"\n\"angle\" \"45\"\n"
                     "\"origin\" \"0 0 0\"\n}\n",
                     "a") == 45.0F);
    }

    // --- Mit Datei -------------------------------------------------------
    if (argc > 1) {
        std::ifstream f(argv[1], std::ios::binary);
        std::ostringstream ss;
        ss << f.rdbuf();
        const std::string bytes = ss.str();

        bhed::MapData map;
        std::string err;
        expect("echte .bsp gelesen", bhed::readBsp(bytes, map, &err));
        expect("Kennung RBSP", map.magic == "RBSP");
        // Diese beiden Proben beschrieben frueher die BEISPIELKARTE, nicht
        // den Leser: "mehr als 50 Entities", "mehr als 10 Zielnamen". Auf
        // yavin2 stimmt das, auf md_tfoaj_jedi.bsp nicht - dort stehen nur
        // 36 Entities und gar kein targetname, weil Movie Duels die Entities
        // aus einer .ent daneben nimmt. Eine Probe, die bei richtiger
        // Eingabe anschlaegt, ist keine Probe.
        //
        // Geprueft wird jetzt, was fuer JEDE gueltige Karte gilt.
        expect("Entities gefunden", !map.entities.empty());
        bool hasWorld = false;
        for (const bhed::MapEntity& e : map.entities) {
            if (e.classname == "worldspawn") { hasWorld = true; }
        }
        expect("worldspawn dabei", hasWorld);
        // Wenn ueberhaupt ein targetname in der Karte steht, muss er auch in
        // der Liste landen - und wenn keiner drinsteht, muss die Liste leer
        // sein. Beides waere sonst still falsch.
        std::size_t withName = 0;
        for (const bhed::MapEntity& e : map.entities) {
            if (!e.targetname.empty()) { ++withName; }
        }
        expect("Zielnamen genau dann, wenn welche dastehen",
               (withName == 0) == map.targetNames.empty());
        expect("nicht mehr Zielnamen als Entities, die einen tragen",
               map.targetNames.size() <= withName);
        expect("Zielnamen sortiert",
               std::is_sorted(map.targetNames.begin(), map.targetNames.end()));
        expect("keine Dubletten unter den Zielnamen",
               std::adjacent_find(map.targetNames.begin(), map.targetNames.end()) ==
                   map.targetNames.end());
        std::printf("     %s %d: %zu Entities, %zu Zielnamen, %zu Kameragruppen\n",
                    map.magic.c_str(), map.version, map.entities.size(),
                    map.targetNames.size(), map.cameraGroups.size());

        // Abgeschnittene Datei darf nicht stuerzen und muss ablehnen.
        for (std::size_t cut : {std::size_t{0}, std::size_t{8}, std::size_t{15},
                                bytes.size() / 2}) {
            bhed::MapData m2;
            (void)bhed::readBsp(bytes.substr(0, cut), m2, nullptr);
        }
        expect("abgeschnittene Datei ueberstanden", true);

        // Kaputter Lumpzeiger
        std::string broken = bytes;
        for (int i = 0; i < 4; ++i) {
            broken[8 + static_cast<std::size_t>(i)] = static_cast<char>(0xFF);
        }
        bhed::MapData m3;
        expect("unsinniger Lumpzeiger wird abgewiesen",
               !bhed::readBsp(broken, m3, nullptr));
    }

    // --- Die Karte nennt ihre Skripte -------------------------------------
    //
    // So haengt eine Mission zusammen: die Karte selbst weiss nichts von
    // Skripten, aber ihre Entities tun es. Bei md_tfoaj_jedi.ent aus Movie
    // Duels sind das sieben - vier ueber usescript an
    // target_scriptrunner, drei ueber deathscript an NPC_spawner.
    {
        const char* text =
            "{\n\"classname\" \"target_scriptrunner\"\n"
            "\"targetname\" \"intro\"\n\"usescript\" \"md/intro\"\n}\n"
            "{\n\"classname\" \"NPC_spawner\"\n"
            "\"deathscript\" \"md/wache_tot\"\n}\n"
            "{\n\"classname\" \"NPC_spawner\"\n"
            "\"deathscript\" \"md/wache_tot\"\n}\n"
            "{\n\"classname\" \"worldspawn\"\n}\n";
        bhed::MapData m;
        bhed::parseEntities(text, m.entities);
        bhed::collectNames(m);
        expect("zwei Skripte gefunden", m.scripts.size() == 2);
        // Dasselbe deathscript steht an zwei Wachen - es darf nur EINMAL
        // in der Liste stehen.
        int wache = 0;
        for (const bhed::MapData::ScriptRef& r : m.scripts) {
            if (r.path == "md/wache_tot") { ++wache; }
        }
        expect("ein doppelter Verweis steht nur einmal", wache == 1);
        expect("der Schluessel wird gemerkt",
               !m.scripts.empty() && m.scripts[0].key == "usescript");
        expect("und wem er gehoert",
               !m.scripts.empty() && m.scripts[0].owner == "intro");
    }

    std::printf("\n%s (%d Fehlschlaege)\n",
                fails != 0 ? "FEHLGESCHLAGEN" : "alle Kartenproben bestanden", fails);
    return fails != 0 ? 1 : 0;
}
