// camtracktest.cpp - die Kamerabahn
//
// Alles hier ist an cg_camera.cpp nachgemessen. Die Proben pruefen genau
// die Stellen, an denen man es falsch machen wuerde, wenn man es annimmt
// statt nachzusehen.
#include "bhed/camtrack.h"
#include "bhed/mapview.h"
#include "bhed/scene.h"

#include <algorithm>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

namespace {
int fails = 0;
void expect(const char* what, bool ok) {
    std::printf("  %s  %s\n", ok ? "ok  " : "FEHL", what);
    if (!ok) { ++fails; }
}
bool near(float a, float b, float eps = 0.01F) { return std::fabs(a - b) < eps; }

bhed::CameraTrack of(const std::string& body) {
    bhed::Script s;
    std::vector<bhed::Diag> d;
    (void)bhed::readScript("//Generated by BehavEd\r\n" + body, s, d);
    return bhed::buildCameraTrack(s);
}
}  // namespace

int main(int argc, char** argv) {
    // --- Der kuerzeste Weg -----------------------------------------------
    //
    // CGCam_Pan rechnet zwei Deltas aus und nimmt das betragsmaessig
    // kleinere. Von 350 Grad auf 10 Grad sind das +20, nicht -340. Wer das
    // falsch macht, laesst die Kamera einmal fast ganz herumfahren - und
    // zwar sichtbar, ueber die volle Dauer des Schwenks.
    {
        expect("350 -> 10 sind +20 Grad",
               near(bhed::shortestAngleDelta(350.0F, 10.0F), 20.0F));
        expect("10 -> 350 sind -20 Grad",
               near(bhed::shortestAngleDelta(10.0F, 350.0F), -20.0F));
        expect("0 -> 90 sind +90 Grad",
               near(bhed::shortestAngleDelta(0.0F, 90.0F), 90.0F));
        expect("0 -> 270 sind -90 Grad",
               near(bhed::shortestAngleDelta(0.0F, 270.0F), -90.0F));
        // Negative Eingaben, wie sie in Skripten stehen: -51 statt 309.
        expect("-51 -> -60 sind -9 Grad",
               near(bhed::shortestAngleDelta(-51.0F, -60.0F), -9.0F));
        // Genau 180 Grad: beide Wege sind gleich lang, es darf nur nichts
        // knallen.
        const float half = bhed::shortestAngleDelta(0.0F, 180.0F);
        expect("180 Grad ergeben 180 oder -180", near(std::fabs(half), 180.0F));
    }

    // --- Bewegung ist linear ---------------------------------------------
    //
    // Zeile 1266 von cg_camera.cpp: kein Ein- und Ausschwingen.
    {
        const bhed::CameraTrack t = of(
            "camera ( /*@CAMERA_COMMANDS*/ MOVE, < 0.000 0.000 0.000 >, 0 );\r\n"
            "camera ( /*@CAMERA_COMMANDS*/ MOVE, < 1000.000 0.000 0.000 >, 4000 );\r\n"
            "wait ( 4000.000 );\r\n");
        expect("die Bahn dauert 4 s", near(static_cast<float>(t.durationMs), 4000.0F, 1.0F));
        expect("bei 0 s am Anfang", near(t.at(0.0).pos[0], 0.0F, 1.0F));
        expect("bei 1 s ein Viertel", near(t.at(1000.0).pos[0], 250.0F, 1.0F));
        expect("bei 2 s die Haelfte", near(t.at(2000.0).pos[0], 500.0F, 1.0F));
        expect("bei 3 s drei Viertel", near(t.at(3000.0).pos[0], 750.0F, 1.0F));
        expect("bei 4 s am Ziel", near(t.at(4000.0).pos[0], 1000.0F, 1.0F));
        expect("danach bleibt sie stehen", near(t.at(9000.0).pos[0], 1000.0F, 1.0F));
    }

    // --- Dauer 0 ist ein SPRUNG ------------------------------------------
    //
    // CGCam_Move setzt bei !duration direkt die Position. Wer hier durch die
    // Dauer teilt, bekommt eine Division durch null.
    {
        const bhed::CameraTrack t = of(
            "camera ( /*@CAMERA_COMMANDS*/ MOVE, < 500.000 0.000 0.000 >, 0 );\r\n");
        expect("ein Sprung ist sofort da", near(t.at(0.0).pos[0], 500.0F, 1.0F));
    }

    // --- Der Schwenk nimmt den kurzen Weg auch in der Bahn ---------------
    {
        const bhed::CameraTrack t = of(
            "camera ( /*@CAMERA_COMMANDS*/ PAN, < 0.000 350.000 0.000 >, "
            "< 0.000 0.000 0.000 >, 0 );\r\n"
            "camera ( /*@CAMERA_COMMANDS*/ PAN, < 0.000 10.000 0.000 >, "
            "< 0.000 0.000 0.000 >, 2000 );\r\n"
            "wait ( 2000.000 );\r\n");
        // Auf halbem Weg muss die Kamera bei 0 Grad stehen, nicht bei 180.
        const bhed::CameraState mid = t.at(1000.0);
        expect("auf halbem Weg von 350 nach 10 steht sie bei 0",
               near(mid.angles[1], 0.0F, 1.0F));
        const bhed::CameraState end = t.at(2000.0);
        expect("am Ende bei 10", near(end.angles[1], 10.0F, 1.0F));
    }

    // --- Zoom und Ein-/Ausschalten ---------------------------------------
    {
        const bhed::CameraTrack t = of(
            "camera ( /*@CAMERA_COMMANDS*/ ENABLE );\r\n"
            "camera ( /*@CAMERA_COMMANDS*/ ZOOM, 30.000, 2000 );\r\n"
            "wait ( 2000.000 );\r\n"
            "camera ( /*@CAMERA_COMMANDS*/ DISABLE );\r\n");
        expect("am Anfang ist die Kamera an", t.at(0.0).enabled);
        expect("der Zoom beginnt bei 90", near(t.at(0.0).fovX, 90.0F, 0.5F));
        expect("auf halbem Weg bei 60", near(t.at(1000.0).fovX, 60.0F, 0.5F));
        expect("am Ende bei 30", near(t.at(2000.0).fovX, 30.0F, 0.5F));
        expect("danach ist sie aus", !t.at(2500.0).enabled);
    }

    // --- SHAKE und FOLLOW -------------------------------------------------
    //
    // Die letzten beiden Unterbefehle der Kamera. In den 284 Skripten der
    // Mod zusammen sieben Verwendungen - damit sind 1902 von 1902 abgedeckt.
    {
        const bhed::CameraTrack t = of(
            "camera ( /*@CAMERA_COMMANDS*/ ENABLE );\r\n"
            "camera ( /*@CAMERA_COMMANDS*/ SHAKE, 4.000, 1000.000 );\r\n"
            "wait ( 2000.000 );\r\n"
            "camera ( /*@CAMERA_COMMANDS*/ FOLLOW, \"helden\", 100.000, 0.000 );\r\n"
            "wait ( 1000.000 );\r\n"
            "camera ( /*@CAMERA_COMMANDS*/ FOLLOW, \"NULL\", 0.000, 0.000 );\r\n");

        // Waehrend des Zitterns weicht der Ort ab, danach nicht mehr.
        const bhed::CameraState mitten = t.at(200.0);
        const bhed::CameraState danach = t.at(1500.0);
        const bool wackelt = mitten.pos[0] != 0.0F || mitten.pos[1] != 0.0F ||
                             mitten.pos[2] != 0.0F;
        expect("SHAKE laesst die Kamera wackeln", wackelt);
        expect("nach der Dauer steht sie wieder still",
               danach.pos[0] == 0.0F && danach.pos[1] == 0.0F &&
                   danach.pos[2] == 0.0F);

        // Wiederholbar - dieselbe Zeit, dasselbe Zittern. Sonst koennte man
        // eine Zwischensequenz nicht abstimmen.
        const bhed::CameraState nochmal = t.at(200.0);
        expect("dasselbe Bild ergibt dasselbe Zittern",
               nochmal.pos[0] == mitten.pos[0] &&
                   nochmal.pos[1] == mitten.pos[1] &&
                   nochmal.pos[2] == mitten.pos[2]);

        // Und es klingt ab: cg_camera.cpp rechnet
        // intensity_scale = 1 - (t/duration) * (FOV/90), also linear.
        float frueh = 0.0F;
        float spaet = 0.0F;
        for (int k = 0; k < 3; ++k) {
            frueh += std::fabs(t.at(50.0).pos[k]);
            spaet += std::fabs(t.at(950.0).pos[k]);
        }
        expect("das Zittern klingt ab", spaet < frueh);

        // ROLL bleibt unberuehrt: die Engine dreht nur zwei der drei
        // Winkel (for i < 2 - "Don't do ROLL").
        expect("SHAKE laesst ROLL in Ruhe", t.at(200.0).angles[2] == 0.0F);

        // FOLLOW merkt sich die Gruppe, und "NULL" schaltet sie ab - so
        // steht es in CGCam_Follow, das "none", "NULL" und leer gleich
        // behandelt.
        expect("FOLLOW merkt sich die Gruppe",
               t.at(2500.0).followGroup == "helden");
        expect("\"NULL\" schaltet das Zielen wieder ab",
               t.at(3500.0).followGroup.empty());
        expect("vor dem ersten FOLLOW wird nicht gezielt",
               t.at(100.0).followGroup.empty());
    }

    // --- Leeres und kaputtes Skript --------------------------------------
    {
        const bhed::CameraTrack empty = of("");
        expect("ein leeres Skript ergibt eine leere Bahn", empty.segments.empty());
        expect("und stuerzt beim Abfragen nicht", near(empty.at(5000.0).fovX, 90.0F));
        const bhed::CameraTrack odd = of(
            "camera ( /*@CAMERA_COMMANDS*/ MOVE, < 1.000 2.000 3.000 >, "
            "$random( 100, 200 )$ );\r\n");
        expect("ein Ausdruck als Dauer wird ueberstanden", !odd.segments.empty());
    }

    // --- Gegen echte Skripte ---------------------------------------------
    for (int a = 1; a < argc; ++a) {
        std::ifstream f(argv[a], std::ios::binary);
        std::ostringstream ss;
        ss << f.rdbuf();
        if (ss.str().empty()) {
            continue;
        }
        bhed::Script s;
        std::vector<bhed::Diag> d;
        if (!bhed::readScript(ss.str(), s, d)) {
            continue;
        }
        const bhed::CameraTrack t = bhed::buildCameraTrack(s);
        std::printf("     %s: %zu Abschnitte, %.1f s\n", argv[a],
                    t.segments.size(), t.durationMs / 1000.0);
        expect("Abschnitte gefunden", !t.segments.empty());

        // Die Abschnitte muessen in Reihenfolge stehen - at() bricht sonst
        // zu frueh ab.
        bool ordered = true;
        double last = -1.0;
        for (const bhed::CamSegment& seg : t.segments) {
            if (seg.startMs < last - 0.001) { ordered = false; }
            last = seg.startMs;
            if (seg.endMs < seg.startMs) { ordered = false; }
        }
        expect("die Abschnitte stehen in Reihenfolge", ordered);

        // Kein Sprung ins Nichts: die Stellung darf nirgends unsinnig sein.
        bool sane = true;
        for (double ms = 0.0; ms <= t.durationMs; ms += 250.0) {
            const bhed::CameraState st = t.at(ms);
            for (int k = 0; k < 3; ++k) {
                if (!std::isfinite(st.pos[k]) || !std::isfinite(st.angles[k])) {
                    sane = false;
                }
            }
            if (!std::isfinite(st.fovX) || st.fovX <= 0.0F || st.fovX > 180.0F) {
                sane = false;
            }
        }
        expect("die Stellung ist zu jeder Zeit brauchbar", sane);
    }

    // --- Der Laufweg einer Figur ----------------------------------------
    //
    // "ich will den charakter anklicken um zu sehen wo er hinlaeuft,
    // aehnlich wie bei der Kamera." Gezeichnet wird das wie die
    // Kamerabahn: in Schritten abtasten und verbinden - ueber Actor::at().
    //
    // Geprueft wird, dass die Abtastung wirklich der Bewegung folgt: am
    // Anfang der Startort, am Ende das Ziel, in der Mitte dazwischen. Eine
    // Bahn, die nur den Startort wiederholt, faellt hier auf.
    {
        bhed::Actor fig;
        fig.name = "ani1";
        fig.haveStart = true;
        fig.start[0] = 0.0F;
        fig.start[1] = 0.0F;
        fig.start[2] = 0.0F;

        bhed::ActorStep sp;
        sp.startMs = 0.0;
        sp.endMs = 1000.0;
        sp.kind = bhed::ActorStep::Kind::Glide;   // move: Ort ueber Dauer
        sp.from[0] = 0.0F;
        sp.from[1] = 0.0F;
        sp.from[2] = 0.0F;
        sp.to[0] = 100.0F;
        sp.to[1] = 200.0F;
        sp.to[2] = 0.0F;
        fig.steps.push_back(sp);

        const bhed::ActorState a0 = fig.at(0.0);
        const bhed::ActorState a5 = fig.at(500.0);
        const bhed::ActorState a1 = fig.at(1000.0);
        std::printf("  Figur: 0 ms (%.0f %.0f)  500 ms (%.0f %.0f)  "
                    "1000 ms (%.0f %.0f)\n",
                    (double)a0.pos[0], (double)a0.pos[1], (double)a5.pos[0],
                    (double)a5.pos[1], (double)a1.pos[0], (double)a1.pos[1]);
        expect("am Anfang steht sie am Startort",
               std::fabs(a0.pos[0]) < 0.5F && std::fabs(a0.pos[1]) < 0.5F);
        expect("am Ende ist sie am Ziel",
               std::fabs(a1.pos[0] - 100.0F) < 0.5F &&
                   std::fabs(a1.pos[1] - 200.0F) < 0.5F);
        expect("dazwischen liegt sie WIRKLICH dazwischen",
               a5.pos[0] > 1.0F && a5.pos[0] < 99.0F &&
                   a5.pos[1] > 1.0F && a5.pos[1] < 199.0F);
        // Und die Bahn hat eine Laenge - eine, die nur den Startort
        // wiederholt, haette null.
        double laenge = 0.0;
        bhed::ActorState vor = fig.at(0.0);
        for (int i = 1; i <= 200; ++i) {
            const bhed::ActorState nun = fig.at(1000.0 * i / 200.0);
            const double dx = nun.pos[0] - vor.pos[0];
            const double dy = nun.pos[1] - vor.pos[1];
            laenge += std::sqrt(dx * dx + dy * dy);
            vor = nun;
        }
        std::printf("  abgetastete Bahnlaenge: %.1f (Luftlinie %.1f)\n",
                    laenge, std::sqrt(100.0 * 100.0 + 200.0 * 200.0));
        expect("die abgetastete Bahn ist so lang wie die Strecke",
               std::fabs(laenge - std::sqrt(100.0 * 100.0 + 200.0 * 200.0)) <
                   1.0);
    }

    // --- Die Richtungsangabe von camera(PAN, ...) -----------------------
    //
    // Geprueft wird nicht nur unsere Funktion, sondern ob ihr Ergebnis die
    // Engine wirklich den GEWOLLTEN Weg fahren laesst. Dafuer steht
    // CGCam_Pan hier nachgebaut - Zeile fuer Zeile aus
    // code/cgame/cg_camera.cpp - und wird mit dem gefuettert, was wir
    // schreiben wuerden. Eine Probe, die nur -1/0/+1 vergleicht, ginge an
    // der eigentlichen Frage vorbei.
    {
        auto norm360 = [](double a) {
            double r = std::fmod(a, 360.0);
            if (r < 0.0) { r += 360.0; }
            return r;
        };
        // Das ist CGCam_Pan: welchen Weg faehrt die Engine wirklich?
        auto engineDelta = [&](double ziel, double jetzt, double richtung) {
            const double dest = norm360(ziel);
            const double delta1 = dest - norm360(jetzt);
            const double delta2 = (delta1 < 0.0) ? delta1 + 360.0
                                                 : delta1 - 360.0;
            if (richtung == 0.0) {
                return (std::fabs(delta1) < std::fabs(delta2)) ? delta1
                                                               : delta2;
            }
            if (richtung < 0.0) {
                if (delta1 < 0.0) { return delta1; }
                if (delta1 > 0.0) { return delta2; }
                return 0.0;
            }
            if (delta1 > 0.0) { return delta1; }
            if (delta1 < 0.0) { return delta2; }
            return 0.0;
        };

        struct Fall { double start; double dreh; const char* was; };
        const Fall faelle[] = {
            {0.0, 30.0, "kleine Drehung nach rechts"},
            {0.0, -30.0, "kleine Drehung nach links"},
            {350.0, 20.0, "ueber die Null hinweg"},
            {10.0, 200.0, "mehr als 180 nach rechts"},
            {210.0, -200.0, "mehr als 180 nach links"},
            {0.0, 270.0, "drei Viertel herum"},
            {0.0, -270.0, "drei Viertel zurueck"},
            {45.0, 179.0, "knapp unter der Haelfte"},
            {45.0, 181.0, "knapp darueber"},
        };
        for (const Fall& f : faelle) {
            const float dir = bhed::panDirectionFor((float)f.dreh);
            const double gefahren =
                engineDelta(f.start + f.dreh, f.start, dir);
            char txt[128];
            std::snprintf(txt, sizeof(txt),
                          "%s: %+.0f gewollt, Richtung %+.0f -> Engine faehrt "
                          "%+.0f",
                          f.was, f.dreh, (double)dir, gefahren);
            expect(txt, std::fabs(gefahren - f.dreh) < 0.01);
        }

        // Genau 180 Grad: ohne Angabe entscheidet der Zufall, mit Angabe
        // nicht. Hier nur, dass wir eine Richtung SETZEN.
        expect("bei genau 180 Grad setzen wir eine Richtung",
               bhed::panDirectionFor(180.0F) != 0.0F &&
                   bhed::panDirectionFor(-180.0F) != 0.0F);

        // Und der bisherige Fehler: OHNE Richtung faehrt die Engine bei
        // einer grossen Drehung den anderen Weg. Wenn das hier NICHT mehr
        // gilt, ist die Probe stumpf geworden.
        const double ohne = engineDelta(10.0 + 200.0, 10.0, 0.0);
        std::printf("  ohne Richtung bei +200: Engine faehrt %+.0f\n", ohne);
        expect("ohne Richtung geht die Engine wirklich andersherum",
               ohne < 0.0);

        // Kleine Drehungen brauchen KEINE Angabe - sonst stuende in jeder
        // Datei eine Richtung, die nichts aendert.
        expect("bei kleinen Drehungen bleibt die Richtung null",
               bhed::panDirectionFor(30.0F) == 0.0F &&
                   bhed::panDirectionFor(-90.0F) == 0.0F);
    }

    // --- Wohin schaut camera(FOLLOW, ...)? ------------------------------
    //
    // Die Kamera zielt auf den Mittelpunkt einer cameraGroup; in der Engine
    // steht dafuer vectoangles(dir) in CGCam_FollowUpdate.
    //
    // Geprueft wird nicht die Formel, sondern das ERGEBNIS: die Kamera muss
    // danach wirklich dorthin schauen. Deshalb geht die Probe den Weg
    // zurueck - Winkel in eine Blickrichtung, und die muss auf das Ziel
    // zeigen. Ein Vorzeichenfehler beim Pitch faellt so sofort auf, und ein
    // solcher waere hier besonders tueckisch: die Kamera schaute dann
    // konsequent in die falsche Hoehe, aber in die richtige Richtung.
    {
        struct Fall { float von[3]; float ziel[3]; const char* was; };
        const Fall faelle[] = {
            {{0, 0, 0}, {100, 0, 0}, "nach +X"},
            {{0, 0, 0}, {0, 100, 0}, "nach +Y"},
            {{0, 0, 0}, {-100, 0, 0}, "nach -X"},
            {{0, 0, 0}, {100, 0, 100}, "schraeg nach oben"},
            {{0, 0, 0}, {100, 0, -100}, "schraeg nach unten"},
            {{500, -300, 40}, {-120, 700, 210}, "irgendwohin"},
        };
        for (const Fall& f : faelle) {
            float ang[3];
            bhed::aimAngles(f.von, f.ziel, ang);

            // Der Rueckweg: Winkel -> Blickrichtung.
            bhed::Camera c;
            for (int k = 0; k < 3; ++k) { c.angles[k] = ang[k]; }
            float fw[3];
            c.forward(fw);

            // Und die Richtung zum Ziel, auf Laenge eins.
            float soll[3];
            float len = 0.0F;
            for (int k = 0; k < 3; ++k) {
                soll[k] = f.ziel[k] - f.von[k];
                len += soll[k] * soll[k];
            }
            len = std::sqrt(len);
            for (int k = 0; k < 3; ++k) { soll[k] /= len; }

            const double punkt = (double)(fw[0] * soll[0] + fw[1] * soll[1] +
                                          fw[2] * soll[2]);
            char txt[128];
            std::snprintf(txt, sizeof(txt),
                          "%s: p=%.1f y=%.1f, Blick trifft zu %.4f", f.was,
                          (double)ang[0], (double)ang[1], punkt);
            expect(txt, punkt > 0.9999);
            expect("und ohne Roll", std::fabs(ang[2]) < 0.001F);
        }

        // Senkrecht nach oben und unten: der Yaw ist dort nicht bestimmt,
        // der Pitch muss trotzdem stimmen.
        {
            const float von[3] = {0, 0, 0};
            const float oben[3] = {0, 0, 100};
            const float unten[3] = {0, 0, -100};
            float a1[3];
            float a2[3];
            bhed::aimAngles(von, oben, a1);
            bhed::aimAngles(von, unten, a2);
            std::printf("  senkrecht: oben p=%.0f, unten p=%.0f\n",
                        (double)a1[0], (double)a2[0]);
            expect("nach oben ist der Pitch -90", std::fabs(a1[0] + 90.0F) < 0.01F);
            expect("nach unten +90", std::fabs(a2[0] - 90.0F) < 0.01F);
        }
    }

    // --- Wo sieht man das Ergebnis eines PAN? ---------------------------
    //
    // Gemeldet: nach "Ins Skript schreiben" stand die Kamera "irgendwo
    // zwischendrin" statt an der neuen Stellung.
    //
    // Der Grund ist kein Schreibfehler, sondern die ZEIT: ein PAN laeuft
    // ueber eine Dauer, und zur Zeit null steht die Kamera dort, wo der
    // Schwenk ANFAENGT. Der neue Wert ist erst am ENDE erreicht.
    //
    // Diese Probe haelt genau das fest - und damit auch, warum der Zeiger
    // ans Ende des Befehls springen muss.
    {
        bhed::CameraTrack t;
        bhed::CamSegment pan;
        pan.kind = bhed::CamSegment::Kind::Pan;
        pan.startMs = 1000.0;
        pan.endMs = 5000.0;
        pan.from[1] = 0.0F;   // bei Pan stehen die Winkel in from/to
        pan.to[1] = 90.0F;
        t.segments.push_back(pan);
        t.durationMs = 6000.0;

        const bhed::CameraState amAnfang = t.at(pan.startMs);
        const bhed::CameraState mittendrin = t.at(3000.0);
        const bhed::CameraState amEnde = t.at(pan.endMs);
        std::printf("  PAN 0 -> 90 Grad: Anfang %.0f, Mitte %.0f, Ende %.0f\n",
                    (double)amAnfang.angles[1], (double)mittendrin.angles[1],
                    (double)amEnde.angles[1]);

        expect("am Ende steht der eingestellte Wert",
               std::fabs(amEnde.angles[1] - 90.0F) < 0.5F);
        expect("am Anfang NICHT - dort faengt der Schwenk erst an",
               std::fabs(amAnfang.angles[1] - 90.0F) > 45.0F);
        expect("und mittendrin liegt er dazwischen",
               mittendrin.angles[1] > 10.0F && mittendrin.angles[1] < 80.0F);

        // Und der Kern fuer die Bedienung: der Zeiger muss ans ENDE, nicht
        // an den Anfang des Befehls.
        expect("das Ende des Abschnitts ist die Stelle zum Hinspringen",
               std::fabs(t.segments[0].endMs - 5000.0) < 0.001);
    }

    // --- Ein Klang laeuft noch: die Laenge entscheidet ------------------
    //
    // Gemeldet: Ton aus und wieder an, und es blieb fuenf Sekunden still.
    //
    // Der Wiedereinstieg sucht den Klang, der GERADE LAEUFT - Bedingung
    // startMs <= jetzt < endMs. Das Skript sagt aber nur, wann ein sound
    // ANFAENGT; die Laenge steht in der Datei. Wurde sie nie nachgetragen,
    // ist endMs gleich startMs, die Bedingung nie erfuellt, und es wird
    // nichts gefunden - also Stille bis zum naechsten Klang.
    //
    // Diese Probe haelt fest, worauf es ankommt: OHNE Laenge findet man
    // nichts, MIT Laenge das Richtige.
    {
        struct Klang { double start; double ende; const char* datei; };
        // Zwei Klaenge, wie in intro2_sith: einer laeuft, der naechste
        // kommt fuenf Sekunden spaeter.
        const Klang ohneLaenge[] = {{1000.0, 1000.0, "a.wav"},
                                    {6000.0, 6000.0, "b.wav"}};
        const Klang mitLaenge[] = {{1000.0, 4200.0, "a.wav"},
                                   {6000.0, 8100.0, "b.wav"}};

        auto laufenderKlang = [](const Klang* k, int n, double jetzt) {
            const Klang* beste = nullptr;
            for (int i = 0; i < n; ++i) {
                if (k[i].start <= jetzt && k[i].ende > jetzt &&
                    (beste == nullptr || k[i].start > beste->start)) {
                    beste = &k[i];
                }
            }
            return beste;
        };

        // Bei 2,5 Sekunden laeuft der erste Klang.
        const Klang* ohne = laufenderKlang(ohneLaenge, 2, 2500.0);
        const Klang* mit = laufenderKlang(mitLaenge, 2, 2500.0);
        std::printf("  bei 2,5 s: ohne Laenge %s, mit Laenge %s\n",
                    ohne ? ohne->datei : "NICHTS",
                    mit ? mit->datei : "NICHTS");
        expect("ohne Laenge wird nichts gefunden - das war der Fehler",
               ohne == nullptr);
        expect("mit Laenge der laufende Klang", mit != nullptr);

        // Und der Einstiegspunkt: 1,5 Sekunden in die Datei hinein.
        if (mit != nullptr) {
            const double ab = 2500.0 - mit->start;
            std::printf("  Einstieg %.0f ms in die Datei\n", ab);
            expect("nicht von vorn, sondern mittendrin",
                   std::fabs(ab - 1500.0) < 0.001);
        }

        // In einer LUECKE darf nichts gefunden werden - sonst startete ein
        // laengst beendeter Klang neu.
        expect("zwischen zwei Klaengen bleibt es still",
               laufenderKlang(mitLaenge, 2, 5000.0) == nullptr);
        // Und nach dem Ende des letzten ebenso.
        expect("nach dem letzten auch",
               laufenderKlang(mitLaenge, 2, 9000.0) == nullptr);
    }

    // --- Was beim Drehen ins Skript geschrieben wird --------------------
    //
    // Gemeldet: nach dem Schreiben sprang die Kamera "um die Haelfte"
    // zurueck. Der Grund war ein Bezugsfehler, kein Rechenfehler:
    //
    //   die VORSCHAU dreht ab der Stellung, die am Schluessel angezeigt
    //   wird - die stammt von den PANs DAVOR;
    //   geschrieben wurde "Ziel des naechsten PAN + Drehung".
    //
    // Beide unterscheiden sich um genau diesen einen Schwenk. Steht der
    // Schluessel mitten darin, sieht es aus wie die Haelfte.
    //
    // Die Regel: geschrieben wird, WAS DIE VORSCHAU ZEIGT - absolut.
    {
        const double angezeigt = 30.0;    // Stellung am Schluessel
        const double naechstesZiel = 90.0;   // Ziel des folgenden PAN
        const double drehung = 20.0;      // was der Anwender gezogen hat

        const double richtig = angezeigt + drehung;
        const double falsch = naechstesZiel + drehung;
        std::printf("  angezeigt %.0f + %.0f -> richtig %.0f, alt waere %.0f\n",
                    angezeigt, drehung, richtig, falsch);
        expect("geschrieben wird die angezeigte Stellung plus die Drehung",
               std::fabs(richtig - 50.0) < 0.001);
        expect("die alte Rechnung lag um den ganzen Schwenk daneben",
               std::fabs(falsch - richtig - (naechstesZiel - angezeigt)) < 0.001);

        // Und die Richtungsangabe bezieht sich weiter auf die DREHUNG,
        // nicht auf den neuen Absolutwert - der Weg, den die Engine faehrt,
        // ist der vom Angezeigten zum Neuen.
        expect("kleine Drehung braucht keine Richtung",
               bhed::panDirectionFor(static_cast<float>(drehung)) == 0.0F);
        expect("eine grosse schon",
               bhed::panDirectionFor(200.0F) != 0.0F);
    }

    // --- Ein Schluessel ohne eigenes PAN erbt die Blickrichtung ---------
    //
    // Gemeldet: "wenn ich Kamera move wird eine gespawnt die in die falsche
    // Richtung zeigt".
    //
    // Der Grund: ein camera(MOVE) beginnt einen neuen Schluessel, und dabei
    // wurde ALLES zurueckgesetzt - auch die Winkel. Folgt kein eigenes PAN,
    // stand die Blickrichtung auf null, und null heisst "nach +X".
    //
    // In der Engine bleibt die Stellung stehen, bis ein PAN sie aendert.
    // Genau das wird hier nachgestellt.
    {
        struct Befehl { const char* art; float wert; };
        const Befehl skript[] = {
            {"MOVE", 0.0F},   // Schluessel 1
            {"PAN", 90.0F},
            {"MOVE", 0.0F},   // Schluessel 2 - OHNE eigenes PAN
            {"MOVE", 0.0F},   // Schluessel 3 - ebenfalls ohne
            {"PAN", 200.0F},
        };

        std::vector<float> winkel;
        std::vector<bool> hat;
        float aktuell = 0.0F;
        bool hatAktuell = false;
        float letzte = 0.0F;
        bool hatteLetzte = false;
        bool offen = false;
        for (const Befehl& b : skript) {
            if (std::string(b.art) == "MOVE") {
                if (offen) {
                    if (!hatAktuell && hatteLetzte) {
                        aktuell = letzte;
                        hatAktuell = true;
                    }
                    winkel.push_back(aktuell);
                    hat.push_back(hatAktuell);
                }
                offen = true;
                aktuell = 0.0F;
                hatAktuell = false;
            } else {
                aktuell = b.wert;
                hatAktuell = true;
                letzte = b.wert;
                hatteLetzte = true;
            }
        }
        if (offen) {
            if (!hatAktuell && hatteLetzte) {
                aktuell = letzte;
                hatAktuell = true;
            }
            winkel.push_back(aktuell);
            hat.push_back(hatAktuell);
        }

        std::printf("  Schluesselwinkel: %.0f, %.0f, %.0f\n", (double)winkel[0],
                    (double)winkel[1], (double)winkel[2]);
        expect("drei Schluessel", winkel.size() == 3);
        expect("der erste hat sein eigenes PAN",
               std::fabs(winkel[0] - 90.0F) < 0.01F);
        expect("der zweite ERBT die Richtung, statt auf null zu stehen",
               std::fabs(winkel[1] - 90.0F) < 0.01F && hat[1]);
        expect("der dritte hat wieder ein eigenes",
               std::fabs(winkel[2] - 200.0F) < 0.01F);
        // Und der Beleg fuer den Fehler: ohne Erben stuende dort null,
        // also "nach +X".
        expect("ohne Erben waere es null gewesen",
               std::fabs(90.0F - 0.0F) > 0.01F);
    }

    // --- Wohin springt der Zeiger beim Anfassen eines Schluessels? ------
    //
    // Gemeldet, dreimal in Folge: die Vorschau zeige "in die falsche
    // Richtung". Die Ursache war nie eine falsche Rechnung, sondern immer
    // ein Zeitpunkt - und der letzte Rest davon steckte hier:
    //
    // Ein Schluessel ist ein camera(MOVE) SAMT allem, was bis zum naechsten
    // MOVE folgt - meist ein PAN, oft ein ZOOM. Springt man nur ans Ende
    // des MOVE, ist der Schwenk noch im Gange, und die weisse Kamera zeigt
    // eine Zwischenstellung.
    {
        struct Abschnitt { const char* art; double von; double bis; };
        const Abschnitt bahn[] = {
            {"MOVE", 0.0, 2000.0},     // Schluessel 1
            {"PAN", 0.0, 5000.0},      // laeuft LAENGER als der MOVE
            {"ZOOM", 0.0, 3000.0},
            {"MOVE", 5000.0, 7000.0},  // Schluessel 2
            {"PAN", 5000.0, 6000.0},
        };

        auto endeDesSchluessels = [&](std::size_t i) {
            double ende = bahn[i].bis;
            if (std::string(bahn[i].art) == "MOVE") {
                for (std::size_t j = i + 1; j < 5; ++j) {
                    if (std::string(bahn[j].art) == "MOVE") { break; }
                    ende = std::max(ende, bahn[j].bis);
                }
            }
            return ende;
        };

        std::printf("  Schluessel 1 endet bei %.0f (MOVE allein: %.0f)\n",
                    endeDesSchluessels(0), bahn[0].bis);
        expect("das Ende des Schluessels ist das Ende SEINES laengsten "
               "Befehls",
               std::fabs(endeDesSchluessels(0) - 5000.0) < 0.001);
        expect("nicht das Ende des MOVE allein",
               std::fabs(bahn[0].bis - 5000.0) > 0.001);
        expect("der naechste MOVE beendet die Suche",
               std::fabs(endeDesSchluessels(3) - 7000.0) < 0.001);
    }

    // --- Der ERSTE Schwenk nach dem MOVE bestimmt den Schluessel --------
    //
    // Entschieden durch das Protokoll aus rc212, mit echten Zahlen aus
    // intro2_sith:
    //
    //     Schluessel  Winkel -19.0  85.0 0.0
    //     laufend     Winkel -19.0 152.0 0.0
    //
    // Auf den MOVE folgen dort ZWEI PAN - erst 152, dann 85. Der Durchlauf
    // nahm den letzten, weil jeder PAN den vorigen ueberschrieb. Die
    // laufende Kamera zeigt aber den ERSTEN: der gilt, sobald die Kamera am
    // Schluessel ankommt. Und geschrieben wird ebenfalls in den ersten.
    //
    // Drei Stellen, die dasselbe meinen mussten - und zwei davon lagen
    // daneben.
    {
        struct Befehl { const char* art; float wert; };
        const Befehl skript[] = {
            {"MOVE", 0.0F},
            {"PAN", 152.0F},   // dieser gilt fuer den Schluessel
            {"ZOOM", 60.0F},
            {"PAN", 85.0F},    // dieser NICHT
            {"MOVE", 0.0F},
            {"PAN", 40.0F},
        };

        std::vector<float> schluessel;
        float aktuell = 0.0F;
        bool hatAktuell = false;
        bool offen = false;
        for (const Befehl& b : skript) {
            const std::string art = b.art;
            if (art == "MOVE") {
                if (offen) { schluessel.push_back(aktuell); }
                offen = true;
                aktuell = 0.0F;
                hatAktuell = false;
            } else if (art == "PAN" && !hatAktuell) {
                aktuell = b.wert;
                hatAktuell = true;
            }
        }
        if (offen) { schluessel.push_back(aktuell); }

        std::printf("  Schluesselwinkel: %.0f, %.0f\n", (double)schluessel[0],
                    (double)schluessel[1]);
        expect("der erste Schwenk gilt - 152, nicht 85",
               std::fabs(schluessel[0] - 152.0F) < 0.01F);
        expect("und der ZOOM dazwischen aendert nichts daran",
               std::fabs(schluessel[0] - 152.0F) < 0.01F);
        expect("der naechste Schluessel nimmt seinen eigenen ersten",
               std::fabs(schluessel[1] - 40.0F) < 0.01F);
        // Der Beleg fuer den Fehler: der LETZTE waere 85 gewesen.
        expect("der letzte Schwenk waere ein anderer Wert",
               std::fabs(85.0F - schluessel[0]) > 1.0F);
    }

    // --- Die Kamera auf einer MARKE, nicht auf Zahlen -------------------
    //
    // Gemeldet fuer md_ga_jedi: "die Kamera ist immer im Boden."
    //
    // Nachgesehen im echten Archiv: dort steht KEIN einziger Kamerapunkt
    // als Zahl. Alle sehen so aus:
    //
    //     camera ( MOVE, tag( "cam1b", ORIGIN ), 0.000 );
    //
    // In der Karte liegt dazu ein ref_tag mit targetname "cam1b" bei
    // 208 1796 1224. Ohne Aufloesung las der Vektorleser null Zahlen, und
    // die Kamera stand auf 0 0 0 - im Boden, genau wie berichtet.
    {
        bhed::Script sc;
        std::vector<bhed::Diag> d;
        (void)bhed::readScript(
            "camera ( ENABLE );\n"
            "camera ( MOVE, $tag( \"cam1b\", ORIGIN )$, 0.000 );\n", sc, d);

        // Ohne Auskunft: es bleibt beim Ausgangspunkt, NICHT am Nullpunkt.
        const bhed::CameraTrack ohne = bhed::buildCameraTrack(sc);
        std::printf("     ohne Auskunft: %.0f %.0f %.0f\n",
                    (double)ohne.segments.back().to[0],
                    (double)ohne.segments.back().to[1],
                    (double)ohne.segments.back().to[2]);

        // Mit Auskunft: die Stelle aus der Karte.
        auto marke = [](const std::string& name, float* o, float* a) {
            if (name != "cam1b") { return false; }
            o[0] = 208.0F; o[1] = 1796.0F; o[2] = 1224.0F;
            a[0] = 0.0F; a[1] = 0.0F; a[2] = 0.0F;
            return true;
        };
        const bhed::CameraTrack mit = bhed::buildCameraTrack(sc, marke);
        const auto& z = mit.segments.back();
        std::printf("     mit Auskunft:  %.0f %.0f %.0f\n", (double)z.to[0],
                    (double)z.to[1], (double)z.to[2]);
        expect("die Marke wird aufgeloest",
               z.to[0] == 208.0F && z.to[1] == 1796.0F && z.to[2] == 1224.0F);

        // Eine Marke, die es nicht gibt, darf die Kamera NICHT an den
        // Nullpunkt setzen - das war ja der Fehler.
        //
        // Dafuer muss sie vorher irgendwo stehen: ohne vorherige Stelle
        // IST "stehen bleiben" gleich null, und die Probe saegte am
        // eigenen Ast. Also erst ein MOVE mit Zahlen.
        bhed::Script sc2;
        std::vector<bhed::Diag> d2;
        (void)bhed::readScript(
            "camera ( ENABLE );\n"
            "camera ( MOVE, <100.0 200.0 300.0>, 0.000 );\n"
            "camera ( MOVE, $tag( \"gibtsnicht\", ORIGIN )$, 0.000 );\n",
            sc2, d2);
        auto leer = [](const std::string&, float*, float*) { return false; };
        const bhed::CameraTrack fehlt = bhed::buildCameraTrack(sc2, leer);
        const auto& f = fehlt.segments.back();
        std::printf("     unbekannte Marke: %.0f %.0f %.0f\n", (double)f.to[0],
                    (double)f.to[1], (double)f.to[2]);
        expect("eine unbekannte Marke laesst die Kamera stehen",
               f.to[0] == 100.0F && f.to[1] == 200.0F && f.to[2] == 300.0F);
    }

    // --- Der Verlauf, mit dem die Engine dreht --------------------------
    //
    // Gemeldet: "wenn er sich laut Skript drehen soll, passiert das bei uns
    // instant statt wie in der Engine mit Transition."
    //
    // Im Quelltext nachgesehen: Q3_Interface.cpp setzt TR_NONLINEAR_STOP,
    // bg_misc.cpp rechnet dafuer
    //
    //     deltaTime = dauer * cos( 90 - 90*t/dauer )
    //
    // und mit cos(90-x) = sin(x) bleibt der Anteil sin(90 Grad * t).
    {
        expect("am Anfang null", bhed::nonlinearStop(0.0F) == 0.0F);
        expect("am Ende eins", bhed::nonlinearStop(1.0F) == 1.0F);
        expect("davor und danach begrenzt",
               bhed::nonlinearStop(-1.0F) == 0.0F &&
                   bhed::nonlinearStop(2.0F) == 1.0F);

        // Die Mitte ist der aussagekraeftige Punkt: gleichmaessig waere
        // 0.5, die Engine ist bei sin(45 Grad) = 0.707 schon weiter.
        const float mitte = bhed::nonlinearStop(0.5F);
        std::printf("     bei der Haelfte: %.3f (gleichmaessig waere 0.5)\n",
                    (double)mitte);
        expect("in der Mitte schon ueber der Haelfte", mitte > 0.70F);
        expect("und nicht darueber hinaus", mitte < 0.71F);

        // Schnell los, langsam aus - das erste Viertel legt mehr zurueck
        // als das letzte.
        const float ersteViertel = bhed::nonlinearStop(0.25F);
        const float letztesViertel = 1.0F - bhed::nonlinearStop(0.75F);
        expect("das erste Viertel ist das schnellste",
               ersteViertel > letztesViertel);

        // Und er waechst durchgehend - ein Verlauf, der zwischendurch
        // zurueckliefe, waere ein Rechenfehler.
        bool steigend = true;
        float vorher = -1.0F;
        for (int i = 0; i <= 20; ++i) {
            const float v = bhed::nonlinearStop(static_cast<float>(i) / 20.0F);
            if (v < vorher) { steigend = false; }
            vorher = v;
        }
        expect("der Verlauf laeuft nie zurueck", steigend);
    }

    // --- Ein ref_tag mit "target" zeigt auf sein Ziel ---------------------
    //
    // g_ref.cpp, ref_link(): hat der Tag ein target, werden seine Winkel
    // aus der Richtung zum Ziel gebildet, nicht aus dem angles-Schluessel.
    //
    // Diese Probe steht hier mit den ECHTEN Zahlen aus md_ga_jedi, weil
    // genau dort der Fehler auffiel - und weil sie den einen Fall
    // festhaelt, in dem er sich versteckt: cam1b liegt so, dass die
    // richtige Antwort null ist. Wer nur cam1b prueft, sieht nichts.
    {
        struct Fall {
            const char* name;
            float tag[3];
            float ziel[3];
            float yaw;
        };
        // Aus md_ga_jedi.bsp: die ref_tags und die info_null, auf die sie
        // zeigen. Yaw so, wie aimAngles ihn liefert (Vorzeichen behalten,
        // nicht auf 0..360 gedreht).
        const Fall faelle[] = {
            {"cam1b -> t2  (der Fall, der auch falsch stimmt)",
             {208.0F, 1796.0F, 1224.0F}, {232.0F, 1796.0F, 1224.0F}, 0.0F},
            {"cam2  -> t5", {240.0F, 1832.0F, 1266.0F},
             {244.0F, 1760.0F, 1264.0F}, -86.8F},
            {"cam3  -> t6", {233.0F, 1328.0F, 1274.0F},
             {225.0F, 1332.0F, 1272.0F}, 153.4F},
        };
        for (const Fall& f : faelle) {
            float a[3] = {0.0F, 0.0F, 0.0F};
            bhed::aimAngles(f.tag, f.ziel, a);
            expect(f.name, near(a[1], f.yaw, 0.5F));
        }
        // Und der Kern der Sache: die drei sind NICHT gleich. Genau das
        // war der Fehler - alle drei standen auf null, und nur der erste
        // war damit zufaellig richtig.
        float a1[3];
        float a2[3];
        bhed::aimAngles(faelle[0].tag, faelle[0].ziel, a1);
        bhed::aimAngles(faelle[1].tag, faelle[1].ziel, a2);
        expect("zwei Kamerapunkte schauen nicht in dieselbe Richtung",
               std::fabs(a1[1] - a2[1]) > 1.0F);
    }

    // --- Abgleich mit cg_camera.cpp (27.09.) ------------------------------
    //
    // Die Engine UEBERNIMMT Ort, Winkel und Bildwinkel erst, wenn ein
    // Uebergang fertig ist. Ein Befehl, der einen laufenden unterbricht,
    // faengt deshalb beim ANFANG des alten an, nicht bei dessen Ziel.
    {
        const bhed::CameraTrack t = of(
            "camera ( MOVE, <0.000 0.000 0.000>, 0.000 );\n"
            "camera ( MOVE, <100.000 0.000 0.000>, 2000.000 );\n"
            "wait ( 1000.000 );\n"
            "camera ( MOVE, <100.000 100.000 0.000>, 2000.000 );\n");
        const bhed::CameraState a = t.at(1000.0);
        const bhed::CameraState b = t.at(2000.0);
        const bhed::CameraState c = t.at(3000.0);
        std::printf("     unterbrochen: %.0f %.0f / %.0f %.0f / %.0f %.0f\n", (double)a.pos[0], (double)a.pos[1],
                    (double)b.pos[0], (double)b.pos[1], (double)c.pos[0], (double)c.pos[1]);
        expect("ein unterbrechender MOVE springt auf den Anfang des alten zurueck",
               near(a.pos[0], 0.0F) && near(a.pos[1], 0.0F));
        expect("und faehrt von dort zum neuen Ziel", near(b.pos[0], 50.0F) && near(b.pos[1], 50.0F));
        expect("am Ende steht er am neuen Ziel", near(c.pos[0], 100.0F) && near(c.pos[1], 100.0F));

        // Der Normalfall: fertig, dann weiter - kein Sprung.
        const bhed::CameraTrack k = of(
            "camera ( MOVE, <0.000 0.000 0.000>, 0.000 );\n"
            "camera ( MOVE, <100.000 0.000 0.000>, 2000.000 );\n"
            "wait ( 2000.000 );\n"
            "camera ( MOVE, <100.000 100.000 0.000>, 2000.000 );\n");
        const bhed::CameraState m = k.at(3000.0);
        expect("MOVE; wait so lang wie er; MOVE: weiter vom Ziel aus",
               near(m.pos[0], 100.0F) && near(m.pos[1], 50.0F));
    }
    // PAN mit Richtung: <0 -1 0> dreht die Gier ABWAERTS, auch wenn der
    // andere Weg kuerzer waere (CGCam_Pan, pan_direction < 0).
    {
        const bhed::CameraTrack t = of(
            "camera ( PAN, <0.000 0.000 0.000>, <0.000 0.000 0.000>, 0.000 );\n"
            "camera ( PAN, <0.000 90.000 0.000>, <0.000 -1.000 0.000>, 1000.000 );\n");
        const bhed::CameraState h = t.at(500.0);
        std::printf("     PAN abwaerts, Mitte: Gier %.1f\n", (double)h.angles[1]);
        expect("PAN mit Richtung -1 faehrt den langen Weg (-135 in der Mitte)", near(h.angles[1], -135.0F, 0.1F));
        const bhed::CameraTrack o = of(
            "camera ( PAN, <0.000 0.000 0.000>, <0.000 0.000 0.000>, 0.000 );\n"
            "camera ( PAN, <0.000 90.000 0.000>, <0.000 0.000 0.000>, 1000.000 );\n");
        expect("ohne Richtung der kurze Weg (+45 in der Mitte)", near(o.at(500.0).angles[1], 45.0F, 0.1F));
    }
    // ROLL mit Dauer kopiert die absoluten Winkel als Deltas: Nicken und
    // Gieren laufen aufs Doppelte (cg_camera.cpp, CGCam_Roll).
    {
        const bhed::CameraTrack t = of(
            "camera ( PAN, <10.000 30.000 0.000>, <0.000 0.000 0.000>, 0.000 );\n"
            "camera ( ROLL, 20.000, 1000.000 );\n");
        const bhed::CameraState e = t.at(2000.0);
        std::printf("     nach ROLL mit Dauer: %.1f %.1f %.1f\n", (double)e.angles[0], (double)e.angles[1],
                    (double)e.angles[2]);
        expect("ROLL mit Dauer: Nicken und Gieren verdoppelt, Rollen am Ziel",
               near(e.angles[0], 20.0F, 0.1F) && near(e.angles[1], 60.0F, 0.1F) && near(e.angles[2], 20.0F, 0.1F));
        const bhed::CameraTrack s = of(
            "camera ( PAN, <10.000 30.000 0.000>, <0.000 0.000 0.000>, 0.000 );\n"
            "camera ( ROLL, 20.000, 0.000 );\n");
        const bhed::CameraState f = s.at(10.0);
        expect("ROLL ohne Dauer setzt nur den Rollwinkel",
               near(f.angles[0], 10.0F, 0.1F) && near(f.angles[1], 30.0F, 0.1F) && near(f.angles[2], 20.0F, 0.1F));
    }
    // ZOOM ohne Dauer mitten in einem laufenden: nur der Ausgangswert wird neu,
    // der laufende Zoom geht mit seiner Zeit weiter.
    {
        const bhed::CameraTrack t = of(
            "camera ( ZOOM, 30.000, 2000.000 );\n"
            "wait ( 1000.000 );\n"
            "camera ( ZOOM, 60.000, 0.000 );\n");
        std::printf("     ZOOM 0 im Zoom: %.1f bei 1000, %.1f bei 2000\n", (double)t.at(1000.0).fovX,
                    (double)t.at(2000.0).fovX);
        expect("ZOOM 0 im laufenden Zoom: vom neuen Wert weiter (45 bei 1000)", near(t.at(1000.0).fovX, 45.0F, 0.1F));
        expect("und am Ende das alte Ziel", near(t.at(2500.0).fovX, 30.0F, 0.1F));
        const bhed::CameraTrack e = of(
            "camera ( ZOOM, 50.000, 0.000 );\n"
            "camera ( ENABLE );\n");
        expect("ENABLE setzt den Bildwinkel auf 90 zurueck", near(e.at(10.0).fovX, 90.0F));
    }
    // FADE bleibt auf der Zielfarbe stehen; die Balken blenden in einer
    // Sekunde ein und nach DISABLE wieder aus.
    {
        const bhed::CameraTrack t = of(
            "camera ( ENABLE );\n"
            "camera ( FADE, <0.000 0.000 0.000>, 0.000, <0.000 0.000 0.000>, 1.000, 1000.000 );\n"
            "wait ( 2000.000 );\n"
            "camera ( DISABLE );\n");
        expect("FADE: halb in der Mitte", near(t.at(500.0).fadeColor[3], 0.5F));
        expect("FADE: bleibt nach dem Ende auf dem Ziel", near(t.at(5000.0).fadeColor[3], 1.0F));
        expect("Balken nach 500 ms halb eingeblendet", near(t.at(500.0).bars, 0.5F));
        expect("Balken nach einer Sekunde voll", near(t.at(1500.0).bars, 1.0F));
        expect("Balken 500 ms nach DISABLE halb ausgeblendet", near(t.at(2500.0).bars, 0.5F));
    }
    // FOLLOW endet mit dem naechsten PAN (CGCam_Pan -> CGCam_FollowDisable).
    {
        const bhed::CameraTrack t = of(
            "camera ( FOLLOW, \"gruppe\", 0.000, 0.000 );\n"
            "wait ( 100.000 );\n"
            "camera ( PAN, <0.000 45.000 0.000>, <0.000 0.000 0.000>, 0.000 );\n");
        expect("FOLLOW gilt bis zum PAN", t.at(50.0).followGroup == "gruppe");
        expect("und endet mit ihm", t.at(200.0).followGroup.empty());
        expect("Tempo 0 heisst 100", near(t.at(50.0).followSpeed, 100.0F));
    }
    // tag( ..., ORIGIN ) liefert den Ort, auch in einem PAN - das Wort in der
    // Marke entscheidet (TaskManager GetVector), nicht der Befehl.
    {
        bhed::Script sc;
        std::vector<bhed::Diag> d;
        (void)bhed::readScript(
            "camera ( PAN, $tag( \"m\", ORIGIN )$, <0.000 0.000 0.000>, 0.000 );\n", sc, d);
        auto marke = [](const std::string&, float* o, float* a) {
            o[0] = 1.0F; o[1] = 2.0F; o[2] = 3.0F;
            a[0] = 10.0F; a[1] = 20.0F; a[2] = 30.0F;
            return true;
        };
        const bhed::CameraTrack t = bhed::buildCameraTrack(sc, marke);
        const bhed::CameraState st = t.at(10.0);
        expect("PAN mit tag(..., ORIGIN) nimmt den Ort", near(st.angles[1], 2.0F));
    }

    std::printf("\n%s (%d Fehlschlaege)\n",
                fails != 0 ? "FEHLGESCHLAGEN" : "alle Kamerabahnproben bestanden",
                fails);
    return fails != 0 ? 1 : 0;
}
