// checks.cpp - Gegenprobe. Jede Regel wird absichtlich verletzt; schlaegt
// der Pruefer nicht an, ist die Regel wertlos.
#include "bhed/script.h"
#include "bhed/bsp.h"
#include "bhed/edit.h"
#include "bhed/gla.h"
#include "bhed/ibi.h"
#include "bhed/settings.h"
#include "bhed/bsp.h"
#include "bhed/edit.h"
#include "bhed/ibi.h"
#include "bhed/settings.h"
#include "bhed/i18n.h"
#include "bhed/keys.h"
#include "bhed/camtrack.h"
#include "bhed/clock.h"
#include "bhed/scene.h"
#include "bhed/theme.h"
#include "bhed/tree.h"
#include "bhed/validate.h"

#include <cstddef>
#include <cstdio>
#include <set>
#include <string>
#include <vector>

static bhed::CommandDb g_db;

static bool has(const std::string& src, const char* code) {
    bhed::Script s;
    std::vector<bhed::Diag> d;
    (void)bhed::readScript(src, s, d);
    std::vector<bhed::Issue> is;
    bhed::validate(s, g_db, is);
    for (const auto& i : is)
        if (i.code == code) return true;
    return false;
}

static int g_fail = 0;

static void expect(const char* what, bool got, bool want) {
    if (got == want) { std::printf("  ok    %s\n", what); return; }
    std::printf("  FEHL  %s  (erwartet %s)\n", what, want ? "Treffer" : "kein Treffer");
    ++g_fail;
}

#define HDR "//Generated by BehavEd\r\n"

// Wie has(), aber liefert den Meldungstext des ersten Treffers.
static std::string meldung(const std::string& src, const char* code) {
    bhed::Script s;
    std::vector<bhed::Diag> d;
    (void)bhed::readScript(src, s, d);
    std::vector<bhed::Issue> is;
    bhed::validate(s, g_db, is);
    for (const auto& i : is) {
        if (i.code == code) { return i.message; }
    }
    return {};
}

static bool schlaegtVor(const std::string& feld, const char* erwartet) {
    const std::string m = meldung(
        HDR "set ( /*@SET_TYPES*/ \"" + feld + "\", \"1\" );\r\n", "V004");
    return m.find(std::string("meintest du ") + erwartet + "?") !=
           std::string::npos;
}

static bool ohneVorschlag(const std::string& feld) {
    const std::string m = meldung(
        HDR "set ( /*@SET_TYPES*/ \"" + feld + "\", \"1\" );\r\n", "V004");
    return !m.empty() && m.find("meintest du") == std::string::npos;
}


int main(int argc, char** argv) {
    if (argc < 3) { std::fprintf(stderr, "Aufruf: checks <behaved.bhc> <headerdir> [nachtrag]\n"); return 2; }
    std::vector<bhed::LoadDiag> ld;
    if (!bhed::loadCommandDb(argv[1], argv[2], g_db, ld)) return 2;
    if (argc > 3 && !bhed::loadCommandDb(argv[3], argv[2], g_db, ld)) return 2;

    // --- gueltige Skripte duerfen NICHT anschlagen -----------------------
    expect("gueltig: set mit Auswahl",
           has(HDR "set ( /*@SET_TYPES*/ \"SET_HEALTH\", 100 );\r\n", "V004"), false);
    expect("gueltig: camera FADE",
           has(HDR "camera ( /*@CAMERA_COMMANDS*/ FADE, < 0.000 0.000 0.000 >, 1.000, "
                   "< 0.000 0.000 0.000 >, 1.000, 1000 );\r\n", "V002"), false);
    expect("gueltig: Variablenform von set",
           has(HDR "set ( \"meinFlag\", \"1\" );\r\n", "V004"), false);
    expect("gueltig: Ausdruck statt Zahl",
           has(HDR "wait ( $get( FLOAT, \"x\" )$ );\r\n", "V008"), false);
    expect("gueltig: gesperrtes Makrofeld",
           has(HDR "set ( /*!*/ \"SET_WALKING\", /*!*/ \"true\" );\r\n", "V004"), false);
    expect("gueltig: blanker Wert aus %i-Menge",
           has(HDR "affect ( \"kyle\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n}\r\n", "V006"), false);

    // --- insertBefore ----------------------------------------------------
    //
    // Gebraucht, seit man aus der Ereignisliste ZWISCHEN zwei Zeilen ziehen
    // kann. Der interessante Fall ist die ERSTE Zeile: dort gibt es keinen
    // Vorgaenger, hinter den man einfuegen koennte - und genau davor will
    // man am haeufigsten etwas setzen.
    {
        auto nodeNamed = [](const char* nm) {
            bhed::Node n;
            n.kind = bhed::Node::Kind::Command;
            n.name = nm;
            return n;
        };

        // Leeres Skript: ein leerer Weg heisst "an den Anfang".
        {
            bhed::Document doc{bhed::Script{}};
            expect("insertBefore: leeres Skript nimmt den ersten Knoten",
                   doc.insertBefore(bhed::Path{}, nodeNamed("flush")), true);
            expect("insertBefore: er steht auch wirklich da",
                   doc.script().nodes.size() == 1U &&
                       doc.script().nodes[0].name == "flush",
                   true);
        }

        // Vor die erste Zeile - der Fall, den insertAfter nicht kann.
        {
            bhed::Document doc{bhed::Script{}};
            (void)doc.insertAfter(bhed::Path{}, nodeNamed("zwei"));
            (void)doc.insertAfter(bhed::Path{0}, nodeNamed("drei"));
            expect("insertBefore: vor die erste Zeile",
                   doc.insertBefore(bhed::Path{0}, nodeNamed("eins")), true);
            const auto& ns = doc.script().nodes;
            expect("insertBefore: Reihenfolge stimmt",
                   ns.size() == 3U && ns[0].name == "eins" &&
                       ns[1].name == "zwei" && ns[2].name == "drei",
                   true);
        }

        // Mittendrin.
        {
            bhed::Document doc{bhed::Script{}};
            (void)doc.insertAfter(bhed::Path{}, nodeNamed("a"));
            (void)doc.insertAfter(bhed::Path{0}, nodeNamed("c"));
            (void)doc.insertBefore(bhed::Path{1}, nodeNamed("b"));
            const auto& ns = doc.script().nodes;
            expect("insertBefore: zwischen zwei Zeilen",
                   ns.size() == 3U && ns[0].name == "a" && ns[1].name == "b" &&
                       ns[2].name == "c",
                   true);
        }

        // Unsinniger Weg darf nichts anfassen.
        {
            bhed::Document doc{bhed::Script{}};
            (void)doc.insertAfter(bhed::Path{}, nodeNamed("a"));
            expect("insertBefore: Weg ausserhalb wird abgewiesen",
                   doc.insertBefore(bhed::Path{7}, nodeNamed("x")), false);
            expect("insertBefore: und aendert nichts",
                   doc.script().nodes.size() == 1U, true);
        }

        // Rueckgaengig muss es auch wieder wegnehmen - sonst waere das
        // Ziehen die eine Bedienung ohne Sicherheitsnetz.
        {
            bhed::Document doc{bhed::Script{}};
            (void)doc.insertAfter(bhed::Path{}, nodeNamed("a"));
            (void)doc.insertBefore(bhed::Path{0}, nodeNamed("neu"));
            expect("insertBefore: laesst sich rueckgaengig machen",
                   doc.undo(), true);
            expect("insertBefore: danach ist der alte Stand da",
                   doc.script().nodes.size() == 1U &&
                       doc.script().nodes[0].name == "a",
                   true);
        }
    }

    // --- Wo liegt die animation.cfg? -------------------------------------
    //
    // Reihenfolge aus code/game/NPC_stats.cpp, G_ParseAnimationFile():
    // erst <skel>/<skel>.cfg, dann <skel>/animation.cfg. <skel> ist der
    // ORDNER, nicht der Dateiname.
    {
        const std::string md = "models/players/_humanoid_md/_humanoid";
        expect("skeletonName ist der Ordner, nicht die Datei",
               bhed::skeletonNameFor(md) == "_humanoid_md", true);
        const std::vector<std::string> c = bhed::animCfgCandidates(md);
        expect("zwei Kandidaten, in der Reihenfolge der Engine",
               c.size() == 2U &&
                   c[0] == "models/players/_humanoid_md/_humanoid_md.cfg" &&
                   c[1] == "models/players/_humanoid_md/animation.cfg",
               true);
        // Ravens eigenes Skelett: dort heissen Ordner und Datei gleich.
        const std::vector<std::string> h =
            bhed::animCfgCandidates("models/players/_humanoid/_humanoid");
        expect("_humanoid: erst _humanoid.cfg, dann animation.cfg",
               h.size() == 2U &&
                   h[0] == "models/players/_humanoid/_humanoid.cfg" &&
                   h[1] == "models/players/_humanoid/animation.cfg",
               true);
        expect("ein Pfad ohne Schraegstrich ergibt nichts",
               bhed::animCfgCandidates("humanoid").empty(), true);
    }


    //
    // Je 39 Verwendungen in den 284 Skripten der Mod. Sie steuern die ZEIT:
    // waitsignal haelt an, bis irgendwo signal mit demselben Namen faellt -
    // auch weiter unten im Skript, in einem anderen affect-Block, dessen
    // Uhr unabhaengig laeuft. Genau deshalb baut buildScene zweimal auf.
    //
    // Ohne das lief alles nach einem waitsignal zu frueh, und das ist bei
    // einer Zwischensequenz die Stelle, an der die Figuren auf den
    // Sprecher warten.
    {
        bhed::MapData map;
        bhed::parseEntities(
            "{\n\"classname\" \"NPC_spawner\"\n\"NPC_targetname\" \"a\"\n"
            "\"NPC_type\" \"kyle\"\n\"origin\" \"0 0 0\"\n}\n"
            "{\n\"classname\" \"NPC_spawner\"\n\"NPC_targetname\" \"b\"\n"
            "\"NPC_type\" \"kyle\"\n\"origin\" \"0 0 0\"\n}\n",
            map.entities);
        bhed::collectNames(map);
        bhed::Script sc;
        std::vector<bhed::Diag> dd;
        // a wartet auf ein Signal, das b erst nach 5000 ms setzt - und der
        // Block von b steht WEITER UNTEN. Eine Vorwaertsschau haette das
        // nicht gesehen.
        (void)bhed::readScript(
            "//Generated by BehavEd\r\n"
            "affect ( \"a\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\twaitsignal ( \"los\" );\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_ORIGIN\", \"100 0 0\" );\r\n"
            "}\r\n"
            "affect ( \"b\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\twait ( 5000.000 );\r\n"
            "\tsignal ( \"los\" );\r\n"
            "}\r\n",
            sc, dd);
        const bhed::Scene sn = bhed::buildScene(sc, map);
        const bhed::Actor* a = sn.find("a");
        expect("waitsignal: der Schritt danach ist da",
               a != nullptr && a->steps.size() == 1U, true);
        if (a != nullptr && !a->steps.empty()) {
            expect("waitsignal spult bis zum Signal vor (5000 ms)",
                   a->steps[0].startMs > 4990.0 && a->steps[0].startMs < 5010.0,
                   true);
            expect("vor dem Signal steht die Figur noch am Anfang",
                   a->at(1000.0).pos[0] < 1.0F, true);
            expect("danach ist sie versetzt", a->at(6000.0).pos[0] > 99.0F, true);
        }
        // Ein Signal, das nie faellt, darf nicht haengen lassen.
        bhed::Script sc2;
        (void)bhed::readScript(
            "//Generated by BehavEd\r\n"
            "affect ( \"a\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\twaitsignal ( \"gibtesnicht\" );\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_ORIGIN\", \"100 0 0\" );\r\n}\r\n",
            sc2, dd);
        const bhed::Scene sn2 = bhed::buildScene(sc2, map);
        const bhed::Actor* a2 = sn2.find("a");
        expect("ein Signal, das nie faellt, wird uebergangen",
               a2 != nullptr && a2->steps.size() == 1U, true);
    }

    // --- EINE Uhr fuer alle drei Auswerter -------------------------------
    //
    // Kamerabahn, Zeitleiste und Szene lesen dasselbe Skript und muessen
    // sich ueber die Zeit einig sein. Sie waren es nicht:
    //
    //   Befehl              camtrack   timeline        scene
    //   wait ( $random$ )   0          Mitte           Mitte
    //   waitsignal ( "x" )  0          0               bis zum Signal
    //
    // Zehn der 284 Skripte der Mod enthalten sowohl waitsignal als auch
    // camera-Befehle; dort lief die Kamera vor den Figuren her. Seit
    // bhed/clock.h gibt es nur noch eine Rechnung.
    {
        const std::string src =
            "//Generated by BehavEd\r\n"
            "camera ( /*@CAMERA_COMMANDS*/ ENABLE );\r\n"
            "waitsignal ( \"los\" );\r\n"
            "camera ( /*@CAMERA_COMMANDS*/ ZOOM, 40.000, 0.000 );\r\n"
            "affect ( \"b\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\twait ( 5000.000 );\r\n"
            "\tsignal ( \"los\" );\r\n"
            "}\r\n";
        bhed::Script sc;
        std::vector<bhed::Diag> dd;
        (void)bhed::readScript(src, sc, dd);

        // 1. Die gemeinsame Sammlung findet das Signal bei 5000.
        const bhed::SignalTimes sig = bhed::collectSignals(sc);
        expect("Signale werden zentral eingesammelt",
               sig.count("los") == 1U && sig.at("los") > 4990.0 &&
                   sig.at("los") < 5010.0,
               true);

        // 2. Die Kamerabahn wartet jetzt darauf. Vorher stand der Zoom bei
        //    0 ms, also vier Sekunden zu frueh.
        const bhed::CameraTrack ct = bhed::buildCameraTrack(sc);
        double zoomAt = -1.0;
        for (const bhed::CamSegment& seg : ct.segments) {
            if (seg.kind == bhed::CamSegment::Kind::Zoom) {
                zoomAt = seg.startMs;
            }
        }
        expect("die Kamerabahn wartet auf das Signal",
               zoomAt > 4990.0 && zoomAt < 5010.0, true);

        // 3. Und $random$ ergibt ueberall die Mitte, nicht nur an einer
        //    Stelle. Frueher gab camtrack dafuer 0 zurueck.
        bhed::Script sc2;
        (void)bhed::readScript(
            "//Generated by BehavEd\r\n"
            "camera ( /*@CAMERA_COMMANDS*/ ENABLE );\r\n"
            "wait ( $random( 1000.000, 3000.000 )$ );\r\n"
            "camera ( /*@CAMERA_COMMANDS*/ ZOOM, 40.000, 0.000 );\r\n",
            sc2, dd);
        const bhed::CameraTrack ct2 = bhed::buildCameraTrack(sc2);
        double zoom2 = -1.0;
        for (const bhed::CamSegment& seg : ct2.segments) {
            if (seg.kind == bhed::CamSegment::Kind::Zoom) {
                zoom2 = seg.startMs;
            }
        }
        expect("$random$ ergibt auch in der Kamerabahn die Mitte",
               zoom2 > 1990.0 && zoom2 < 2010.0, true);
        expect("readMs kennt $random$ direkt",
               bhed::readMs("$random( 100.000, 300.000 )$") > 199.0 &&
                   bhed::readMs("$random( 100.000, 300.000 )$") < 201.0,
               true);
        expect("und eine glatte Zahl bleibt eine glatte Zahl",
               bhed::readMs("2500.000") == 2500.0, true);
    }

    // --- move, rotate und die Bloecke ------------------------------------
    //
    // Gezaehlt an den 64 Skripten aus MD_Maps_Ep1/2/4/6: move 85 mal,
    // rotate 86 mal, do 56, task 42, if 24, loop 6. Nichts davon wurde
    // ausgewertet - der Flyby der Droidenjaeger hat GENAU EINEN Befehl
    // ausserhalb seines loop, alles andere fiel unter den Tisch.
    {
        bhed::MapData map;
        bhed::parseEntities("{\n\"classname\" \"func_static\"\n"
                            "\"targetname\" \"schiff\"\n"
                            "\"origin\" \"0 0 0\"\n\"angle\" \"350\"\n}\n",
                            map.entities);
        bhed::collectNames(map);
        bhed::Script sc;
        std::vector<bhed::Diag> dd;
        (void)bhed::readScript(
            "//Generated by BehavEd\r\n"
            "affect ( \"schiff\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\tloop ( 1.000 )\r\n\t{\r\n"
            "\t\tmove ( < 1000.000 0.000 0.000 >, < 0.000 10.000 0.000 >, 1000.000 );\r\n"
            "\t\twait ( $random( 1000.000, 3000.000 )$ );\r\n"
            "\t\trotate ( < 0.000 90.000 0.000 >, 1000.000 );\r\n"
            "\t}\r\n}\r\n",
            sc, dd);
        const bhed::Scene sn = bhed::buildScene(sc, map);
        const bhed::Actor* a = sn.find("schiff");
        expect("in den loop hineingestiegen: zwei Schritte statt keiner",
               a != nullptr && a->steps.size() == 2U, true);
        if (a != nullptr && a->steps.size() == 2U) {
            // move: TR_NONLINEAR_STOP wie in der Engine (g_mover.cpp:648):
            // nach halber Dauer sin(45 Grad) = 70,7 % der Strecke.
            const bhed::ActorState halb = a->at(500.0);
            expect("move bewegt weich: nach 500 ms 70,7 % der Strecke",
                   halb.pos[0] > 690.0F && halb.pos[0] < 725.0F, true);
            expect("move dreht mit: 350 -> 10 Grad ueber den KUERZEREN Weg",
                   halb.angles[1] > 355.0F || halb.angles[1] < 5.0F, true);
            const bhed::ActorState fertig = a->at(1000.0);
            expect("move ist nach der Dauer am Ziel",
                   fertig.pos[0] > 999.0F, true);
            // $random(1000, 3000)$ ergibt die Mitte, also 2000.
            //
            // Der rotate beginnt damit bei 2000, NICHT bei 3000: move
            // haelt den Ablauf nicht an. Ich hatte hier zuerst 3000
            // erwartet und damit meiner eigenen Beschreibung von move
            // widersprochen - die Probe hat es gefangen.
            expect("random nimmt die Mitte: rotate beginnt bei 2000 ms",
                   a->steps[1].startMs > 1990.0 && a->steps[1].startMs < 2010.0,
                   true);
            const bhed::ActorState gedreht = a->at(3000.0);
            expect("rotate ist am Ende bei 90 Grad",
                   gedreht.angles[1] > 89.0F && gedreht.angles[1] < 91.0F, true);
            expect("rotate laesst den Ort in Ruhe",
                   gedreht.pos[0] > 999.0F, true);
        }
    }

    // --- affect trifft JEDE benannte Entity, nicht nur Figuren ----------
    //
    // code/game/Q3_Interface.cpp, CQuake3GameInterface::GetByName():
    //
    //     ei = m_EntityList.find( Q_strupr( (char *) temp ) );
    //
    // Eine Liste ueber ALLE benannten Entities, und der Schluessel ist in
    // Grossbuchstaben - die Suche ist also unempfindlich gegen Gross- und
    // Kleinschreibung.
    //
    // Nachgezaehlt an den 23 Karten aus MD_Maps_Ep1/2/4/6: von den 25
    // aufloesbaren affect-Zielen in den mitgelieferten Skripten ist KEIN
    // EINZIGES ein NPC. Es sind func_usable, func_static, trigger_multiple,
    // func_breakable, func_door - Tueren, Plattformen, fliegende Schiffe.
    {
        bhed::MapData map;
        bhed::parseEntities(
            "{\n\"classname\" \"func_static\"\n\"targetname\" \"theFalcon_Ramp\"\n"
            "\"origin\" \"10 20 30\"\n\"angle\" \"90\"\n}\n"
            "{\n\"classname\" \"NPC_spawner\"\n\"NPC_targetname\" \"kanan1\"\n"
            "\"NPC_type\" \"md_kanan\"\n\"origin\" \"1 2 3\"\n}\n",
            map.entities);
        bhed::collectNames(map);
        bhed::Script sc;
        std::vector<bhed::Diag> dd;
        // Das Skript schreibt den Namen KLEIN, die Karte gross.
        (void)bhed::readScript(
            "//Generated by BehavEd\r\n"
            "affect ( \"thefalcon_ramp\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n}\r\n"
            "affect ( \"KANAN1\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n}\r\n",
            sc, dd);
        const bhed::Scene sn = bhed::buildScene(sc, map);
        const bhed::Actor* ramp = sn.find("thefalcon_ramp");
        const bhed::Actor* kanan = sn.find("KANAN1");
        expect("affect trifft auch eine func_static",
               ramp != nullptr && ramp->haveStart, true);
        expect("und uebernimmt ihren Ort",
               ramp != nullptr && ramp->start[0] == 10.0F &&
                   ramp->start[1] == 20.0F && ramp->start[2] == 30.0F,
               true);
        expect("und ihren Winkel",
               ramp != nullptr && ramp->startAngles[1] == 90.0F, true);
        expect("ein Nicht-NPC bekommt keinen NPC_type",
               ramp != nullptr && ramp->npcType.empty(), true);
        expect("Gross- und Kleinschreibung ist egal (Q_strupr)",
               kanan != nullptr && kanan->haveStart &&
                   kanan->npcType == "md_kanan",
               true);
    }

    // --- absichtliche Verletzungen MUESSEN anschlagen --------------------
    expect("V001 unbekannter Befehl",
           has(HDR "gibtesnicht ( \"x\" );\r\n", "V001"), true);
    expect("V002 falsche Stelligkeit",
           has(HDR "sound ( /*@CHANNELS*/ CHAN_VOICE, \"a.mp3\", \"zuviel\" );\r\n", "V002"), true);
    expect("V004 Wert nicht in der Auswahlliste",
           has(HDR "set ( /*@SET_TYPES*/ \"SET_GIBTESNICHT\", \"1\" );\r\n", "V004"), true);

    // --- "Meintest du ...?" fuer die sechs Umbenennungen seit JK2 --------
    //
    // Das ICARUS_Manual.doc ist aelter als Jedi Academy und nennt diese
    // sechs Felder ohne Unterstrich. Wer nach dem Handbuch arbeitet -
    // und es ist die einzige Anleitung - schreibt die linke Spalte.
    // Gemessen gegen das Original-Q3_Interface.h (261 Felder).
    expect("Vorschlag SET_BEHAVIORSTATE",
           schlaegtVor("SET_BEHAVIORSTATE", "SET_BEHAVIOR_STATE"), true);
    expect("Vorschlag SET_COPYORIGIN",
           schlaegtVor("SET_COPYORIGIN", "SET_COPY_ORIGIN"), true);
    expect("Vorschlag SET_DEFAULTBSTATE",
           schlaegtVor("SET_DEFAULTBSTATE", "SET_DEFAULT_BSTATE"), true);
    expect("Vorschlag SET_ENEMYTEAM",
           schlaegtVor("SET_ENEMYTEAM", "SET_ENEMY_TEAM"), true);
    expect("Vorschlag SET_LOCKEDENEMY",
           schlaegtVor("SET_LOCKEDENEMY", "SET_LOCKED_ENEMY"), true);
    expect("Vorschlag SET_PLAYERTEAM",
           schlaegtVor("SET_PLAYER" "TEAM", "SET_PLAYER_TEAM"), true);

    // --- und KEIN Vorschlag, wo keiner hingehoert ------------------------
    //
    // Diese acht gibt es in JKA wirklich nicht mehr. Ein Vorschlag waere
    // hier schaedlich: er schickt jemanden zu einem anderen Feld.
    // SET_STUCKSCRIPT stand bei Abstand <= 3 faelschlich auf
    // SET_ATTACKSCRIPT - deshalb ist die Schwelle 2.
    expect("kein Vorschlag SET_STUCKSCRIPT",  ohneVorschlag("SET_STUCKSCRIPT"), true);
    expect("kein Vorschlag SET_CAPTUREGOAL",  ohneVorschlag("SET_CAPTUREGOAL"), true);
    expect("kein Vorschlag SET_TEMPBEHAVIOR", ohneVorschlag("SET_TEMPBEHAVIOR"), true);
    expect("kein Vorschlag SET_AFFIRMNEGTARG",ohneVorschlag("SET_AFFIRMNEGTARG"), true);
    expect("kein Vorschlag SET_PRECACHE",     ohneVorschlag("SET_PRECACHE"), true);
    expect("kein Vorschlag bei Unsinn",       ohneVorschlag("SET_ZZZZQQQQXXXX"), true);

    // --- Ein EIGENER Wert muss durchkommen -------------------------------
    //
    // Movie Duels bringt Animationen mit, die in keiner .bhc stehen. Die
    // Oberflaeche laesst sie jetzt sichtbar eintippen ("... uebernehmen"
    // ganz oben in der Auswahlliste). Damit das etwas taugt, muss der Wert
    // drei Dinge ueberstehen:
    //
    //   1. Er darf nur eine ANMERKUNG ausloesen, keinen Fehler - sonst ist
    //      das Skript rot, obwohl es richtig ist.
    //   2. Er muss unveraendert zurueckgeschrieben werden.
    //   3. Er darf nicht still durch einen Listeneintrag ersetzt werden.
    {
        const std::string src =
            HDR "set ( /*@SET_TYPES*/ \"SET_ANIM_BOTH\", \"BOTH_MD_EIGENE_ANIM\" );\r\n";
        bhed::Script sc;
        std::vector<bhed::Diag> d;
        (void)bhed::readScript(src, sc, d);
        std::vector<bhed::Issue> iss;
        bhed::validate(sc, g_db, iss);
        bool onlyWarning = true;
        for (const bhed::Issue& i : iss) {
            if (i.level == bhed::Issue::Level::Error) { onlyWarning = false; }
        }
        expect("eigener Wert ist hoechstens eine Anmerkung, kein Fehler",
               onlyWarning, true);
        const std::string back = bhed::writeScript(sc);
        expect("eigener Wert steht unveraendert wieder da",
               back.find("BOTH_MD_EIGENE_ANIM") != std::string::npos, true);
        expect("eigener Wert kommt bytegleich zurueck", back == src, true);
    }
    expect("V006 %i-Menge faelschlich zitiert",
           has(HDR "affect ( \"kyle\", /*@AFFECT_TYPE*/ \"FLUSH\" )\r\n{\r\n}\r\n", "V006"), true);
    expect("V007 falsche Annotation",
           has(HDR "affect ( \"kyle\", /*@BOOL_TYPES*/ FLUSH )\r\n{\r\n}\r\n", "V007"), true);
    expect("V008 Text statt Zahl",
           has(HDR "set ( /*@SET_TYPES*/ \"SET_HEALTH\", \"viel\" );\r\n", "V008"), true);
    expect("V010 fehlender Block",
           has(HDR "task ( \"t\" );\r\n", "V010"), true);
    expect("V010 unerwarteter Block",
           has(HDR "print ( \"x\" )\r\n{\r\n}\r\n", "V010"), true);
    expect("V011 Textfeld ohne Anfuehrungszeichen",
           has(HDR "print ( 42 );\r\n", "V011"), true);

    // --- Baumansicht -----------------------------------------------------
    {
        const std::string src = HDR
            "//$\"walkOnly\"@2\r\n"
            "set ( /*!*/ \"SET_WALKING\", /*!*/ \"true\" );\r\n"
            "set ( /*!*/ \"SET_RUNNING\", /*!*/ \"false\" );\r\n"
            "affect ( \"kyle\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\twait ( 1000.000 );\r\n}\r\n";
        bhed::Script sc;
        std::vector<bhed::Diag> d;
        (void)bhed::readScript(src, sc, d);

        // Zugeklappt gegen aufgeklappt. Der Schalter dafuer ist der
        // Aufklappzustand, nicht foldMacros - letzterer bestimmt nur, OB
        // die Befehle ueberhaupt Kinder des Makros werden.
        bhed::TreeOptions o;
        bhed::Expanded closed;
        o.expanded = &closed;
        std::vector<bhed::Row> folded;
        bhed::buildTree(sc, g_db, o, folded);

        bhed::Expanded opened;
        opened.openAll();
        o.expanded = &opened;
        std::vector<bhed::Row> open_;
        bhed::buildTree(sc, g_db, o, open_);

        // Zugeklappt bleiben zwei Zeilen: der Makroknoten und der
        // affect-Block. Aufgeklappt kommen die zwei Makrobefehle und das
        // eine wait im Block dazu.
        expect("Baum: zugeklappt bleiben Makro und Block", folded.size() == 2, true);
        expect("Baum: aufgeklappt kommen drei Zeilen dazu",
               open_.size() - folded.size() == 3, true);
        expect("Baum: Makrozeile traegt I_MACRO",
               !folded.empty() && folded[0].icon == "I_MACRO", true);
        expect("Baum: Symbol kommt aus der .bhc",
               open_.size() > 1 && open_[1].icon == "I_SET", true);
        expect("Baum: gesperrtes Feld erkannt",
               open_.size() > 1 && open_[1].locked, true);
        expect("Baum: Blockbefehl hat Kinder",
               !open_.empty() && open_.back().depth == 1, true);

        // --- Zwei Spalten statt einer Beschriftung ------------------------
        //
        // Die Anzeige setzt Name und Argumente getrennt, damit die Klammern
        // untereinander stehen. text muss weiterhin genau Name + " " +
        // args sein, sonst laufen Anzeige und Ziehtext auseinander.
        {
            bool split = true;
            for (const bhed::Row& r : open_) {
                if (r.what != bhed::Row::What::Command) { continue; }
                if (r.name.empty() || r.args.empty()) { split = false; break; }
                if (r.text != r.name + " " + r.args) { split = false; break; }
            }
            expect("Baum: Name und Argumente getrennt, text bleibt gleich",
                   split, true);
            expect("Baum: Argumente beginnen mit der Klammer",
                   open_.size() > 1 && !open_[1].args.empty() &&
                       open_[1].args.front() == '(',
                   true);
        }

        // --- Letztes Kind ----------------------------------------------
        //
        // Nur fuer die gepunkteten Linien: dort hoert die Senkrechte auf
        // halber Hoehe auf. Geprueft wird die Regel, nicht das Zeichnen -
        // die letzte Zeile ueberhaupt ist immer ein letztes Kind, und eine
        // Zeile mit einem Geschwister danach ist es nie.
        {
            expect("Baum: letzte Zeile ist letztes Kind",
                   !open_.empty() && open_.back().lastChild, true);
            bool ok = true;
            for (std::size_t i = 0; i + 1 < open_.size(); ++i) {
                if (open_[i].depth != open_[i + 1].depth) { continue; }
                // Gleiche Ebene direkt danach: dann war es NICHT das letzte.
                if (open_[i].lastChild) { ok = false; break; }
            }
            expect("Baum: Zeile mit Geschwister danach ist nicht letztes Kind",
                   ok, true);
        }

        // --- Spaltenmasse gegen das Bildschirmfoto ------------------------
        //
        // Bei MS Sans Serif 8pt ist die Schrift rund 13 Punkte hoch. Genau
        // dort muessen die Verhaeltniszahlen die gemessenen Werte treffen,
        // sonst sind sie beim naechsten Anfassen still verrutscht.
        {
            const bhed::TreeMetrics m = bhed::treeMetricsFor(13.0F);
            expect("Masse: Einrueckung je Ebene 19", m.indent == 19.0F, true);
            expect("Masse: Kaestchen 9", m.box == 9.0F, true);
            expect("Masse: Symbol bei 11", m.iconAt == 11.0F, true);
            expect("Masse: Name bei 33", m.nameAt == 33.0F, true);
            expect("Masse: Namensspalte 59 breit", m.nameW == 59.0F, true);
            // Und beim Zoomen muss die Ordnung erhalten bleiben.
            const bhed::TreeMetrics big = bhed::treeMetricsFor(26.0F);
            expect("Masse: skalieren behaelt die Reihenfolge",
                   big.box < big.iconAt && big.iconAt < big.nameAt &&
                       big.nameAt < big.nameW && big.indent > big.box,
                   true);
        }

        bhed::TreeOptions t;
        t.showTypes = true;
        std::vector<bhed::Row> withTypes;
        bhed::buildTree(sc, g_db, t, withTypes);
        bool ann = false;
        for (const auto& r : withTypes)
            if (r.text.find("<AFFECT_TYPE>") != std::string::npos) ann = true;
        // Der Baum schreibt <AFFECT_TYPE>, nicht /*@AFFECT_TYPE*/ - so steht
        // es im Bildschirmfoto des Originals.
        expect("Baum: Show Types zeigt <TYPMENGE>", ann, true);

        bhed::TreeOptions gf;
        gf.gFloats = true;
        std::vector<bhed::Row> withG;
        bhed::buildTree(sc, g_db, gf, withG);
        bool trimmed = false;
        for (const auto& r : withG)
            if (r.text.find("wait ( 1000 )") != std::string::npos) trimmed = true;
        expect("Baum: %g floats kuerzt 1000.000 auf 1000", trimmed, true);
    }

    // --- Bearbeiten -------------------------------------------------------
    {
        const std::string src = HDR
            "print ( \"eins\" );\r\n"
            "print ( \"zwei\" );\r\n"
            "affect ( \"kyle\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\tprint ( \"drin\" );\r\n}\r\n";
        bhed::Script sc;
        std::vector<bhed::Diag> d;
        (void)bhed::readScript(src, sc, d);
        const std::string base = bhed::writeScript(sc);

        {   // moveUp muss tatsaechlich vertauschen
            bhed::Document doc{sc};
            expect("Bearbeiten: moveUp meldet Erfolg", doc.moveUp({1}), true);
            const std::string t = bhed::writeScript(doc.script());
            expect("Bearbeiten: moveUp vertauscht wirklich", t != base, true);
            expect("Bearbeiten: zwei steht jetzt vor eins",
                   t.find("\"zwei\"") < t.find("\"eins\""), true);
            expect("Bearbeiten: moveUp am Anfang wird abgewiesen", doc.moveUp({0}), false);
            expect("Bearbeiten: undo stellt her", doc.undo() && bhed::writeScript(doc.script()) == base, true);
        }
        {   // moveDown ebenso
            bhed::Document doc{sc};
            expect("Bearbeiten: moveDown vertauscht wirklich",
                   doc.moveDown({0}) && bhed::writeScript(doc.script()) != base, true);
        }
        {   // Klonen verdoppelt genau einen Knoten
            bhed::Document doc{sc};
            const std::size_t before = doc.script().nodes.size();
            expect("Bearbeiten: cloneAt", doc.cloneAt({0}), true);
            expect("Bearbeiten: cloneAt fuegt genau einen Knoten ein",
                   doc.script().nodes.size() == before + 1, true);
            expect("Bearbeiten: Klon steht direkt hinter dem Vorbild",
                   doc.script().nodes[1].args.size() == 1 &&
                   doc.script().nodes[1].args[0].text == "eins", true);
        }
        {   // insertAfter ebenso positionsgenau
            bhed::Document doc{sc};
            const std::vector<const bhed::Command*> ov = g_db.overloads("flush");
            expect("Bearbeiten: insertAfter",
                   !ov.empty() && doc.insertAfter({0}, bhed::makeNode(*ov.front(), g_db)), true);
            expect("Bearbeiten: insertAfter setzt an Stelle 1",
                   doc.script().nodes.size() > 1 &&
                   doc.script().nodes[1].name == "flush", true);
        }
        {   // Ausschneiden und Einfuegen behaelt den Block
            bhed::Document doc{sc};
            expect("Bearbeiten: cutAt Block", doc.cutAt({2}), true);
            expect("Bearbeiten: pasteAfter", doc.pasteAfter({0}), true);
            const std::string t = bhed::writeScript(doc.script());
            expect("Bearbeiten: eingefuegter Block behaelt sein Kind",
                   t.find("\"drin\"") != std::string::npos, true);
            // Position, nicht nur Anwesenheit: nach "eins", vor "zwei".
            expect("Bearbeiten: pasteAfter fuegt HINTER dem Knoten ein",
                   t.find("\"eins\"") < t.find("affect") &&
                   t.find("affect") < t.find("\"zwei\""), true);
            expect("Bearbeiten: Block steht an Stelle 1",
                   doc.script().nodes.size() > 1 &&
                   doc.script().nodes[1].name == "affect", true);
        }
        {   // Wiederholen-Stapel muss nach einer neuen Bearbeitung leer sein
            bhed::Document doc{sc};
            (void)doc.cloneAt({0});
            (void)doc.undo();
            expect("Bearbeiten: redo nach undo moeglich", doc.redoDepth() == 1, true);
            (void)doc.moveDown({0});
            expect("Bearbeiten: neue Bearbeitung leert den Wiederholen-Stapel",
                   doc.redoDepth() == 0, true);
            expect("Bearbeiten: redo danach abgewiesen", doc.redo(), false);
        }
        {   // Ungueltige Wege aendern nichts
            bhed::Document doc{sc};
            expect("Bearbeiten: ungueltiger Weg abgewiesen", doc.removeAt({99}), false);
            expect("Bearbeiten: Skript unveraendert",
                   bhed::writeScript(doc.script()) == base, true);
            expect("Bearbeiten: kein Eintrag im Rueckgaengig-Stapel",
                   doc.undoDepth() == 0, true);
        }
        {   // Neuer Knoten aus einer Signatur
            const std::vector<const bhed::Command*> ov = g_db.overloads("sound");
            expect("Bearbeiten: sound-Signatur vorhanden", !ov.empty(), true);
            if (!ov.empty()) {
                const bhed::Node n = bhed::makeNode(*ov.front(), g_db);
                expect("Bearbeiten: makeNode setzt zwei Felder", n.args.size() == 2, true);
                expect("Bearbeiten: %i-Menge wird blank angelegt",
                       n.args[0].kind == bhed::Arg::Kind::Ident, true);
            }
        }
        {   // Suchen - wie das Original (ABGLEICH-VERHALTEN.md)
            bhed::FindOptions o;
            o.contains = "drin";
            expect("Suchen: Argument im Block", bhed::findAll(sc, o).size() == 1, true);
            bhed::FindOptions n;
            n.named = "drin";
            expect("Suchen: 'called' prueft nur den Befehlsnamen",
                   bhed::findAll(sc, n).empty(), true);
            bhed::FindOptions c;
            c.named = "print";
            expect("Suchen: drei print-Zeilen", bhed::findAll(sc, c).size() == 3, true);
            bhed::FindOptions k;
            k.contains = "print";
            expect("Suchen: 'containing' prueft nicht den Befehlsnamen",
                   bhed::findAll(sc, k).empty(), true);
            bhed::FindOptions w;
            w.named = "ein";
            expect("Suchen: Ganzwort findet Teilwort nicht",
                   bhed::findAll(sc, w).empty(), true);
        }
    }

    // --- Uebersetzung und Farbgebung -------------------------------------
    {
        using bhed::i18n::Language;
        using bhed::i18n::Str;
        bool alleGefuellt = true;
        bool alleVerschieden = false;
        for (int i = 0; i < static_cast<int>(Str::Count); ++i) {
            const auto id = static_cast<Str>(i);
            for (Language l : {Language::English, Language::German,
                               Language::ChineseSimplified, Language::Japanese}) {
                const char* t = bhed::i18n::trIn(l, id);
                if (t == nullptr || t[0] == '\0') { alleGefuellt = false; }
            }
            // mindestens ein Text muss sich zwischen Englisch und Deutsch
            // unterscheiden, sonst ist die Tabelle nur kopiert
            if (std::string(bhed::i18n::trIn(Language::English, id)) !=
                bhed::i18n::trIn(Language::German, id)) {
                alleVerschieden = true;
            }
        }
        expect("i18n: kein leerer Text in vier Sprachen", alleGefuellt, true);
        expect("i18n: Deutsch ist nicht nur kopiertes Englisch", alleVerschieden, true);
        expect("i18n: de-DE wird Deutsch",
               bhed::i18n::fromSystemLocale("de-DE") == Language::German, true);
        expect("i18n: zh-Hant faellt auf Englisch zurueck",
               bhed::i18n::fromSystemLocale("zh-Hant-TW") == Language::English, true);
        expect("i18n: zh-CN wird Vereinfachtes Chinesisch",
               bhed::i18n::fromSystemLocale("zh-CN") == Language::ChineseSimplified, true);
        expect("i18n: unbekanntes Gebiet wird Englisch",
               bhed::i18n::fromSystemLocale("fi-FI") == Language::English, true);

        bool alleAA = true;
        for (const auto& t : bhed::theme::themes()) {
            if (bhed::theme::worstContrast(t) < 4.5F) { alleAA = false; }
        }
        expect("Farbgebung: alle erreichen WCAG AA (4,5:1)", alleAA, true);
        expect("Farbgebung: sechs Stueck", bhed::theme::themes().size() == 6, true);
        expect("Farbgebung: klassische ist ueber Kennung findbar",
               bhed::theme::findTheme("behaved-classic") != nullptr, true);
        // Gegenprobe der Kontrastrechnung selbst
        expect("Kontrast: Schwarz auf Weiss ist 21:1",
               bhed::theme::contrastRatio({0, 0, 0, 1}, {1, 1, 1, 1}) > 20.9F, true);
        expect("Kontrast: Grau auf Grau faellt durch",
               bhed::theme::contrastRatio({0.5F, 0.5F, 0.5F, 1}, {0.55F, 0.55F, 0.55F, 1}) < 1.3F, true);
    }

    // --- argForParam mit GEAENDERTEM Wert --------------------------------
    //
    // Der Rundgang ueber den Bestand (edittour) aendert nie etwas und deckt
    // deshalb nur die Regel "unveraendert bleibt unveraendert" ab. Eine
    // Mutationsprobe hat gezeigt, dass die beiden anderen Regeln dabei
    // voellig ungeprueft blieben. Hier stehen sie.
    {
        using bhed::Arg;
        using bhed::Param;

        auto param = [](Param::Kind k, const char* ts = "") {
            Param p;
            p.kind = k;
            p.typeset = ts;
            return p;
        };
        auto arg = [](Arg::Kind k, const char* text, const char* ts = "") {
            Arg a;
            a.kind = k;
            a.text = text;
            a.typeset = ts;
            return a;
        };

        // Stand ein Ausdruck drin, bleibt es einer - auch in einem %v-Feld.
        //     set ( "SET_ORIGIN", $tag( "press1", ORIGIN)$ )
        const Arg wasExpr = arg(Arg::Kind::Expr, "tag( \"a\", ORIGIN)");
        const Arg r1 = bhed::argForParam(param(Param::Kind::Vector),
                                         "tag( \"b\", ORIGIN)", g_db, &wasExpr);
        expect("argForParam: Ausdruck bleibt Ausdruck, auch im Vektorfeld",
               r1.kind == Arg::Kind::Expr, true);

        // In einem Ausdrucksfeld bleibt eine blanke Zahl blank.
        //     move ( $tag( "cp1", ORIGIN)$, 0.000 )
        const Arg wasNumber = arg(Arg::Kind::Number, "0.000");
        const Arg r2 = bhed::argForParam(param(Param::Kind::Expr), "1.500",
                                         g_db, &wasNumber);
        expect("argForParam: blanke Zahl im Ausdrucksfeld bleibt blank",
               r2.kind == Arg::Kind::Number, true);

        // ... und ein $2$ bleibt ein $2$.
        const Arg wasDollar = arg(Arg::Kind::Expr, "2");
        const Arg r3 = bhed::argForParam(param(Param::Kind::Expr), "3",
                                         g_db, &wasDollar);
        expect("argForParam: $2$ bleibt Ausdrucksform", r3.kind == Arg::Kind::Expr, true);

        // Geaenderter Wert in einem Auswahlfeld bekommt die Annotation.
        const Arg wasPlain = arg(Arg::Kind::String, "SET_WALKING");
        const Arg r4 = bhed::argForParam(param(Param::Kind::TypeSet, "SET_TYPES"),
                                         "SET_RUNNING", g_db, &wasPlain);
        expect("argForParam: geaenderter Auswahlwert bekommt /*@TYPMENGE*/",
               r4.typeset == "SET_TYPES", true);

        // Unveraendert: keine Annotation anhaengen (Makroausklappungen).
        const Arg r5 = bhed::argForParam(param(Param::Kind::TypeSet, "SET_TYPES"),
                                         "SET_WALKING", g_db, &wasPlain);
        expect("argForParam: unveraenderter Wert behaelt fehlende Annotation",
               r5.typeset.empty(), true);

        // %i-Typmenge steht blank, %s in Anfuehrungszeichen.
        const Arg r6 = bhed::argForParam(param(Param::Kind::TypeSet, "AFFECT_TYPE"),
                                         "INSERT", g_db, nullptr);
        expect("argForParam: %i-Typmenge blank", r6.kind == Arg::Kind::Ident, true);
        const Arg r7 = bhed::argForParam(param(Param::Kind::TypeSet, "SET_TYPES"),
                                         "SET_HEALTH", g_db, nullptr);
        expect("argForParam: %s-Typmenge zitiert", r7.kind == Arg::Kind::String, true);

        // Gesperrtes Feld bleibt gesperrt.
        Arg locked = arg(Arg::Kind::String, "true");
        locked.locked = true;
        const Arg r8 = bhed::argForParam(param(Param::Kind::String), "false",
                                         g_db, &locked);
        expect("argForParam: /*!*/ bleibt erhalten", r8.locked, true);
    }

    // --- Einstellungen ---------------------------------------------------
    {
        bhed::Settings a;
        a.scriptPath = "C:/base/scripts";
        a.ibizePath = "C:/tools/IBIZE.EXE";
        a.commandFile = "C:/tools/behaved.bhc";
        a.reopenLastFile = true;
        a.language = "de";
        a.theme = "behaved-classic";
        a.uiScale = 1.5F;
        a.showTypes = true;
        a.foldMacros = false;
        for (const char* f : {"a.icarus", "b.icarus", "c.icarus"}) { a.noteRecent(f); }

        bhed::Settings b;
        expect("Einstellungen: gelesen", bhed::readSettings(bhed::writeSettings(a), b), true);
        expect("Einstellungen: Rundlauf gleich",
               bhed::writeSettings(b) == bhed::writeSettings(a), true);
        expect("Einstellungen: neueste Datei zuerst",
               !b.recent.empty() && b.recent[0] == "c.icarus", true);

        // Dublette wandert nach vorn, statt sich zu verdoppeln
        a.noteRecent("a.icarus");
        expect("Einstellungen: Dublette wandert nach vorn",
               a.recent.size() == 3 && a.recent[0] == "a.icarus", true);

        // Liste laeuft nicht ueber
        for (int i = 0; i < 20; ++i) { a.noteRecent(std::to_string(i) + ".icarus"); }
        expect("Einstellungen: Liste bleibt begrenzt",
               a.recent.size() == bhed::Settings::kMaxRecent, true);

        // Die Schalter aus Dialog 131 muessen den Rundlauf ueberstehen.
        bhed::Settings d;
        d.alternativeIcons = true;
        d.queryOnDiscard = false;
        d.dialogUsesLastDir = false;
        d.lastDir = "C:/base/scripts/taspir2";
        d.splitButtons = 0.22F;
        bhed::Settings e;
        (void)bhed::readSettings(bhed::writeSettings(d), e);
        expect("Einstellungen: alternative Symbole", e.alternativeIcons, true);
        expect("Einstellungen: Nachfrage abschaltbar", !e.queryOnDiscard, true);
        expect("Einstellungen: letzter Ordner", e.lastDir == d.lastDir, true);
        expect("Einstellungen: Spaltenteilung", e.splitButtons > 0.21F, true);

        // --- Eigene Tastenbelegungen ------------------------------------
        //
        // Gespeichert wird die ZAHL eines ImGuiKeyChord, nicht der Name der
        // Taste - imgui.h sagt zu GetKeyName ausdruecklich, die Namen seien
        // "not meant to be saved persistently nor compared". Was hier
        // geprueft wird, ist genau das: die Zahl kommt unveraendert zurueck.
        {
            bhed::Settings k;
            k.keyBindings.push_back({"MoveUp", 12345});
            k.keyBindings.push_back({"MoveDown", 12346});
            k.keyBindings.push_back({"Delete", 0});   // ausdruecklich KEINE Taste
            bhed::Settings back;
            (void)bhed::readSettings(bhed::writeSettings(k), back);
            expect("Belegungen: alle drei wieder da",
                   back.keyBindings.size() == 3U, true);
            bool same = back.keyBindings.size() == 3U;
            for (std::size_t i = 0; same && i < back.keyBindings.size(); ++i) {
                same = back.keyBindings[i].action == k.keyBindings[i].action &&
                       back.keyBindings[i].chord == k.keyBindings[i].chord;
            }
            expect("Belegungen: Kennung und Zahl unveraendert", same, true);
            // Eine kaputte Zeile darf die anderen nicht mitreissen.
            bhed::Settings bad;
            (void)bhed::readSettings("key=MoveUp keineZahl\nkey=MoveDown 7\n"
                                     "key=OhneZahl\n",
                                     bad);
            expect("Belegungen: kaputte Zeile wird uebergangen",
                   bad.keyBindings.size() == 1U &&
                       bad.keyBindings[0].action == "MoveDown" &&
                       bad.keyBindings[0].chord == 7,
                   true);
        }

        // Die Kennungen der Aktionen duerfen sich NICHT aendern - sonst
        // verliert jeder seine eigenen Belegungen. Deshalb hier festgehalten.
        {
            expect("Aktionen: MoveUp kennt sich selbst",
                   bhed::keys::fromName("MoveUp") == bhed::keys::Action::MoveUp,
                   true);
            expect("Aktionen: unbekannter Name ergibt Unhandled",
                   bhed::keys::fromName("GibtEsNicht") ==
                       bhed::keys::Action::Unhandled,
                   true);
            bool alleEindeutig = true;
            const auto& bs = bhed::keys::bindable();
            for (std::size_t i = 0; i < bs.size(); ++i) {
                for (std::size_t j = i + 1; j < bs.size(); ++j) {
                    if (std::string(bs[i].name) == bs[j].name ||
                        bs[i].action == bs[j].action) {
                        alleEindeutig = false;
                    }
                }
            }
            expect("Aktionen: jede Kennung und jede Aktion nur einmal",
                   alleEindeutig, true);
        }

        // Eine kaputte Datei darf das Fenster nicht unbedienbar machen
        bhed::Settings c;
        (void)bhed::readSettings("uiScale=99999\nmuell ohne gleichheitszeichen\n"
                                 "unbekannterSchluessel=egal\n", c);
        expect("Einstellungen: unsinniger Massstab wird verworfen",
               c.uiScale >= 0.5F && c.uiScale <= 4.0F, true);
        expect("Einstellungen: unbekannter Schluessel wird uebergangen",
               bhed::readSettings("neuerSchluessel=1\n", c), true);
    }

    // --- Tastenkuerzel ----------------------------------------------------
    expect("Tasten: Strg+A ist Speichern unter",
           bhed::keys::lookup(bhed::keys::Mod::Ctrl, 'A') == bhed::keys::Action::SaveAs, true);
    expect("Tasten: 23 Eintraege wie in der Ressource",
           bhed::keys::table().size() == 23, true);

    // --- Was die Helferzeilen des Editors bauen --------------------------
    //
    // Sie erzeugen Text, der anschliessend durch Leser, Schreiber und
    // Uebersetzer muss. Wenn dort ein Leerzeichen zu viel oder ein
    // Anfuehrungszeichen zu wenig steht, faellt es sonst erst auf, wenn
    // jemand ein Skript damit gebaut hat.
    {
        const char* kFromHelpers[] = {
            "get( FLOAT, \"SET_PARM1\" )",
            "get( STRING, \"SET_PARM1\" )",
            "tag( \"cp1\", ORIGIN )",
            "tag( \"at1\", ANGLES )",
            "random( 0.000, 1.000 )",
        };
        for (const char* e : kFromHelpers) {
            const std::string src = std::string(HDR) + "wait ( $" + e + "$ );\r\n";
            bhed::Script sc;
            std::vector<bhed::Diag> d;
            const bool read = bhed::readScript(src, sc, d);
            expect((std::string("Helfer lesbar: ") + e).c_str(), read, true);
            expect((std::string("Helfer bytegleich: ") + e).c_str(),
                   bhed::writeScript(sc) == src, true);

            std::vector<bhed::IbiBlock> bl;
            std::vector<bhed::Diag> cd;
            expect((std::string("Helfer uebersetzbar: ") + e).c_str(),
                   bhed::compile(sc, g_db, bl, cd), true);
        }
    }

    // --- Ein LEERES Skript befuellen -------------------------------------
    //
    // Der Fall, den alle bisherigen Bearbeitungsproben uebersehen haben: sie
    // arbeiteten samt und sonders mit einem schon gefuellten Skript. Bei
    // einem leeren gab es keinen Knoten, hinter den man einfuegen konnte -
    // also kam nie ein erster hinein, und der Doppelklick in der
    // Ereignisliste tat gar nichts.
    {
        bhed::Document doc{bhed::Script{}};
        expect("leeres Skript hat keine Knoten", doc.script().nodes.empty(), true);

        const std::vector<const bhed::Command*> ov = g_db.overloads("wait");
        expect("Befehl wait gefunden", !ov.empty(), true);
        if (!ov.empty()) {
            // Erster Knoten ueberhaupt, ohne Auswahl.
            expect("erster Knoten laesst sich einfuegen",
                   doc.insertAfter(bhed::Path{}, bhed::makeNode(*ov.front(), g_db)), true);
            expect("Knoten ist da", doc.script().nodes.size() == 1, true);

            // Zweiter ohne Auswahl haengt hinten an.
            (void)doc.insertAfter(bhed::Path{}, bhed::makeNode(*ov.front(), g_db));
            expect("zweiter haengt hinten an", doc.script().nodes.size() == 2, true);

            // Dritter hinter den ERSTEN.
            (void)doc.insertAfter(bhed::Path{0}, bhed::makeNode(*ov.front(), g_db));
            expect("dritter sitzt an Stelle 1", doc.script().nodes.size() == 3, true);

            // Rueckgaengig muss alles wieder wegnehmen.
            (void)doc.undo();
            (void)doc.undo();
            (void)doc.undo();
            expect("Rueckgaengig raeumt bis zum leeren Skript",
                   doc.script().nodes.empty(), true);
        }

        // Einfuegen aus der Zwischenablage in ein leeres Skript.
        bhed::Document d2{bhed::Script{}};
        if (!ov.empty()) {
            (void)d2.insertAfter(bhed::Path{}, bhed::makeNode(*ov.front(), g_db));
            (void)d2.copyAt(bhed::Path{0});
            (void)d2.removeAt(bhed::Path{0});
            expect("Skript wieder leer, Zwischenablage voll",
                   d2.script().nodes.empty() && d2.hasClipboard(), true);
            expect("Einfuegen in ein leeres Skript geht",
                   d2.pasteAfter(bhed::Path{}), true);
            expect("Knoten ist wieder da", d2.script().nodes.size() == 1, true);
        }
    }

    // --- Rueckgaengig ----------------------------------------------------
    {
        const std::vector<const bhed::Command*> ov = g_db.overloads("wait");
        bhed::Document doc{bhed::Script{}};
        expect("frisches Dokument ist nicht ungesichert", !doc.dirty(), true);
        expect("nichts zurueckzunehmen", doc.undoDepth() == 0, true);
        expect("Bezeichnung leer, wenn nichts ansteht",
               std::string(doc.undoLabel()).empty(), true);

        if (!ov.empty()) {
            (void)doc.insertAfter(bhed::Path{}, bhed::makeNode(*ov.front(), g_db));
            expect("nach dem Einfuegen ungesichert", doc.dirty(), true);
            expect("Schritt heisst insert",
                   std::string(doc.undoLabel()) == "insert", true);

            (void)doc.removeAt(bhed::Path{0});
            expect("Schritt heisst delete",
                   std::string(doc.undoLabel()) == "delete", true);

            // Der eigentliche Punkt: alles zurueckgenommen heisst NICHT
            // ungesichert. Ein Schalter, der bei jeder Aenderung angeht und
            // nie wieder ausgeht, fragt beim Schliessen unnoetig nach.
            (void)doc.undo();
            (void)doc.undo();
            expect("alles zurueckgenommen ist wieder gesichert", !doc.dirty(), true);
            expect("Wiederholen steht bereit", doc.redoDepth() == 2, true);
            expect("Wiederholen kennt seinen Namen",
                   std::string(doc.redoLabel()) == "insert", true);

            (void)doc.redo();
            expect("nach Wiederholen wieder ungesichert", doc.dirty(), true);

            // Speichern setzt den Bezugspunkt neu.
            doc.markSaved();
            expect("nach dem Speichern gesichert", !doc.dirty(), true);
            (void)doc.undo();
            expect("Zurueck hinter den Speicherpunkt ist ungesichert",
                   doc.dirty(), true);
        }
    }

    // --- Makros ausklappen ------------------------------------------------
    //
    // Der Vergleich ist hart: Ravens Datei alora_chat_1.icarus enthaelt
    // dieselbe Ausklappung, und unsere muss Zeile fuer Zeile dieselbe sein.
    {
        expect("Makros haben einen Rumpf", !g_db.macroBodies.empty(), true);
        const bhed::Macro* m = g_db.macro("walkOnly");
        expect("walkOnly gefunden", m != nullptr, true);
        if (m != nullptr) {
            // Ravens Marker sagt @5 - so viele Zeilen muss der Rumpf haben.
            expect("walkOnly hat 5 Zeilen, wie Ravens Marker sagt",
                   m->body.size() == 5, true);

            bhed::Script sc;
            for (const bhed::Node& n : bhed::makeMacroNodes(*m, g_db)) {
                sc.nodes.push_back(n);
            }
            const std::string text = bhed::writeScript(sc);
            const char* kExpected =
                "//Generated by BehavEd\r\n"
                "//$\"walkOnly\"@5\r\n"
                "set ( /*!*/ \"SET_BEHAVIOR_STATE\", /*!*/ \"BS_DEFAULT\" );\r\n"
                "set ( /*!*/ \"SET_WALKING\", /*!*/ \"true\" );\r\n"
                "set ( /*!*/ \"SET_RUNNING\", /*!*/ \"false\" );\r\n"
                "set ( /*!*/ \"SET_IGNOREALERTS\", /*!*/ \"true\" );\r\n"
                "set ( /*!*/ \"SET_LOOK_FOR_ENEMIES\", /*!*/ \"false\" );\r\n";
            expect("Ausklappung ist Zeile fuer Zeile wie bei Raven",
                   text == kExpected, true);

            // Wieder eingelesen muss der Marker seine Zeilenzahl behalten.
            bhed::Script back;
            std::vector<bhed::Diag> d;
            (void)bhed::readScript(text, back, d);
            expect("Marker ueberlebt den Rundlauf",
                   !back.nodes.empty() &&
                       back.nodes[0].kind == bhed::Node::Kind::Macro &&
                       back.nodes[0].count == 5, true);
            expect("gesperrte Felder ueberleben",
                   back.nodes.size() > 1 && !back.nodes[1].args.empty() &&
                       back.nodes[1].args[0].locked, true);
        }
    }

    // --- Export, wortgetreu nach dem Bildschirmfoto ----------------------
    {
        const char* kSrc =
            "//Generated by BehavEd\r\n"
            "rem ( \"comment\" );\r\n"
            "signal ( \"signalname\" );\r\n"
            "move ( < 0.000 0.000 0.000 >, < 0.000 0.000 0.000 >, 1000.000 );\r\n"
            "use ( \"DEFAULT\" );\r\n";
        bhed::Script sc;
        std::vector<bhed::Diag> d;
        (void)bhed::readScript(kSrc, sc, d);

        // So steht es im Bildschirmfoto des Originals, Zeile fuer Zeile.
        const char* kWanted =
            "( Original filename: \"\" )\r\n"
            "\r\n"
            "//Generated by BehavEd\r\n"
            "\r\n"
            "rem ( \"comment\" );\r\n"
            "signal ( \"signalname\" );\r\n"
            "move ( < 0 0 0 >, < 0 0 0 >, 1000 );\r\n"
            "use ( \"DEFAULT\" );\r\n";
        expect("Export ist wie im Bildschirmfoto",
               bhed::writeExport(sc, "", true) == kWanted, true);

        // Ohne %g bleiben die Nachkommastellen stehen.
        const std::string full = bhed::writeExport(sc, "taspir2/intro.icarus", false);
        expect("ohne den Schalter bleiben die Stellen",
               full.find("< 0.000 0.000 0.000 >") != std::string::npos, true);
        expect("Kopfzeile nennt den Dateinamen",
               full.rfind("( Original filename: \"taspir2/intro.icarus\" )", 0) == 0,
               true);
    }

    // --- Makro im Baum, nach dem Bildschirmfoto --------------------------
    //
    // Bis hierhin war die Faltung geraten. Die Bilder vom 11.08.2026 zeigen:
    // das Makro ist EIN Knoten mit dem []-Symbol, die erzeugten Befehle
    // stehen als EINGERUECKTE KINDER darunter, und die gesperrten Felder
    // tragen "(R)" samt Anfuehrungszeichen:
    //     standOnly
    //       set   ( (R)"SET_BEHAVIOR_STATE", (R)"BS_DEFAULT" )
    {
        const bhed::Macro* m = g_db.macro("standOnly");
        expect("standOnly gefunden", m != nullptr, true);
        if (m != nullptr) {
            bhed::Script sc;
            for (const bhed::Node& n : bhed::makeMacroNodes(*m, g_db)) {
                sc.nodes.push_back(n);
            }
            bhed::TreeOptions o;
            bhed::Expanded ex;
            ex.openAll();
            o.expanded = &ex;
            std::vector<bhed::Row> rows;
            bhed::buildTree(sc, g_db, o, rows);

            expect("Makro plus drei Kinder", rows.size() == 4, true);
            if (rows.size() == 4) {
                expect("erste Zeile ist das Makro",
                       rows[0].what == bhed::Row::What::Macro &&
                           rows[0].text == "standOnly" && rows[0].icon == "I_MACRO",
                       true);
                expect("Makro steht auf Ebene 0", rows[0].depth == 0, true);
                expect("Kinder stehen eine Ebene tiefer",
                       rows[1].depth == 1 && rows[3].depth == 1, true);
                expect("gesperrte Felder tragen (R) mit Anfuehrungszeichen",
                       rows[1].text ==
                           "set ( (R)\"SET_BEHAVIOR_STATE\", (R)\"BS_DEFAULT\" )",
                       true);
                // Der Weg eines Kindes muss auf seine echte Stelle zeigen,
                // sonst traefe "Loeschen" den falschen Knoten.
                expect("Weg des ersten Kindes zeigt auf Knoten 1",
                       rows[1].path.size() == 1 && rows[1].path[0] == 1, true);
                expect("Weg des dritten Kindes zeigt auf Knoten 3",
                       rows[3].path.size() == 1 && rows[3].path[0] == 3, true);
                // Und sie sind als Makrokinder MARKIERT.
                //
                // Genau daran hing shanks Verwirrung: im Baum sahen Makro
                // und Block gleich aus, also hat er dreimal versucht, einen
                // Befehl aus `standOnly` herauszuziehen. Ein Makro ist kein
                // Block - seine Zeilen stehen daneben, nicht darin, und
                // genau das sagen Marke und Hinweis jetzt.
                expect("Makrozeile ist als solche gekennzeichnet",
                       rows[0].what == bhed::Row::What::Macro, true);
                expect("Kinder tragen ausMakro", rows[1].ausMakro, true);
                expect("und der dritte auch", rows[3].ausMakro, true);
            }

            // Zugeklappt bleibt nur der Makroknoten.
            bhed::Expanded closed;
            o.expanded = &closed;
            std::vector<bhed::Row> few;
            bhed::buildTree(sc, g_db, o, few);
            expect("zugeklappt bleibt eine Zeile", few.size() == 1, true);
        }
    }

    // --- Ueberschriften in den Typmengen ---------------------------------
    //
    // Die Kopfdateien liefern sie ueber "//# #sep <Text>" - eine Anweisung,
    // die ausdruecklich fuer BehavEd dort steht. Ohne sie ist eine Liste mit
    // 1543 Animationsnamen eine Wand.
    {
        const bhed::TypeSet* setTypes = g_db.typeset("SET_TYPES");
        expect("SET_TYPES vorhanden", setTypes != nullptr, true);
        if (setTypes != nullptr) {
            int withSection = 0;
            bool parm = false;
            for (const bhed::TypeEntry& e : setTypes->entries) {
                if (!e.section.empty()) { ++withSection; }
                if (e.name == "SET_PARM1") {
                    parm = (e.section == "Parm strings");
                }
            }
            expect("jeder SET_TYPES-Eintrag hat eine Ueberschrift",
                   withSection == static_cast<int>(setTypes->entries.size()), true);
            expect("SET_PARM1 steht unter \"Parm strings\"", parm, true);
        }

        const bhed::TypeSet* anims = g_db.typeset("ANIM_NAMES");
        if (anims != nullptr && !anims->entries.empty()) {
            std::set<std::string> sections;
            for (const bhed::TypeEntry& e : anims->entries) {
                if (!e.section.empty()) { sections.insert(e.section); }
            }
            expect("die Animationsnamen sind in mehr als zehn Gruppen geteilt",
                   sections.size() > 10, true);
        }
    }

    // --- Wechsel der Auswahl aendert die Felder --------------------------
    //
    // Aus einem Fehlerbericht: wer die Liste von SET_PARM1 auf SET_HEALTH
    // stellt, bekam zwar ein Zahlenfeld, im Feld stand aber weiter
    // "DEFAULT". Die Regel dahinter steht in den Kopfdateien:
    {
        const bhed::TypeSet* ts = g_db.typeset("SET_TYPES");
        expect("SET_TYPES vorhanden fuer den Feldwechsel", ts != nullptr, true);
        if (ts != nullptr) {
            const bhed::TypeEntry* parm1 = ts->find("SET_PARM1");
            const bhed::TypeEntry* parm2 = ts->find("SET_PARM2");
            const bhed::TypeEntry* health = ts->find("SET_HEALTH");
            const bhed::TypeEntry* origin = ts->find("SET_ORIGIN");
            expect("die vier Eintraege gibt es",
                   parm1 != nullptr && parm2 != nullptr && health != nullptr &&
                       origin != nullptr, true);
            if (parm1 != nullptr && parm2 != nullptr && health != nullptr &&
                origin != nullptr) {
                expect("SET_PARM1 will einen Text",
                       parm1->params.size() == 1 &&
                           parm1->params[0].kind == bhed::Param::Kind::String, true);
                // Gleiche Art UND gleiche Vorgabe: ein getippter Wert soll
                // beim Wechsel erhalten bleiben.
                expect("SET_PARM1 und SET_PARM2 sind gleich gebaut",
                       parm2->params.size() == 1 &&
                           parm2->params[0].kind == parm1->params[0].kind &&
                           parm2->params[0].def == parm1->params[0].def, true);
                // Andere Art: hier MUSS der Wert neu gesetzt werden.
                expect("SET_HEALTH will eine Zahl mit Vorgabe 0",
                       health->params.size() == 1 &&
                           health->params[0].kind == bhed::Param::Kind::Int &&
                           health->params[0].def == "0", true);
                expect("SET_ORIGIN will einen Vektor",
                       origin->params.size() == 1 &&
                           origin->params[0].kind == bhed::Param::Kind::Vector, true);
                expect("und der unterscheidet sich von dem des Textfeldes",
                       origin->params[0].def != parm1->params[0].def, true);
            }
        }
    }

    // --- Mehrere Knoten auf einmal ---------------------------------------
    //
    // Der Fallstrick: loescht man von VORN, verschieben sich alle folgenden
    // Wege um eins, und der zweite Aufruf trifft den falschen Knoten. Es
    // wird etwas geloescht - nur nicht das Gewaehlte. Deshalb wird hier
    // nicht die Anzahl geprueft, sondern WELCHE Knoten uebrig bleiben.
    {
        const std::vector<const bhed::Command*> ov = g_db.overloads("print");
        if (!ov.empty()) {
            auto build = [&]() {
                bhed::Document d{bhed::Script{}};
                for (int i = 0; i < 5; ++i) {
                    bhed::Node n = bhed::makeNode(*ov.front(), g_db);
                    if (!n.args.empty()) {
                        n.args[0].text = std::string(1, static_cast<char>('A' + i));
                    }
                    (void)d.insertAfter(bhed::Path{}, n);
                }
                return d;
            };
            auto texts = [](const bhed::Document& d) {
                std::string out;
                for (const bhed::Node& n : d.script().nodes) {
                    out += n.args.empty() ? "?" : n.args[0].text;
                }
                return out;
            };

            bhed::Document d = build();
            expect("fuenf Knoten A bis E", texts(d) == "ABCDE", true);

            // B und D loeschen - in dieser Reihenfolge angegeben.
            expect("zwei Knoten auf einmal geloescht",
                   d.removeAll({bhed::Path{1}, bhed::Path{3}}), true);
            expect("es bleiben A, C und E - nicht irgendwelche zwei",
                   texts(d) == "ACE", true);

            // Ein einziger Rueckgaengig-Schritt muss beide zurueckholen.
            (void)d.undo();
            expect("Rueckgaengig holt beide auf einmal zurueck",
                   texts(d) == "ABCDE", true);

            // Auch andersherum angegeben muss dasselbe herauskommen.
            bhed::Document d2 = build();
            (void)d2.removeAll({bhed::Path{3}, bhed::Path{1}});
            expect("die Reihenfolge der Angabe ist egal", texts(d2) == "ACE", true);

            // Kopieren behaelt die Reihenfolge des Skripts.
            bhed::Document d3 = build();
            expect("drei Knoten kopiert",
                   d3.copyAll({bhed::Path{4}, bhed::Path{0}, bhed::Path{2}}), true);
            (void)d3.removeAll({bhed::Path{0}, bhed::Path{1}, bhed::Path{2},
                                bhed::Path{3}, bhed::Path{4}});
            expect("Skript ist leer", d3.script().nodes.empty(), true);
            (void)d3.pasteAfter(bhed::Path{});
            expect("eingefuegt in Skriptreihenfolge, nicht in Klickreihenfolge",
                   texts(d3) == "ACE", true);

            // Ausschneiden ist beides zusammen.
            bhed::Document d4 = build();
            expect("ausgeschnitten", d4.cutAll({bhed::Path{1}, bhed::Path{2}}), true);
            expect("und weg", texts(d4) == "ADE", true);
            (void)d4.pasteAfter(bhed::Path{0});
            expect("und wieder eingefuegt", texts(d4) == "ABCDE", true);
        }
    }

    // --- Mehrere Knoten gemeinsam verschieben ----------------------------
    //
    // Der Fallstrick spiegelt den beim Loeschen: HOCH muss von vorn
    // geschoben werden, RUNTER von hinten. Wer das vertauscht, bekommt eine
    // Auswahl, die sich beim Schieben selbst zerlegt - und das faellt erst
    // ab drei gewaehlten Knoten auf.
    {
        const std::vector<const bhed::Command*> ov = g_db.overloads("print");
        if (!ov.empty()) {
            auto build = [&](int n) {
                bhed::Document d{bhed::Script{}};
                for (int i = 0; i < n; ++i) {
                    bhed::Node x = bhed::makeNode(*ov.front(), g_db);
                    if (!x.args.empty()) {
                        x.args[0].text = std::string(1, static_cast<char>('A' + i));
                    }
                    (void)d.insertAfter(bhed::Path{}, x);
                }
                return d;
            };
            auto texts = [](const bhed::Document& x) {
                std::string out;
                for (const bhed::Node& n : x.script().nodes) {
                    out += n.args.empty() ? "?" : n.args[0].text;
                }
                return out;
            };

            // C, D, E nach oben: aus ABCDE wird ACDEB.
            bhed::Document d = build(5);
            std::vector<bhed::Path> sel{bhed::Path{2}, bhed::Path{3}, bhed::Path{4}};
            expect("drei Knoten nach oben", d.moveAll(sel, true), true);
            expect("aus ABCDE wird ACDEB", texts(d) == "ACDEB", true);
            expect("die Wege wandern mit",
                   sel.size() == 3 && sel[0][0] == 1 && sel[2][0] == 3, true);

            // Und wieder zurueck.
            expect("dieselben drei nach unten", d.moveAll(sel, false), true);
            expect("wieder ABCDE", texts(d) == "ABCDE", true);

            // Am Rand passiert nichts, statt die Auswahl zu zerlegen.
            bhed::Document e = build(4);
            std::vector<bhed::Path> top{bhed::Path{0}, bhed::Path{1}};
            expect("am oberen Rand passiert nichts", !e.moveAll(top, true), true);
            expect("und das Skript ist unveraendert", texts(e) == "ABCD", true);
            std::vector<bhed::Path> bottom{bhed::Path{2}, bhed::Path{3}};
            expect("am unteren Rand ebenso", !e.moveAll(bottom, false), true);

            // Ein einziger Rueckgaengig-Schritt fuer die ganze Bewegung.
            bhed::Document f = build(5);
            std::vector<bhed::Path> two{bhed::Path{0}, bhed::Path{1}};
            (void)f.moveAll(two, false);
            expect("zwei nach unten geschoben", texts(f) == "CABDE", true);
            (void)f.undo();
            expect("ein Rueckgaengig holt beide zurueck", texts(f) == "ABCDE", true);

            // Mehrere auf einmal ziehen: die Reihenfolge untereinander
            // bleibt erhalten.
            bhed::Document g = build(5);
            expect("A und B hinter D gezogen",
                   g.moveAllTo({bhed::Path{0}, bhed::Path{1}}, bhed::Path{3}), true);
            expect("aus ABCDE wird CDABE", texts(g) == "CDABE", true);
        }
    }

    // --- Auf einen Block gezogen heisst HINEIN ---------------------------
    //
    // Aus einem Fehlerbericht: Befehle liessen sich nicht auf affect, task,
    // if oder else ziehen. moveTo setzt DANEBEN - fuer einen Block braucht
    // es moveInto.
    {
        const std::vector<const bhed::Command*> af = g_db.overloads("affect");
        const std::vector<const bhed::Command*> pr = g_db.overloads("print");
        if (!af.empty() && !pr.empty()) {
            bhed::Document d{bhed::Script{}};
            (void)d.insertAfter(bhed::Path{}, bhed::makeNode(*af.front(), g_db));
            (void)d.insertAfter(bhed::Path{0}, bhed::makeNode(*pr.front(), g_db));
            expect("zwei Knoten auf oberster Ebene",
                   d.script().nodes.size() == 2, true);

            // Den print auf den affect ziehen.
            expect("in den Block gezogen",
                   d.moveInto(bhed::Path{1}, bhed::Path{0}), true);
            expect("jetzt nur noch ein Knoten oben",
                   d.script().nodes.size() == 1, true);
            expect("und er hat ein Kind",
                   d.script().nodes[0].children.size() == 1, true);

            // Ein Block in sich selbst muss abgelehnt werden.
            expect("ein Block laesst sich nicht in sich selbst ziehen",
                   !d.moveInto(bhed::Path{0}, bhed::Path{0}), true);
            // Auch nicht in ein eigenes Kind.
            expect("und nicht in sein eigenes Kind",
                   !d.moveInto(bhed::Path{0}, bhed::Path{0, 0}), true);

            // Auf etwas, das kein Block ist, geht es nicht.
            expect("auf einen einfachen Befehl geht es nicht",
                   !d.moveInto(bhed::Path{0, 0}, bhed::Path{0, 0}), true);

            // Ein Rueckgaengig holt alles zurueck.
            (void)d.undo();
            expect("Rueckgaengig stellt beide Knoten her",
                   d.script().nodes.size() == 2, true);
        }
    }

    // --- Ziehen im Baum ---------------------------------------------------
    {
        const std::vector<const bhed::Command*> ov = g_db.overloads("print");
        const std::vector<const bhed::Command*> af = g_db.overloads("affect");
        if (!ov.empty() && !af.empty()) {
            bhed::Document d{bhed::Script{}};
            for (int i = 0; i < 3; ++i) {
                bhed::Node n = bhed::makeNode(*ov.front(), g_db);
                if (!n.args.empty()) {
                    n.args[0].text = std::string(1, static_cast<char>('A' + i));
                }
                (void)d.insertAfter(bhed::Path{}, n);
            }
            auto texts = [](const bhed::Document& x) {
                std::string out;
                for (const bhed::Node& n : x.script().nodes) {
                    out += n.args.empty() ? "?" : n.args[0].text;
                }
                return out;
            };
            expect("drei Knoten fuer das Ziehen", texts(d) == "ABC", true);

            // A hinter C ziehen.
            expect("A hinter C gezogen", d.moveTo(bhed::Path{0}, bhed::Path{2}), true);
            expect("Reihenfolge ist jetzt BCA", texts(d) == "BCA", true);

            // C hinter B ziehen - da steht es schon. Das ist ein NULLZUG.
            //
            // Diese Probe erwartete bis rc522 `true`: der Zug meldete
            // Erfolg, legte einen Rueckgaengig-Schritt an und bewegte
            // nichts. Wer danach Strg+Z drueckt, bekommt seine vorige
            // ECHTE Aenderung nicht zurueck, sondern das Nichts davor.
            //
            // Die Folgeprobe war ausserdem hohl: `!texts(d).empty()` ist
            // immer wahr, sie haette jede Reihenfolge durchgelassen. Sie
            // prueft jetzt, was sie behauptet.
            expect("Nullzug meldet keinen Erfolg",
                   !d.moveTo(bhed::Path{1}, bhed::Path{0}), true);
            expect("Reihenfolge bleibt BCA", texts(d) == "BCA", true);

            // Auf sich selbst ziehen tut nichts.
            const std::string before = texts(d);
            expect("auf sich selbst gezogen passiert nichts",
                   !d.moveTo(bhed::Path{1}, bhed::Path{1}), true);
            expect("und das Skript ist unveraendert", texts(d) == before, true);

            // Ein Block in sich selbst muss abgelehnt werden - sonst haenge
            // der Baum an sich selbst und jeder Durchlauf liefe endlos.
            bhed::Document b{bhed::Script{}};
            bhed::Node blk = bhed::makeNode(*af.front(), g_db);
            blk.hasBlock = true;
            blk.children.push_back(bhed::makeNode(*ov.front(), g_db));
            (void)b.insertAfter(bhed::Path{}, blk);
            expect("ein Block laesst sich nicht in sich selbst ziehen",
                   !b.moveTo(bhed::Path{0}, bhed::Path{0, 0}), true);
            expect("und der Block ist noch heil",
                   b.script().nodes.size() == 1 &&
                       b.script().nodes[0].children.size() == 1, true);
        }
    }

    // --- Eine .ent-Datei ersetzt die Entities ----------------------------
    //
    // Movie Duels arbeitet so: die .bsp bleibt unveraendert, die Entities
    // kommen aus einer eigenen Datei daneben. Der Leser ist derselbe wie
    // fuer das Entity-Lump - das ist kein Zufall, sondern dasselbe Format.
    {
        const char* text =
            "{\n\"classname\" \"waypoint_navgoal\"\n"
            "\"targetname\" \"anakin1_nav1\"\n\"origin\" \"1278 -2254 1060\"\n}\n"
            "{\n\"classname\" \"target_scriptrunner\"\n"
            "\"targetname\" \"intro\"\n\"usescript\" \"md_twj/intro_jedi\"\n}\n";
        std::vector<bhed::MapEntity> ents;
        bhed::parseEntities(text, ents);
        expect("zwei Entities aus der .ent", ents.size() == 2, true);
        if (ents.size() == 2) {
            expect("der Wegpunkt traegt seinen Namen",
                   ents[0].targetname == "anakin1_nav1", true);
            expect("und seinen Ort", ents[0].origin == "1278 -2254 1060", true);
            expect("der Skriptstarter nennt sein Skript",
                   ents[1].find("usescript") != nullptr &&
                       *ents[1].find("usescript") == "md_twj/intro_jedi", true);
        }
    }

    // --- Vorgabewerte ----------------------------------------------------
    //
    // Aus einem Fehlerbericht: "affect" bekam beim Neu-Auswerten den Wert
    // "AFFECT_TYPE" - das ist der TYPNAME aus der .bhc, kein Wert. Und ein
    // Zahlenfeld mit dem Platzhalter "DEFAULT" ergab das Wort statt einer
    // Null.
    {
        auto defOf = [&](const char* cmd, std::size_t index) {
            const std::vector<const bhed::Command*> ov = g_db.overloads(cmd);
            if (ov.empty() || ov.front()->params.size() <= index) {
                return std::string("<fehlt>");
            }
            return bhed::defaultValueFor(ov.front()->params[index], g_db);
        };

        expect("affect nimmt FLUSH, nicht \"AFFECT_TYPE\"",
               defOf("affect", 1) == "FLUSH", true);
        expect("set nimmt SET_PARM1, nicht \"SET_TYPES\"",
               defOf("set", 0) == "SET_PARM1", true);
        expect("camera nimmt ENABLE", defOf("camera", 0) == "ENABLE", true);

        // Ein Zahlenfeld mit echtem Vorgabewert behaelt ihn.
        expect("wait behaelt seine 1000.0", defOf("wait", 0) == "1000.0", true);

        // Und eines mit Platzhalter bekommt eine Null. Wir bauen den Fall
        // selbst, weil er in der .bhc nicht auftaucht - aber genau danach
        // wurde gefragt.
        {
            bhed::Param p;
            p.kind = bhed::Param::Kind::Float;
            p.def = "DEFAULT";
            expect("ein Zahlenfeld mit Platzhalter ergibt 0.000",
                   bhed::defaultValueFor(p, g_db) == "0.000", true);
            p.kind = bhed::Param::Kind::Int;
            expect("ein Ganzzahlfeld ergibt 0",
                   bhed::defaultValueFor(p, g_db) == "0", true);
            p.kind = bhed::Param::Kind::Vector;
            expect("ein Vektorfeld ergibt einen Nullvektor",
                   bhed::defaultValueFor(p, g_db) == "0.000 0.000 0.000", true);
            // Bei Text bleibt DEFAULT stehen: das ist Ravens Platzhalter
            // fuer einen Entity-Namen und dort brauchbar.
            p.kind = bhed::Param::Kind::String;
            expect("ein Textfeld behaelt DEFAULT",
                   bhed::defaultValueFor(p, g_db) == "DEFAULT", true);
        }

        // makeNode muss dasselbe liefern - beide Wege gehen jetzt ueber
        // dieselbe Funktion.
        const std::vector<const bhed::Command*> af = g_db.overloads("affect");
        if (!af.empty()) {
            const bhed::Node n = bhed::makeNode(*af.front(), g_db);
            expect("ein neuer affect-Knoten traegt FLUSH",
                   n.args.size() > 1 && n.args[1].text == "FLUSH", true);
            expect("und er hat einen Block", n.hasBlock, true);
        }
    }

    // --- Befehle in einen Block einfuegen --------------------------------
    //
    // Der schwerste Punkt aus dem Bericht: affect, if und task liessen sich
    // nicht befuellen. insertAfter setzt IMMER daneben - fuer einen Block
    // braucht es insertInto.
    {
        const std::vector<const bhed::Command*> af = g_db.overloads("affect");
        const std::vector<const bhed::Command*> pr = g_db.overloads("print");
        if (!af.empty() && !pr.empty()) {
            bhed::Document d{bhed::Script{}};
            (void)d.insertAfter(bhed::Path{}, bhed::makeNode(*af.front(), g_db));
            expect("ein affect-Block steht im Skript",
                   d.script().nodes.size() == 1 && d.script().nodes[0].hasBlock, true);
            expect("und er ist leer", d.script().nodes[0].children.empty(), true);

            // Hinein, an den Anfang.
            expect("ein Befehl laesst sich hineinlegen",
                   d.insertInto(bhed::Path{0}, 0, bhed::makeNode(*pr.front(), g_db)),
                   true);
            expect("jetzt hat der Block ein Kind",
                   d.script().nodes[0].children.size() == 1, true);
            expect("und das Skript hat immer noch nur einen Knoten oben",
                   d.script().nodes.size() == 1, true);

            // Ein zweiter davor.
            (void)d.insertInto(bhed::Path{0}, 0, bhed::makeNode(*pr.front(), g_db));
            expect("zwei Kinder", d.script().nodes[0].children.size() == 2, true);

            // Und das Ganze muss sich schreiben und wieder lesen lassen.
            const std::string text = bhed::writeScript(d.script());
            bhed::Script back;
            std::vector<bhed::Diag> dg;
            expect("der Block laesst sich schreiben und wieder lesen",
                   bhed::readScript(text, back, dg), true);
            expect("mit seinen zwei Kindern",
                   back.nodes.size() == 1 && back.nodes[0].children.size() == 2, true);
        }
    }

    // --- Einfuegen NEBEN einem Kind bleibt im Block ----------------------
    //
    // Der haeufige Fall: man klickt eine Zeile IM Block an und fuegt etwas
    // ein. Das muss im Block bleiben - insertAfter arbeitet auf den
    // Geschwistern, also stimmt es; die Probe haelt es fest.
    {
        const std::vector<const bhed::Command*> af = g_db.overloads("affect");
        const std::vector<const bhed::Command*> pr = g_db.overloads("print");
        if (!af.empty() && !pr.empty()) {
            bhed::Document d{bhed::Script{}};
            (void)d.insertAfter(bhed::Path{}, bhed::makeNode(*af.front(), g_db));
            (void)d.insertInto(bhed::Path{0}, 0, bhed::makeNode(*pr.front(), g_db));
            (void)d.insertAfter(bhed::Path{0, 0}, bhed::makeNode(*pr.front(), g_db));
            expect("neben einem Kind eingefuegt bleibt es im Block",
                   d.script().nodes.size() == 1 &&
                       d.script().nodes[0].children.size() == 2, true);

            // Und ein Block laesst sich auch mitten hinein befuellen.
            (void)d.insertInto(bhed::Path{0}, 1, bhed::makeNode(*pr.front(), g_db));
            expect("drei Kinder", d.script().nodes[0].children.size() == 3, true);
        }
    }

    std::printf("\n%s (%d Fehlschlaege)\n", g_fail ? "FEHLGESCHLAGEN" : "alle Gegenproben bestanden", g_fail);
    return g_fail ? 1 : 0;
}
