// edittest.cpp - Bearbeitung, Rueckgaengig und der REM-Rundlauf.
//
// Der schaerfste Test hier ist der letzte: Ravens eigene Dateien enthalten
// 40 Skripte mit //(BHVDREM)-Bloecken. Wenn unser uncomment() sie oeffnet und
// unser commentOut() sie wieder schliesst, muss die Datei Byte fuer Byte
// dieselbe sein. Das prueft die Formatregel gegen echte Daten statt gegen
// meine Lesart.
#include "bhed/edit.h"
#include "bhed/script.h"

#include <cstddef>
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <random>
#include <sstream>
#include <string>
#include <vector>

namespace fs = std::filesystem;

static int g_fail = 0;

static void expect(const char* what, bool ok) {
    std::printf("  %s  %s\n", ok ? "ok  " : "FEHL", what);
    if (!ok) {
        ++g_fail;
    }
}

static std::string slurp(const fs::path& p) {
    std::ifstream f(p, std::ios::binary);
    std::ostringstream ss;
    ss << f.rdbuf();
    return ss.str();
}

static bhed::Script parse(const std::string& t) {
    bhed::Script s;
    std::vector<bhed::Diag> d;
    (void)bhed::readScript(t, s, d);
    return s;
}

#define HDR "//Generated by BehavEd\r\n"

// Alle Wege zu Knoten einer Art, von hinten nach vorn (Indizes bleiben gueltig).
static void collectRem(const std::vector<bhed::Node>& ns, bhed::Path prefix,
                       std::vector<bhed::Path>& out) {
    for (std::size_t i = ns.size(); i-- > 0;) {
        bhed::Path p = prefix;
        p.push_back(i);
        if (!ns[i].children.empty()) {
            collectRem(ns[i].children, p, out);
        }
        // Nur den ANFANG eines auskommentierten Blocks merken.
        const bool isRem = ns[i].kind == bhed::Node::Kind::LineComment &&
                           ns[i].raw.find("//(BHVDREM)") != std::string::npos;
        // Leerzeilen innerhalb des Blocks tragen kein //(BHVDREM) - beim
        // Suchen des Blockanfangs muessen sie uebersprungen werden.
        std::size_t k = i;
        while (k > 0 && ns[k - 1].kind == bhed::Node::Kind::Blank) {
            --k;
        }
        const bool prevRem = k > 0 && ns[k - 1].kind == bhed::Node::Kind::LineComment &&
                             ns[k - 1].raw.find("//(BHVDREM)") != std::string::npos;
        // Seit rc568 JEDE REM-Zeile: uncomment nimmt die Anweisung zurueck,
        // zu der die Zeile gehoert - auch mitten in einer Folge.
        (void)prevRem;
        if (isRem) {
            out.push_back(p);
        }
    }
}

int main(int argc, char** argv) {
    if (argc < 4) {
        std::fprintf(stderr, "Aufruf: edittest <skriptdir> <bhc> <headerdir> [nachtrag]\n");
        return 2;
    }
    bhed::CommandDb db;
    std::vector<bhed::LoadDiag> ld;
    if (!bhed::loadCommandDb(argv[2], argv[3], db, ld)) {
        return 2;
    }
    if (argc > 4 && !bhed::loadCommandDb(argv[4], argv[3], db, ld)) {
        return 2;
    }

    // --- Grundoperationen ------------------------------------------------
    {
        const std::string src = HDR
            "wait ( 1000.000 );\r\n"
            "affect ( \"kyle\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\tprint ( \"hallo\" );\r\n}\r\n";
        bhed::Document doc{parse(src)};

        expect("Weg loest auf", bhed::nodeAt(doc.script(), {1}) != nullptr);
        expect("Weg ins Kind loest auf", bhed::nodeAt(doc.script(), {1, 0}) != nullptr);
        expect("zu tiefer Weg liefert nullptr", bhed::nodeAt(doc.script(), {1, 0, 5}) == nullptr);

        expect("Clone verdoppelt", doc.cloneAt({0}) &&
               doc.script().nodes.size() == 3);
        expect("Rueckgaengig stellt her", doc.undo() &&
               bhed::writeScript(doc.script()) == src);
        expect("Wiederherstellen", doc.redo() && doc.script().nodes.size() == 3);
        expect("nochmal rueckgaengig", doc.undo() &&
               bhed::writeScript(doc.script()) == src);

        expect("Loeschen", doc.removeAt({0}) && doc.script().nodes.size() == 1);
        expect("Loeschen rueckgaengig", doc.undo() &&
               bhed::writeScript(doc.script()) == src);

        expect("Kopieren + Einfuegen", doc.copyAt({0}) && doc.pasteAfter({0}) &&
               doc.script().nodes.size() == 3);
        (void)doc.undo();

        expect("Ausschneiden", doc.cutAt({0}) && doc.script().nodes.size() == 1 &&
               doc.hasClipboard());
        (void)doc.undo();

        expect("in den Block einfuegen",
               doc.insertInto({1}, 0, bhed::makeNode(*db.overloads("flush").front(), db)) &&
               bhed::nodeAt(doc.script(), {1, 0})->name == "flush");
        (void)doc.undo();

        expect("nach oben am Anfang geht nicht", !doc.moveUp({0}));
        expect("nach unten am Ende geht nicht", !doc.moveDown({1}));
        expect("nach unten tauscht", doc.moveDown({0}) &&
               doc.script().nodes[1].name == "wait");
        expect("und wieder zurueck", doc.moveUp({1}) &&
               bhed::writeScript(doc.script()) == src);

        expect("ungueltiger Weg aendert nichts",
               !doc.removeAt({99}) && bhed::writeScript(doc.script()) == src);
    }

    // --- neue Knoten aus der Befehlsliste ---------------------------------
    {
        const bhed::Command* set = nullptr;
        for (const bhed::Command* c : db.overloads("set")) {
            if (!c->params.empty() && c->params[0].kind == bhed::Param::Kind::TypeSet) {
                set = c;
            }
        }
        expect("set-Signatur mit Auswahlliste gefunden", set != nullptr);
        if (set != nullptr) {
            const bhed::Node n = bhed::makeNode(*set, db);
            expect("neuer set-Knoten hat 2 Felder", n.args.size() == 2);
            expect("erstes Feld ist der erste Eintrag der Menge",
                   n.args[0].text == "SET_PARM1" && n.args[0].typeset == "SET_TYPES");
        }
        const bhed::Command* cam = db.overloads("camera").front();
        const bhed::Node c = bhed::makeNode(*cam, db);
        expect("camera-Feld blank, weil CAMERA_COMMANDS eine %i-Menge ist",
               !c.args.empty() && c.args[0].kind == bhed::Arg::Kind::Ident);
    }

    // --- Suchen (Dialog 140) ----------------------------------------------
    {
        const std::string src = HDR
            "task ( \"speech1\" )\r\n{\r\n\tsound ( /*@CHANNELS*/ CHAN_VOICE, \"a/b.mp3\" );\r\n}\r\n"
            "dowait ( \"speech1\" );\r\n";
        const bhed::Script s = parse(src);
        // Wie das Original: "containing" prueft jedes Argument einzeln,
        // "called" nur den Befehlsnamen (ABGLEICH-VERHALTEN.md, Suche).
        bhed::FindOptions o;
        expect("Whole-string ist vorgewaehlt", o.wholeString);
        o.contains = "speech1";
        expect("Suche findet beide Vorkommen", bhed::findAll(s, o).size() == 2);
        o.contains = "b.mp3";
        expect("ganzes Argument findet den Teiltext nicht", bhed::findAll(s, o).empty());
        o.wholeString = false;
        expect("Teiltextsuche findet den Klang", bhed::findAll(s, o).size() == 1);
        o.contains.clear();
        o.named = "dowait";
        expect("'called' findet den Befehl", bhed::findAll(s, o).size() == 1);
        o.named = "speech1";
        expect("'called' findet kein Argument", bhed::findAll(s, o).empty());
        o.named = "dowai";
        expect("'called' ist immer exakt", bhed::findAll(s, o).empty());
    }

    // --- Rueckgaengig ueber den gesamten Bestand ---------------------------
    {
        std::mt19937 rng(7);
        int files = 0;
        int mismatch = 0;
        for (const auto& e : fs::recursive_directory_iterator(argv[1])) {
            if (!e.is_regular_file() || e.path().extension() != ".icarus") {
                continue;
            }
            const std::string src = slurp(e.path());
            bhed::Document doc{parse(src)};
            const std::string base = bhed::writeScript(doc.script());
            ++files;
            for (int k = 0; k < 6; ++k) {
                const bhed::Path p{rng() % 12};
                switch (rng() % 6) {
                    case 0: (void)doc.cloneAt(p); break;
                    case 1: (void)doc.removeAt(p); break;
                    case 2: (void)doc.moveUp(p); break;
                    case 3: (void)doc.moveDown(p); break;
                    case 4: (void)doc.commentOut(p); break;
                    case 5: (void)doc.insertRem(p); break;
                }
            }
            while (doc.undo()) {
            }
            if (bhed::writeScript(doc.script()) != base) {
                ++mismatch;
            }
        }
        std::printf("  -- %d Dateien, je 6 Zufallsaenderungen, dann alles zurueck\n", files);
        expect("Rueckgaengig stellt ueberall den Ausgangszustand her", mismatch == 0);
    }

    // --- Un-REM nimmt nur die eigene Anweisung zurueck (rc568) ---------------
    {
        const std::string src = HDR
            "//(BHVDREM)  wait ( 100.000 );\r\n"
            "//(BHVDREM)  if ( $get( FLOAT, \"x\")$, $>$, $1$ )\r\n"
            "//(BHVDREM)  {\r\n"
            "\t//(BHVDREM)  wait ( 200.000 );\r\n"
            "//(BHVDREM)  }\r\n"
            "//(BHVDREM)  wait ( 300.000 );\r\n";
        bhed::Document doc{parse(src)};
        std::size_t produced = 0;
        // Zeile 1 ist der Kopf des if-Blocks.
        expect("Un-REM auf dem Kopf: geht", doc.uncomment({1}, &produced));
        const auto& ns = doc.script().nodes;
        expect("... genau eine Anweisung zurueck", produced == 1);
        expect("... der Nachbar davor bleibt REM",
               ns.size() >= 3 && ns[0].kind == bhed::Node::Kind::LineComment);
        expect("... das if ist ein Block mit seinem wait",
               ns.size() >= 3 && ns[1].name == "if" && ns[1].children.size() == 1);
        expect("... der Nachbar dahinter bleibt REM",
               ns.size() >= 3 && ns[2].kind == bhed::Node::Kind::LineComment);
        bhed::Document doc2{parse(src)};
        expect("Un-REM auf einer Zeile IM Block holt den ganzen Block",
               doc2.uncomment({3}, &produced) && produced == 1 &&
                   doc2.script().nodes[1].name == "if");
    }

    // --- REM-Rundlauf gegen Ravens eigene Bloecke --------------------------
    {
        int files = 0;
        int blocks = 0;
        int mismatch = 0;
        std::vector<std::string> bad;
        for (const auto& e : fs::recursive_directory_iterator(argv[1])) {
            if (!e.is_regular_file() || e.path().extension() != ".icarus") {
                continue;
            }
            const std::string src = slurp(e.path());
            if (src.find("//(BHVDREM)") == std::string::npos) {
                continue;
            }
            ++files;
            bhed::Document doc{parse(src)};
            const std::string base = bhed::writeScript(doc.script());

            std::vector<bhed::Path> rems;
            collectRem(doc.script().nodes, {}, rems);
            for (const bhed::Path& p : rems) {
                std::size_t produced = 0;
                bhed::Path anfang;
                if (!doc.uncomment(p, &produced, &anfang)) {
                    continue;
                }
                ++blocks;
                // Was daraus entstand, wieder zumachen - von hinten nach vorn,
                // damit die Indizes der frueheren Knoten gueltig bleiben. Es
                // steht ab `anfang`: wer mitten im Block waehlt, holt die
                // Anweisung zurueck, die weiter oben beginnt.
                for (std::size_t k = produced; k-- > 0;) {
                    bhed::Path q = anfang;
                    q.back() = anfang.back() + k;
                    (void)doc.commentOut(q);
                }
            }
            const std::string nachher = bhed::writeScript(doc.script());
            if (nachher != base) {
                ++mismatch;
                if (bad.size() < 3) {
                    // Die erste abweichende Zeile gleich mit - sonst muss man
                    // raten, was sich geaendert hat.
                    std::istringstream a(base);
                    std::istringstream b(nachher);
                    std::string la;
                    std::string lb;
                    int zeile = 1;
                    while (std::getline(a, la) && std::getline(b, lb) && la == lb) {
                        ++zeile;
                    }
                    bad.push_back(e.path().filename().string() + ", Zeile " +
                                  std::to_string(zeile) + ": [" + la + "] -> [" + lb + "]");
                }
            }
        }
        std::printf("  -- %d Dateien mit //(BHVDREM), %d Bloecke geoeffnet und wieder geschlossen\n",
                    files, blocks);
        for (const auto& b : bad) {
            std::printf("     abweichend: %s\n", b.c_str());
        }
        expect("REM-Rundlauf ist bytegleich", mismatch == 0);
    }

    // --- Wo steht die Dauer eines Befehls? ------------------------------
    //
    // Daran haengt seit rc197 das Ziehen der rechten Kante in der
    // Zeitleiste. Faellt die Antwort falsch aus, aendert ein Zug den
    // FALSCHEN Wert - etwa den Ort einer Kamerafahrt statt ihrer Dauer.
    // Deshalb steht die Regel im Kern und wird hier festgehalten.
    {
        auto befehl = [](const char* name,
                         std::vector<bhed::Arg> args) {
            bhed::Node n;
            n.kind = bhed::Node::Kind::Command;
            n.name = name;
            n.args = std::move(args);
            return n;
        };
        auto zahl = [](const char* t) {
            bhed::Arg a;
            a.kind = bhed::Arg::Kind::Number;
            a.text = t;
            return a;
        };
        auto wort = [](const char* t) {
            bhed::Arg a;
            a.kind = bhed::Arg::Kind::Ident;
            a.text = t;
            return a;
        };
        auto text = [](const char* t) {
            bhed::Arg a;
            a.kind = bhed::Arg::Kind::String;
            a.text = t;
            return a;
        };
        auto vek = [](const char* t) {
            bhed::Arg a;
            a.kind = bhed::Arg::Kind::Vector;
            a.text = t;
            return a;
        };

        expect("wait mit Zahl: Argument 0",
               bhed::durationArgIndex(befehl("wait", {zahl("5000.000")})) == 0);
        // Der Fall, an dem eine Regel "wait heisst Dauer" scheitern wuerde.
        expect("wait auf ein SIGNAL hat keine Dauer",
               bhed::durationArgIndex(befehl("wait", {text("jsf_land")})) == -1);
        expect("camera MOVE: das letzte Argument",
               bhed::durationArgIndex(befehl(
                   "camera", {wort("MOVE"), vek("1 2 3"), zahl("5000")})) == 2);
        expect("camera PAN hat vier Argumente - trotzdem das letzte",
               bhed::durationArgIndex(befehl(
                   "camera", {wort("PAN"), vek("0 0 0"), vek("0 0 0"),
                              zahl("6000")})) == 3);
        expect("camera ENABLE hat keine Dauer",
               bhed::durationArgIndex(befehl("camera", {wort("ENABLE")})) == -1);
        expect("camera DISABLE ebenso",
               bhed::durationArgIndex(befehl("camera", {wort("DISABLE")})) == -1);
        expect("ein sound hat keine",
               bhed::durationArgIndex(befehl(
                   "sound", {wort("CHAN_VOICE"), text("a.wav")})) == -1);
        expect("und ein Befehl ohne Argumente auch nicht",
               bhed::durationArgIndex(befehl("flush", {})) == -1);
    }

    std::printf("\n%s (%d Fehlschlaege)\n",
                g_fail != 0 ? "FEHLGESCHLAGEN" : "alle Bearbeitungsproben bestanden", g_fail);
    return g_fail != 0 ? 1 : 0;
}
