// scenetest.cpp - wo die Figuren stehen und was sie tun
//
// Die Bahnen entstehen aus Skript UND Karte: der Startort kommt vom
// NPC_spawner, das Ziel eines SET_NAVGOAL vom waypoint_navgoal. Fehlt eines
// von beiden, darf nichts geraten werden.
#include "bhed/scene.h"
#include "bhed/gla.h"

#include <cmath>
#include <cstddef>
#include <cstdio>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

namespace {
int fails = 0;
void expect(const char* what, bool ok) {
    std::printf("  %s  %s\n", ok ? "ok  " : "FEHL", what);
    if (!ok) { ++fails; }
}
bool near(float a, float b, float eps = 1.0F) { return std::fabs(a - b) < eps; }

bhed::MapData mapWith(const char* text) {
    bhed::MapData m;
    bhed::parseEntities(text, m.entities);
    return m;
}

bhed::Scene sceneOf(const std::string& body, const bhed::MapData& map) {
    bhed::Script s;
    std::vector<bhed::Diag> d;
    (void)bhed::readScript("//Generated by BehavEd\r\n" + body, s, d);
    return bhed::buildScene(s, map);
}
}  // namespace

int main(int argc, char** argv) {
    const bhed::MapData map = mapWith(
        "{\n\"classname\" \"NPC_spawner\"\n\"npc_targetname\" \"held\"\n"
        "\"NPC_type\" \"jedi\"\n\"origin\" \"0 0 100\"\n\"angle\" \"90\"\n}\n"
        "{\n\"classname\" \"waypoint_navgoal\"\n\"targetname\" \"ziel1\"\n"
        "\"origin\" \"900 0 100\"\n}\n");

    // --- Startort aus dem Spawner ----------------------------------------
    {
        const bhed::Scene s = sceneOf(
            "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_WALKING\", /*@BOOL_TYPES*/ \"true\" );\r\n}\r\n",
            map);
        expect("die Figur wurde gefunden", s.actors.size() == 1);
        if (!s.actors.empty()) {
            const bhed::Actor& a = s.actors.front();
            expect("Startort aus dem Spawner",
                   a.haveStart && near(a.start[0], 0.0F) && near(a.start[2], 100.0F));
            expect("Blickrichtung aus dem Spawner", near(a.startAngles[1], 90.0F));
            expect("NPC_type uebernommen", a.npcType == "jedi");
        }
    }

    // --- Gehen mit der Geschwindigkeit der Engine -------------------------
    //
    // walkSpeed = 90 Einheiten je Sekunde (NPC_stats.cpp). 900 Einheiten
    // sind also genau 10 Sekunden - beim Laufen mit 300 nur 3.
    {
        const bhed::Scene walk = sceneOf(
            "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_WALKING\", /*@BOOL_TYPES*/ \"true\" );\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_NAVGOAL\", \"ziel1\" );\r\n}\r\n", map);
        expect("ein Gehschritt entstand",
               !walk.actors.empty() && walk.actors[0].steps.size() == 1);
        if (!walk.actors.empty() && !walk.actors[0].steps.empty()) {
            const bhed::ActorStep& st = walk.actors[0].steps.front();
            // Seit 28.09. nach dem Steuermodell der Engine (gehDauerMs),
            // nicht mehr 900 / 90 = 10 s.
            expect("900 Einheiten im Gehen: Dauer nach gehDauerMs",
                   near(static_cast<float>(st.endMs),
                        static_cast<float>(bhed::gehDauerMs(900.0, 90.0, 1.0, 0.0)), 1.0F) &&
                       st.endMs > 10000.0);
            expect("und es ist die Gehanimation", st.text == "BOTH_WALK1");
        }

        const bhed::Scene run = sceneOf(
            "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_WALKING\", /*@BOOL_TYPES*/ \"false\" );\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_NAVGOAL\", \"ziel1\" );\r\n}\r\n", map);
        if (!run.actors.empty() && !run.actors[0].steps.empty()) {
            expect("im Laufen deutlich schneller (runSpeed 300)",
                   near(static_cast<float>(run.actors[0].steps.front().endMs),
                        static_cast<float>(bhed::gehDauerMs(900.0, 300.0, 1.0, 0.0)), 1.0F));
            expect("und es ist die Laufanimation",
                   run.actors[0].steps.front().text == "BOTH_RUN1");
        }
    }

    // --- Die Stellung zwischendrin ----------------------------------------
    {
        const bhed::Scene s = sceneOf(
            "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_WALKING\", /*@BOOL_TYPES*/ \"true\" );\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_NAVGOAL\", \"ziel1\" );\r\n}\r\n", map);
        const bhed::Actor& a = s.actors.front();
        expect("am Anfang am Startort", near(a.at(0.0).pos[0], 0.0F));
        const double dauer = bhed::gehDauerMs(900.0, 90.0, 1.0, 0.0);
        expect("zur halben Dauer auf halbem Weg", near(a.at(dauer / 2.0).pos[0], 450.0F, 5.0F));
        expect("am Ende am Ziel", near(a.at(dauer).pos[0], 900.0F, 1.0F));
        expect("danach bleibt sie dort", near(a.at(20000.0).pos[0], 900.0F, 1.0F));
        expect("unterwegs laeuft die Gehanimation",
               a.at(5000.0).animation == "BOTH_WALK1");
        // Am Ziel steht sie - dort waere BOTH_WALK1 falsch.
        expect("am Ziel steht sie", a.at(20000.0).animation == "BOTH_STAND1");
        expect("und schaut in Laufrichtung", near(a.at(5000.0).angles[1], 0.0F, 1.0F));
    }

    // --- Fehlende Angaben werden NICHT geraten ----------------------------
    {
        // Ein Wegpunkt, den es in der Karte nicht gibt.
        const bhed::Scene s = sceneOf(
            "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_NAVGOAL\", \"gibtesnicht\" );\r\n}\r\n", map);
        expect("ein unbekannter Wegpunkt erzeugt keinen Schritt",
               s.actors.empty() || s.actors[0].steps.empty());

        // Eine Figur ohne Spawner.
        const bhed::Scene t = sceneOf(
            "affect ( \"fremder\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_WALKING\", /*@BOOL_TYPES*/ \"true\" );\r\n}\r\n",
            map);
        expect("eine Figur ohne Spawner hat keinen Startort",
               !t.actors.empty() && !t.actors[0].haveStart);
    }

    // --- Unsichtbar und wieder sichtbar -----------------------------------
    {
        const bhed::Scene s = sceneOf(
            "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_INVISIBLE\", /*@BOOL_TYPES*/ \"true\" );\r\n"
            "\twait ( 2000.000 );\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_INVISIBLE\", /*@BOOL_TYPES*/ \"false\" );\r\n}\r\n",
            map);
        const bhed::Actor& a = s.actors.front();
        expect("erst unsichtbar", !a.at(1000.0).visible);
        expect("dann wieder sichtbar", a.at(3000.0).visible);
    }

    // --- Haltezeit: einfrieren statt wiederholen --------------------------
    //
    // set ( SET_ANIM_HOLDTIME_BOTH, -1 ) haelt die Animation unbegrenzt.
    // In Ravens 1510 Skripten steht das 510 von 721 Mal - 71 %. Ohne diese
    // Unterscheidung laufen Gesten und Posen in Endlosschleife.
    {
        const bhed::Scene s = sceneOf(
            "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_ANIM_BOTH\", \"BOTH_STAND2\" );\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_ANIM_HOLDTIME_BOTH\", -1 );\r\n"
            "\twait ( 4000.000 );\r\n}\r\n", map);
        const bhed::Actor& a = s.actors.front();
        expect("die Animation ist gesetzt", a.at(1000.0).animation == "BOTH_STAND2");
        expect("und sie haelt", a.at(1000.0).holdAnim);
        expect("auch nach vier Sekunden noch", a.at(5000.0).holdAnim);

        // Eine positive Zahl haelt nur so lange.
        const bhed::Scene t = sceneOf(
            "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_ANIM_BOTH\", \"BOTH_STAND2\" );\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_ANIM_HOLDTIME_BOTH\", 2000 );\r\n}\r\n",
            map);
        const bhed::Actor& b = t.actors.front();
        expect("2000 ms halten waehrend der Zeit", b.at(1000.0).holdAnim);
        expect("danach nicht mehr", !b.at(3000.0).holdAnim);

        // Und der Einsatzzeitpunkt wird gemerkt.
        const bhed::Scene u = sceneOf(
            "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\twait ( 3000.000 );\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_ANIM_BOTH\", \"BOTH_STAND2\" );\r\n}\r\n",
            map);
        expect("die Animation beginnt bei 3 s, nicht bei 0",
               near(static_cast<float>(u.actors.front().at(5000.0).animStartMs),
                    3000.0F, 1.0F));
    }

    // --- SET_RUNNING ------------------------------------------------------
    {
        const bhed::Scene s = sceneOf(
            "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_WALKING\", /*@BOOL_TYPES*/ \"true\" );\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_RUNNING\", /*@BOOL_TYPES*/ \"true\" );\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_NAVGOAL\", \"ziel1\" );\r\n}\r\n", map);
        expect("SET_RUNNING hebt SET_WALKING auf",
               !s.actors.empty() && !s.actors[0].steps.empty() &&
                   near(static_cast<float>(s.actors[0].steps.front().endMs),
                        static_cast<float>(bhed::gehDauerMs(900.0, 300.0, 1.0, 0.0)), 1.0F));
    }

    // --- Blickziel --------------------------------------------------------
    {
        // ziel1 liegt bei 900 0 100, die Figur bei 0 0 100 - sie muss also
        // nach +X schauen, also yaw 0.
        const bhed::Scene s = sceneOf(
            "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_LOOK_TARGET\", \"ziel1\" );\r\n}\r\n",
            map);
        const bhed::ActorState st = s.actors.front().at(1000.0);
        expect("ein Blickziel ist gesetzt", st.hasLookTarget);
        // Bis rc248 stand hier: "und die Figur dreht sich dorthin". Das war
        // falsch, und die Probe hat den Fehler festgehalten statt ihn zu
        // fangen.
        //
        // SET_LOOK_TARGET dreht in der Engine nur den KOPF
        // (cg_players.cpp:3319 f., CG_UpdateAngleClamp gegen
        // headYawClampMin/Max). Der Koerper bleibt, wo er war - hier also
        // auf den 90 Grad aus dem Spawner, nicht auf den 0 Grad zum Ziel.
        //
        // Die Drehung des Kopfes selbst prueft glatest.cpp am Knochen; hier
        // gehoert nur hin, dass der Koerper sich NICHT mitdreht.
        expect("aber der Koerper dreht sich NICHT mit",
               near(st.angles[1], 90.0F, 1.0F));

        // NULL loescht es wieder.
        const bhed::Scene t = sceneOf(
            "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_LOOK_TARGET\", \"ziel1\" );\r\n"
            "\twait ( 1000.000 );\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_LOOK_TARGET\", \"NULL\" );\r\n}\r\n",
            map);
        expect("NULL loescht das Blickziel",
               !t.actors.front().at(2000.0).hasLookTarget);
    }

    // --- Watchtarget: die Figur dreht sich ---------------------------------
    //
    // Anders als das Blickziel dreht SET_WATCHTARGET den ganzen Koerper
    // (NPC_behavior.cpp:256 ff.), und zwar NICHT auf der Stelle, sondern mit
    // 60 + yawSpeed*3 Grad je Sekunde (NPC_utils.cpp:288 ff.).
    //
    // Die Figur steht bei 0 0 100 und schaut nach yaw 90 (aus dem Spawner).
    // ziel1 liegt bei 900 0 100, also genau in +x - Zielwinkel 0. Zu drehen
    // sind damit 90 Grad, bei 330 Grad je Sekunde rund 273 ms.
    {
        const bhed::Scene s = sceneOf(
            "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_WATCHTARGET\", \"ziel1\" );\r\n}\r\n",
            map);
        expect("ein Watchtarget ist gesetzt",
               s.actors.front().at(0.0).hasWatchTarget);
        // Im Moment des Setzens steht sie noch, wo sie stand.
        expect("zu Beginn steht sie noch auf ihrem Startwinkel",
               near(s.actors.front().at(0.0).angles[1], 90.0F, 0.5F));
        // Nach der halben Drehzeit die halbe Strecke. DAS ist die Probe,
        // die einen Sprung von einer Drehung unterscheidet: wer die Winkel
        // sofort setzt, liefert hier schon 0 statt 45.
        expect("nach halber Zeit die halbe Drehung",
               near(s.actors.front().at(136.0).angles[1], 45.0F, 3.0F));
        expect("danach ist sie angekommen",
               near(s.actors.front().at(1000.0).angles[1], 0.0F, 0.5F));
        // Und sie dreht NICHT weiter - der Weg endet am Ziel.
        expect("und dreht nicht darueber hinaus",
               near(s.actors.front().at(5000.0).angles[1], 0.0F, 0.5F));

        // NULL loescht es; danach gilt wieder der Startwinkel.
        const bhed::Scene t = sceneOf(
            "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_WATCHTARGET\", \"ziel1\" );\r\n"
            "\twait ( 1000.000 );\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_WATCHTARGET\", \"NULL\" );\r\n}\r\n",
            map);
        expect("NULL loescht das Watchtarget",
               !t.actors.front().at(2000.0).hasWatchTarget);
    }

    // --- Watchtarget gewinnt gegen die Laufrichtung ------------------------
    //
    // NPC_behavior.cpp:257 sagt es woertlich: "this will override any angles
    // set by NPC_MoveToGoal". Eine Figur, die zu einem Wegpunkt geht und
    // dabei jemanden ansieht, dreht den KOERPER zum Angesehenen.
    //
    // Diese Probe haelt genau den Unterschied zum Blickziel fest: dort steht
    // ein !st.moving davor, hier darf keines stehen.
    {
        const bhed::MapData m2 = mapWith(
            "{\n\"classname\" \"NPC_spawner\"\n\"npc_targetname\" \"held\"\n"
            "\"NPC_type\" \"jedi\"\n\"origin\" \"0 0 100\"\n\"angle\" \"0\"\n}\n"
            "{\n\"classname\" \"waypoint_navgoal\"\n\"targetname\" \"ziel1\"\n"
            "\"origin\" \"900 0 100\"\n}\n"
            "{\n\"classname\" \"info_null\"\n\"targetname\" \"zuschauer\"\n"
            "\"origin\" \"0 900 100\"\n}\n");
        const bhed::Scene s = sceneOf(
            "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_WATCHTARGET\", \"zuschauer\" );\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_WALKING\", /*@BOOL_TYPES*/ \"true\" );\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_NAVGOAL\", \"ziel1\" );\r\n}\r\n",
            m2);
        // Laufrichtung waere +x (yaw 0), der Zuschauer liegt in +y.
        //
        // NICHT gegen eine feste Zahl pruefen: die Figur laeuft waehrend
        // des Zusehens weiter, also wandert der Winkel zum Zuschauer mit
        // ihr. Geprueft wird die REGEL - sie schaut aus ihrer jeweiligen
        // Stellung zum Zuschauer -, und dazu, dass das nicht die
        // Laufrichtung ist. Eine feste Zahl waere hier eine Probe, die das
        // Ergebnis abschreibt statt es zu pruefen.
        const bhed::ActorState st = s.actors.front().at(1500.0);
        const float soll =
            std::atan2(st.watchAt[1] - st.pos[1], st.watchAt[0] - st.pos[0]) *
            180.0F / 3.14159265F;
        expect("sie schaut aus ihrer jeweiligen Stellung zum Zuschauer",
               near(st.angles[1], soll, 1.0F));
        expect("beim Gehen gewinnt das Watchtarget gegen die Laufrichtung",
               st.moving && std::fabs(st.angles[1]) > 45.0F);
    }

    // --- SET_WALKSPEED / SET_RUNSPEED --------------------------------------
    //
    // Q3_SetWalkSpeed (Q3_Interface.cpp:3370) hat eine Eigenheit, die man
    // nachlesen muss:
    //
    //     if(int_data == 0) { ...walkSpeed = ...speed = 1; }
    //     ...walkSpeed = ...speed = int_data;
    //
    // Es fehlt das else - die Null bleibt eine Null. Und PM_CmdScale
    // (bg_pmove.cpp:784) rechnet scale = ps->speed * max / (127*total),
    // also bewegt sich bei 0 nichts.
    //
    // In md_ga_jedi sind 25 der 34 SET_WALKSPEED genau 0.000. Diese Probe
    // ist deshalb keine Formsache: sie haelt fest, dass eine festgenagelte
    // Figur STEHENBLEIBT statt loszumarschieren.
    {
        // ziel1 liegt 900 Einheiten entfernt. Bei 45 statt der Vorgabe 90
        // dauert der Weg 20 s statt 10.
        const bhed::Scene s = sceneOf(
            "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_WALKING\", /*@BOOL_TYPES*/ \"true\" );\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_WALKSPEED\", 45.000 );\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_NAVGOAL\", \"ziel1\" );\r\n}\r\n",
            map);
        expect("walkSpeed 45 statt 90: nach gehDauerMs deutlich laenger",
               !s.actors.front().steps.empty() &&
                   near(static_cast<float>(s.actors.front().steps.back().endMs),
                        static_cast<float>(bhed::gehDauerMs(900.0, 45.0, 1.0, 0.0)), 1.0F) &&
                   s.actors.front().steps.back().endMs > 1.9 * bhed::gehDauerMs(900.0, 90.0, 1.0, 0.0) - 400.0);

        const bhed::Scene null = sceneOf(
            "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_WALKING\", /*@BOOL_TYPES*/ \"true\" );\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_WALKSPEED\", 0.000 );\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_NAVGOAL\", \"ziel1\" );\r\n}\r\n",
            map);
        const bhed::ActorState fest = null.actors.front().at(60000.0);
        expect("Geschwindigkeit null nagelt die Figur fest",
               near(fest.pos[0], 0.0F, 1.0F));
        expect("und sie laeuft dabei auch nicht auf der Stelle",
               !fest.moving);

        // Laufen benutzt runSpeed, nicht walkSpeed - beide getrennt
        // gesetzt, damit ein vertauschtes Feld auffliegt.
        const bhed::Scene r = sceneOf(
            "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_WALKSPEED\", 45.000 );\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_RUNSPEED\", 450.000 );\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_RUNNING\", /*@BOOL_TYPES*/ \"true\" );\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_NAVGOAL\", \"ziel1\" );\r\n}\r\n",
            map);
        expect("beim Laufen gilt runSpeed, nicht walkSpeed",
               !r.actors.front().steps.empty() &&
                   near(static_cast<float>(r.actors.front().steps.back().endMs),
                        static_cast<float>(bhed::gehDauerMs(900.0, 450.0, 1.0, 0.0)), 1.0F));
    }

    // --- SET_YAWSPEED ------------------------------------------------------
    //
    // Grad je Sekunde = 60 + yawSpeed*3. Mit yawSpeed 150 sind das 510
    // statt der 330 aus der Vorgabe - die 90 Grad Drehung dauert damit
    // 176 statt 273 ms.
    {
        const bhed::Scene s = sceneOf(
            "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_YAWSPEED\", 150.000 );\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_WATCHTARGET\", \"ziel1\" );\r\n}\r\n",
            map);
        expect("SET_YAWSPEED setzt die Drehrate",
               near(s.actors.front().at(0.0).turnDegPerSec, 510.0F, 0.5F));
        // Bei 176 ms waere sie mit der Vorgabe erst bei 58 Grad statt 0.
        expect("und damit ist die Drehung frueher fertig",
               near(s.actors.front().at(180.0).angles[1], 0.0F, 2.0F));
    }

    // --- Hocken -----------------------------------------------------------
    {
        const bhed::Scene s = sceneOf(
            "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_CROUCHED\", /*@BOOL_TYPES*/ \"true\" );\r\n}\r\n",
            map);
        const bhed::ActorState st = s.actors.front().at(1000.0);
        expect("die Figur hockt", st.crouched);
        expect("und hat eine Hockanimation", st.animation.find("CROUCH") !=
                                                 std::string::npos);
    }

    // --- NPC-Beschreibungen ------------------------------------------------
    {
        const char* npc =
            "// Kommentar\n"
            "md_ani_tcwa\n"
            "{\n"
            "\tplayerModel\tanakin_tcw\n"
            "\trank\t\tlt\n"
            "\thealth\t\t100\n"
            "}\n"
            "md_templeguard\n"
            "{\n"
            "\tplayerModel\ttempleguard\n"
            "}\n";
        bhed::NpcMap m;
        bhed::parseNpcFile(npc, m);
        expect("zwei NPC-Typen gelesen", m.size() == 2);
        expect("md_ani_tcwa nutzt anakin_tcw", m["md_ani_tcwa"].playerModel == "anakin_tcw");
        expect("md_templeguard nutzt templeguard",
               m["md_templeguard"].playerModel == "templeguard");
        // Kaputte Dateien duerfen nicht stuerzen.
        for (const char* bad : {"", "{", "}", "name\n{\n", "{{{{", "name\n{\nx\n}\n"}) {
            bhed::NpcMap m2;
            bhed::parseNpcFile(bad, m2);
        }
        expect("kaputte .npc ueberstanden", true);
    }

    // --- Gegen echte Daten -------------------------------------------------
    if (argc > 2) {
        std::ifstream sf(argv[1], std::ios::binary);
        std::ostringstream ss;
        ss << sf.rdbuf();
        std::ifstream ef(argv[2], std::ios::binary);
        std::ostringstream es;
        es << ef.rdbuf();
        if (!ss.str().empty() && !es.str().empty()) {
            bhed::Script script;
            std::vector<bhed::Diag> d;
            (void)bhed::readScript(ss.str(), script, d);
            bhed::MapData real;
            bhed::parseEntities(es.str(), real.entities);
            const bhed::Scene s = bhed::buildScene(script, real);
            std::printf("     %zu Figuren, Bahn bis %.1f s\n", s.actors.size(),
                        s.durationMs / 1000.0);
            expect("Figuren gefunden", !s.actors.empty());

            int withStart = 0;
            int withType = 0;
            for (const bhed::Actor& a : s.actors) {
                if (a.haveStart) { ++withStart; }
                if (!a.npcType.empty()) { ++withType; }
            }
            std::printf("     %d von %zu mit Startort, %d mit NPC_type\n",
                        withStart, s.actors.size(), withType);
            expect("jede Figur hat einen Startort",
                   withStart == static_cast<int>(s.actors.size()));

            // Kein Sprung ins Nichts ueber die ganze Bahn.
            bool sane = true;
            for (const bhed::Actor& a : s.actors) {
                for (double ms = 0.0; ms <= s.durationMs; ms += 500.0) {
                    const bhed::ActorState st = a.at(ms);
                    for (int k = 0; k < 3; ++k) {
                        if (!std::isfinite(st.pos[k]) ||
                            !std::isfinite(st.angles[k])) {
                            sane = false;
                        }
                    }
                }
            }
            expect("die Stellung ist zu jeder Zeit brauchbar", sane);
        }
    }

    // --- Der Uebergang zwischen zwei Animationen -------------------------
    //
    // Belegt im Quelltext, nicht angenommen:
    //
    //   bg_public.h:176            SETANIM_BLEND_DEFAULT 100
    //   Q3_Interface.cpp:1955/1985 NPC_SetAnim(...) OHNE blendTime
    //   tr_ghoul2.cpp:1543         Pose = l*neu + (1-l)*alt
    //   ghoul2_shared.h:97         die alte Seite ist EINE Frame, eingefroren
    {
        std::printf("\n== Uebergang zwischen Animationen ==\n");
        const bhed::Scene s = sceneOf(
            "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_ANIM_BOTH\", \"BOTH_STAND2\" );\r\n"
            "\twait ( 2000.000 );\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_ANIM_BOTH\", \"BOTH_GESTURE1\" );\r\n"
            "}\r\n",
            map);
        expect("die Figur wurde gefunden", s.actors.size() == 1);
        if (!s.actors.empty()) {
            const bhed::Actor& a = s.actors.front();

            // Vor dem zweiten Befehl: kein Uebergang.
            const bhed::ActorState vor = a.at(1900.0);
            expect("vor dem Wechsel laeuft kein Uebergang",
                   bhed::blendFraction(vor, 1900.0) >= 1.0F);

            // Genau bei HALBER Blendzeit liegt die Stellung in der Mitte.
            // Das ist die Probe, um die es geht.
            const bhed::ActorState mitte = a.at(2050.0);
            expect("bei halber Blendzeit liegt die Stellung in der Mitte",
                   near(bhed::blendFraction(mitte, 2050.0), 0.5F, 0.001F));
            expect("die neue Animation steht an",
                   mitte.animation == "BOTH_GESTURE1");
            expect("die alte Animation ist vermerkt",
                   mitte.prevAnimation == "BOTH_STAND2");

            // Die Blendzeit ist die der Engine, nicht geraten.
            expect("die Blendzeit betraegt 100 ms",
                   near(static_cast<float>(mitte.blendMs), 100.0F, 0.001F));

            // DIE ENTSCHEIDENDE PROBE.
            //
            // Die alte Seite ist ein STANDBILD. Wer den Uebergang als zwei
            // laufende Animationen baut, faellt genau hier durch: dort
            // liefe prevAnimSinceMs weiter, und die beiden Werte waeren
            // verschieden.
            const bhed::ActorState frueh = a.at(2001.0);
            const bhed::ActorState spaet = a.at(2099.0);
            expect("die alte Seite bewegt sich waehrend des Uebergangs NICHT",
                   near(static_cast<float>(frueh.prevAnimSinceMs),
                        static_cast<float>(spaet.prevAnimSinceMs), 0.001F));
            expect("die alte Seite steht dort, wo sie beim Wechsel war",
                   near(static_cast<float>(frueh.prevAnimSinceMs), 2000.0F, 0.001F));

            // Nach 100 ms ist die alte Seite weg.
            const bhed::ActorState nach = a.at(2100.0);
            expect("nach der Blendzeit zaehlt allein die neue Animation",
                   bhed::blendFraction(nach, 2100.0) >= 1.0F);
            const bhed::ActorState weit = a.at(5000.0);
            expect("lange danach ebenfalls",
                   bhed::blendFraction(weit, 5000.0) >= 1.0F);

            // Der Anfang: unmittelbar beim Wechsel zaehlt die ALTE Seite.
            expect("beim Wechsel selbst zaehlt die alte Stellung ganz",
                   near(bhed::blendFraction(a.at(2000.0), 2000.0), 0.0F, 0.001F));
        }
    }

    // Auch DIESELBE Animation neu gesetzt blendet.
    //
    // Skripte setzen SETANIM_FLAG_RESTART, und PM_SetAnimFinal laesst
    // BONE_ANIM_BLEND damit stehen:
    //     (torsOnAnimNow && !animRestart) ? (animFlags & ~BONE_ANIM_BLEND)
    //                                     : animFlags
    {
        const bhed::Scene s = sceneOf(
            "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_ANIM_BOTH\", \"BOTH_GESTURE1\" );\r\n"
            "\twait ( 1000.000 );\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_ANIM_BOTH\", \"BOTH_GESTURE1\" );\r\n"
            "}\r\n",
            map);
        if (!s.actors.empty()) {
            const bhed::ActorState st = s.actors.front().at(1050.0);
            expect("dieselbe Animation neu gesetzt blendet ebenfalls",
                   near(bhed::blendFraction(st, 1050.0), 0.5F, 0.001F));
        }
    }

    // Ohne Uebergang darf nichts gemischt werden - sonst mischte jede
    // Figur dauerhaft gegen eine Stellung, die es nie gab.
    {
        const bhed::Scene s = sceneOf(
            "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_WALKING\", /*@BOOL_TYPES*/ \"true\" );\r\n"
            "}\r\n",
            map);
        if (!s.actors.empty()) {
            const bhed::ActorState st = s.actors.front().at(500.0);
            expect("ohne Animationsbefehl laeuft kein Uebergang",
                   st.prevAnimation.empty() &&
                       bhed::blendFraction(st, 500.0) >= 1.0F);
        }
    }

    // --- remove und kill ---------------------------------------------------
    //
    // `remove` kam in 40 Skripten 56 mal vor und wurde bisher UEBERGANGEN -
    // die Figur blieb sichtbar stehen, obwohl das Skript sie fortgenommen
    // hat.
    //
    // CQuake3GameInterface::Remove (Q3_Interface.cpp:9712) sucht ueber
    // targetname und ruft Q3_RemoveEnt fuer JEDE Entity dieses Namens. Die
    // Entity ist danach frei, nicht bloss unsichtbar.
    {
        // Das Ziel steht in einem FREMDEN affect-Block. Genau so steht es in
        // den Missionen: 38 der 56 Entfernungen treffen jemand anderen als
        // die Figur des umgebenden Blocks.
        const bhed::MapData m2 = mapWith(
            "{\n\"classname\" \"NPC_spawner\"\n\"npc_targetname\" \"held\"\n"
            "\"NPC_type\" \"jedi\"\n\"origin\" \"0 0 100\"\n\"angle\" \"0\"\n}\n"
            "{\n\"classname\" \"NPC_spawner\"\n\"npc_targetname\" \"opfer\"\n"
            "\"NPC_type\" \"jedi\"\n\"origin\" \"500 0 100\"\n\"angle\" \"0\"\n}\n");
        const bhed::Scene s = sceneOf(
            "affect ( \"opfer\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_WALKING\", /*@BOOL_TYPES*/ \"true\" );\r\n}\r\n"
            "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\twait ( 1000.000 );\r\n"
            "\tremove ( \"opfer\" );\r\n}\r\n",
            m2);
        const bhed::Actor* opfer = nullptr;
        for (const bhed::Actor& a : s.actors) {
            if (a.name == "opfer") { opfer = &a; }
        }
        expect("das Opfer gibt es als Figur", opfer != nullptr);
        if (opfer != nullptr) {
            expect("vor der Entfernung ist es sichtbar",
                   opfer->at(500.0).visible);
            expect("danach nicht mehr", !opfer->at(1500.0).visible);
            expect("und es gilt als fort, nicht nur als unsichtbar",
                   opfer->at(1500.0).removed);
        }

        // DAS ist der Unterschied zu SET_INVISIBLE: ein spaeteres
        // "false" holt eine entfernte Figur NICHT zurueck. Ohne diese
        // Zusicherung koennte man remove faelschlich als Hide bauen.
        const bhed::Scene z = sceneOf(
            "affect ( \"opfer\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\twait ( 2000.000 );\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_INVISIBLE\", /*@BOOL_TYPES*/ \"false\" );\r\n}\r\n"
            "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\twait ( 1000.000 );\r\n"
            "\tremove ( \"opfer\" );\r\n}\r\n",
            m2);
        for (const bhed::Actor& a : z.actors) {
            if (a.name == "opfer") {
                expect("SET_INVISIBLE false holt eine entfernte Figur nicht "
                       "zurueck",
                       !a.at(3000.0).visible);
            }
        }

        // "self" trifft die Figur des eigenen Blocks.
        const bhed::Scene self = sceneOf(
            "affect ( \"opfer\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\twait ( 1000.000 );\r\n"
            "\tremove ( \"self\" );\r\n}\r\n",
            m2);
        for (const bhed::Actor& a : self.actors) {
            if (a.name == "opfer") {
                expect("remove(\"self\") trifft die eigene Figur",
                       a.at(500.0).visible && !a.at(1500.0).visible);
            }
        }

        // kill geht denselben Weg.
        //
        // Das Opfer braucht hier einen EIGENEN affect-Block. Ohne ihn gibt
        // es die Figur nicht (wer nur entfernt wird, bekommt keine Bahn) -
        // die Schleife darunter faende nichts, und die Probe waere still
        // gruen, ohne irgendetwas zu pruefen. Beim ersten Anlauf war sie
        // genau das.
        bool killGeprueft = false;
        const bhed::Scene k = sceneOf(
            "affect ( \"opfer\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_WALKING\", /*@BOOL_TYPES*/ \"true\" );\r\n}\r\n"
            "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\twait ( 1000.000 );\r\n"
            "\tkill ( \"opfer\" );\r\n}\r\n",
            m2);
        for (const bhed::Actor& a : k.actors) {
            if (a.name == "opfer") {
                killGeprueft = true;
                // kill ist NICHT remove: die Figur stirbt (BOTH_DEATH1,
                // eingefroren) und bleibt sichtbar liegen - player_die,
                // g_combat.cpp:4490. Frueher verschwand sie hier.
                const bhed::ActorState danach = a.at(1500.0);
                expect("kill: die Figur stirbt und bleibt liegen",
                       a.at(500.0).visible && danach.visible && danach.animation == "BOTH_DEATH1");
            }
        }
        expect("und die kill-Probe ist ueberhaupt gelaufen", killGeprueft);
    }

    // --- Ein Ziel darf eine andere FIGUR sein ------------------------------
    //
    // Gemeldet: "die Kopfbewegungen gehen immer noch nicht."
    //
    // findEntity() sah nur auf targetname. Ein NPC_spawner traegt seinen
    // Namen aber unter NPC_targetname - und damit fand ein SET_LOOK_TARGET
    // oder SET_WATCHTARGET NIE eine andere Figur. Der Schritt kam als
    // "Ziel loeschen" an, und die Figur schaute geradeaus.
    //
    // Im Spiel geht das anders (NPC_spawn.cpp:1688 f.): die erzeugte Figur
    // bekommt den NPC_targetname ihres Spawners als eigenen targetname.
    //
    // Gemessen an md_ga_jedi: vorher wurden 6 Blickziele und 7 Watchtargets
    // aufgeloest und KEINE Figur drehte den Kopf sichtbar; danach 15 und 18,
    // und fuenf Figuren drehen ihn um mehr als 5 Grad.
    {
        const bhed::MapData m2 = mapWith(
            "{\n\"classname\" \"NPC_spawner\"\n\"npc_targetname\" \"held\"\n"
            "\"NPC_type\" \"jedi\"\n\"origin\" \"0 0 100\"\n\"angle\" \"0\"\n}\n"
            "{\n\"classname\" \"NPC_spawner\"\n\"npc_targetname\" \"gegenueber\"\n"
            "\"NPC_type\" \"jedi\"\n\"origin\" \"0 900 100\"\n\"angle\" \"180\"\n}\n");
        const bhed::Scene s = sceneOf(
            "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_LOOK_TARGET\", \"gegenueber\" );\r\n}\r\n",
            m2);
        const bhed::ActorState st = s.actors.front().at(1000.0);
        expect("eine andere Figur als Blickziel wird gefunden",
               st.hasLookTarget);
        // UND der Ort stimmt. Ohne diese Zusicherung bestuende die Probe
        // auch, wenn das Ziel bei 0/0/0 landete - und genau so sah der
        // Fehler aus.
        expect("und ihr Ort ist der des Spawners",
               near(st.lookAt[1], 900.0F, 1.0F));

        // Dasselbe fuer das Watchtarget - derselbe Weg, dieselbe Falle.
        const bhed::Scene w = sceneOf(
            "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_WATCHTARGET\", \"gegenueber\" );\r\n}\r\n",
            m2);
        const bhed::ActorState wst = w.actors.front().at(2000.0);
        expect("eine andere Figur als Watchtarget wird gefunden",
               wst.hasWatchTarget && near(wst.watchAt[1], 900.0F, 1.0F));
        expect("und der Koerper hat sich dorthin gedreht",
               near(wst.angles[1], 90.0F, 1.0F));
    }

    // --- SET_ANIM_UPPER laesst die Beine in Ruhe ---------------------------
    //
    // Gemeldet: "ich denke manche Charaktere benutzen die falschen
    // Animationen."
    //
    // SETANIM_LEGS setzt die Animation auf "model_root" (das ganze
    // Skelett), SETANIM_TORSO auf "lower_lumbar" (bg_panimate.cpp:4848,
    // 4864). Ein UPPER fasst die Beinspur also nicht an - vorher landeten
    // alle drei Befehle im selben Feld und der letzte gewann fuer alles.
    {
        const bhed::Scene s = sceneOf(
            "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_ANIM_BOTH\", \"BOTH_STAND1\" );\r\n"
            "\twait ( 1000.000 );\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_ANIM_UPPER\", \"TORSO_WEAPONIDLE2\" );\r\n}\r\n",
            map);
        const bhed::ActorState st = s.actors.front().at(2000.0);
        expect("die Beine behalten ihre Animation",
               st.animation == "BOTH_STAND1");
        expect("und der Oberkoerper hat eine eigene",
               st.torsoAnimation == "TORSO_WEAPONIDLE2");

        // Ein SET_ANIM_BOTH danach belegt BEIDE Knochen neu - danach gibt
        // es keine getrennte Oberkoerperspur mehr.
        const bhed::Scene b = sceneOf(
            "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_ANIM_UPPER\", \"TORSO_WEAPONIDLE2\" );\r\n"
            "\twait ( 1000.000 );\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_ANIM_BOTH\", \"BOTH_STAND2\" );\r\n}\r\n",
            map);
        const bhed::ActorState bst = b.actors.front().at(2000.0);
        // NICHT BOTH_RUN1 nehmen: eine stehende Figur bekommt am Ende von
        // at() BOTH_STAND1 zugewiesen (die Naeherung fuer "laeuft nicht
        // mehr"), und die Probe pruefte dann diese Naeherung statt der
        // Aufteilung. Beim ersten Anlauf ist sie genau daran gescheitert.
        expect("SET_ANIM_BOTH hebt die getrennte Oberkoerperspur auf",
               bst.animation == "BOTH_STAND2" && bst.torsoAnimation.empty());

        // Ein UPPER darf den Uebergang der BEINE nicht ausloesen - sonst
        // ruckelte bei jeder Geste der ganze Unterkoerper.
        const bhed::Scene u = sceneOf(
            "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_ANIM_BOTH\", \"BOTH_STAND1\" );\r\n"
            "\twait ( 1000.000 );\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_ANIM_UPPER\", \"TORSO_WEAPONIDLE2\" );\r\n}\r\n",
            map);
        expect("ein UPPER loest keinen Uebergang der Beine aus",
               near(bhed::blendFraction(u.actors.front().at(1050.0), 1050.0),
                    1.0F, 0.001F));

        // SET_ANIM_HOLDTIME_UPPER haelt den OBERkoerper, nicht die Beine -
        // Q3_SetAnimHoldTime bekommt dafuer den Parameter `lower`
        // (Q3_Interface.cpp:2060).
        const bhed::Scene h = sceneOf(
            "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_ANIM_BOTH\", \"BOTH_STAND1\" );\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_ANIM_UPPER\", \"BOTH_SILENCEGESTURE1\" );\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_ANIM_HOLDTIME_UPPER\", -1.000 );\r\n}\r\n",
            map);
        const bhed::ActorState hst = h.actors.front().at(3000.0);
        expect("HOLDTIME_UPPER haelt den Oberkoerper",
               hst.torsoHold && !hst.holdAnim);
    }

    // --- Ghoul2 dreht den Oberkoerper NICHT mit ----------------------------
    //
    // Gemeldet: "wenn ich Kopf und Oberkoerper aus mache, sieht es richtig
    // aus. Nicht immer dreht sich der Oberkoerper mit dem Kopf mit."
    //
    // Beides trifft zu. rc254 hatte die Oberkoerperdrehung aus
    // `CG_PlayerAngles` (cg_players.cpp:3030) abgeschrieben - dem alten Weg
    // fuer MD3-Modelle. Ghoul2-Modelle laufen ueber `CG_G2PlayerAngles`
    // (ebenda:2479), und der endet mit `return` (ebenda:2881), BEVOR jener
    // Block je erreicht wird. In Movie Duels ist jedes Modell ein .glm.
    //
    // Was bleibt, ist `CG_G2ClientNeckAngles` mit drei Anteilen
    // (ebenda:2301 ff.) und den Anschlaegen aus ebenda:2878.
    {
        constexpr float kBrust = 0.10F;
        constexpr float kHals = 0.30F;
        constexpr float kKopf = 0.60F;
        expect("die drei Anteile ergeben eins",
               std::fabs((kBrust + kHals + kKopf) - 1.0F) < 0.0001F);
        expect("der Kopf bekommt die groesste Haelfte", kKopf > kHals + kBrust);
        // Der Anschlag ist NICHT symmetrisch. Wer ihn symmetrisch macht,
        // laesst den Kopf in eine Richtung fuenf Grad zu weit drehen.
        expect("der Anschlag ist nach links und rechts verschieden",
               std::fabs(bhed::kHeadYawClampMin) !=
                   std::fabs(bhed::kHeadYawClampMax));
        expect("er steht bei -55 und +50",
               near(bhed::kHeadYawClampMin, -55.0F, 0.01F) &&
                   near(bhed::kHeadYawClampMax, 50.0F, 0.01F));
    }

    // --- .sab lesen: die Klinge einer Figur --------------------------------
    //
    // Gemeldet: "weder die Lichtschwerter werden geladen und ordentlich
    // angezeigt als auch die Sounds."
    //
    // Die Kette ist: NPC_type -> .npc `saber` -> .sab-Eintrag -> soundOn.
    // Der Aufbau einer .sab-Datei stammt aus den echten Dateien
    // (MD_Hilts.pk3, ext_data/sabers/single_hilts_pt.sab).
    {
        bhed::SaberMap sm;
        bhed::parseSaberFile(
            "aayla\r\n{\r\n"
            "\tname\t\t\"Aayla Secura\"\r\n"
            "\tsaberType\tSABER_SINGLE\r\n"
            "\tsaberModel\t\"models/weapons2/saber_plasma/saber_aayla.glm\"\r\n"
            "\tsoundOn\t\t\"sound/weapons/saber/saberon.wav\"\r\n"
            "\tsoundLoop\t\"sound/weapons/saber/saberhum2.wav\"\r\n"
            "\tsoundOff\t\"sound/weapons/saber/saberoff.wav\"\r\n"
            "\tsaberColor\tblue\r\n"
            "\tsaberLength\t36\r\n"
            "\tsaberRadius 2.7\r\n}\r\n"
            "\r\n"
            "stumm\r\n{\r\n"
            "\tsaberModel\t\"models/weapons2/saber/saber_w.glm\"\r\n}\r\n",
            sm);
        expect("beide Klingen gelesen", sm.size() == 2);
        const auto it = sm.find("aayla");
        expect("der Eintrag ist da", it != sm.end());
        if (it != sm.end()) {
            // Anfuehrungszeichen muessen weg - sonst sucht der Klangleser
            // spaeter nach einer Datei mit Gaensefuesschen im Namen.
            expect("der Klang steht ohne Anfuehrungszeichen da",
                   it->second.soundOn == "sound/weapons/saber/saberon.wav");
            expect("das Modell ebenso",
                   it->second.model ==
                       "models/weapons2/saber_plasma/saber_aayla.glm");
            // saberColor und saberLength stehen NACKT da, ohne
            // Anfuehrungszeichen. Beide Schreibweisen muessen gehen.
            expect("ein nackter Wert wird auch gelesen",
                   it->second.color == "blue");
            expect("und eine nackte Zahl", near(it->second.length, 36.0F, 0.01F));
            // saberRadius steht in den echten Dateien OHNE Doppelpunkt und
            // ohne Anfuehrungszeichen, oft mit einem Leerzeichen statt
            // eines Tabulators. Der Wert bestimmt die Breite der Klinge -
            // ohne ihn kaeme jede gleich breit heraus.
            expect("und der Radius", near(it->second.radius, 2.7F, 0.01F));
        }
        // Ein Eintrag OHNE Klang - der kommt in den echten Dateien 9 mal
        // von 254 vor. Er muss leer bleiben, damit die Aufrufstelle die
        // Vorgabe der Engine einsetzen kann.
        const auto st = sm.find("stumm");
        expect("ein Eintrag ohne Klang bleibt leer",
               st != sm.end() && st->second.soundOn.empty());
        // Und er behaelt die Vorgabe der Engine fuer den Radius: 3
        // (SABER_RADIUS_STANDARD, wp_saber.h:57). Eine Null waere eine
        // Klinge ohne Breite - unsichtbar.
        expect("und den vorgegebenen Radius",
               st != sm.end() && near(st->second.radius, 3.0F, 0.01F));
        // Ebenso bleibt die LAENGE leer, damit die Aufrufstelle die
        // Vorgabe der Engine einsetzen kann: 32 (wp_saberLoad.cpp:364,
        // "saber->blade[i].lengthMax = 32"). In rc259 stand dort 40 -
        // eine Zahl, die ich erfunden und nicht nachgesehen hatte.
        expect("und keine erfundene Laenge",
               st != sm.end() && near(st->second.length, 0.0F, 0.01F));
    }

    // --- Der saber-Schluessel in der .npc-Datei ----------------------------
    {
        bhed::NpcMap nm;
        bhed::parseNpcFile(
            "md_ani_ga\r\n{\r\n"
            "\tplayerModel\tanakin\r\n"
            "\tsaber\t\tanakin_ep2\r\n"
            "\tsaberColor\tblue\r\n}\r\n"
            "kein_jedi\r\n{\r\n"
            "\tplayerModel\tstormtrooper\r\n}\r\n",
            nm);
        const auto a = nm.find("md_ani_ga");
        expect("der NPC-Typ ist da", a != nm.end());
        if (a != nm.end()) {
            expect("mit seinem Modell", a->second.playerModel == "anakin");
            expect("und seiner Klinge", a->second.saber == "anakin_ep2");
        }
        // saberColor darf NICHT als saber durchgehen - der Vergleich muss
        // genau sein, sonst traegt jeder Jedi die Klinge "blue".
        const auto k = nm.find("kein_jedi");
        expect("wer keine hat, hat keine",
               k != nm.end() && k->second.saber.empty());
    }

    // --- SET_SABERACTIVE: der Zustand, nicht nur der Klang -----------------
    //
    // Der Klang haengt an der Zeitleiste (rc256). Fuer die ANZEIGE braucht
    // es den Zustand je Figur: eine Klinge zeichnet man nur, solange sie an
    // ist.
    {
        const bhed::Scene s = sceneOf(
            "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\twait ( 1000.000 );\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_SABERACTIVE\", \"true\" );\r\n"
            "\twait ( 2000.000 );\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_SABERACTIVE\", \"false\" );\r\n}\r\n",
            map);
        const bhed::Actor& a = s.actors.front();
        expect("vor dem Einschalten ist die Klinge aus",
               !a.at(500.0).saberActive);
        expect("danach ist sie an", a.at(2000.0).saberActive);
        expect("und am Ende wieder aus", !a.at(4000.0).saberActive);
    }

    // --- SET_FIRE_WEAPON und SET_SHOT_SPACING ------------------------------
    //
    // Gemeldet: "es fehlt noch die Schussanimation der Super Battle
    // Droids."
    //
    // Sie steht nicht als Animation im Skript. Zwischen der Skriptzeile und
    // dem Bild liegen VIER Glieder:
    //
    //   SET_FIRE_WEAPON -> SCF_FIRE_WEAPON    (Q3_Interface.cpp:4523)
    //   -> WeaponThink()                      (AI_Default.cpp:742)
    //   -> ShootThink() setzt BUTTON_ATTACK   (NPC_combat.cpp:1109)
    //   -> PM_SetAnim(SETANIM_TORSO, BOTH_ATTACK3, ...RESTART)
    //                                         (bg_pmove.cpp:13810)
    //
    // behaved kannte nur das erste. Hier wird der Zustand gefuehrt; die
    // Animation waehlt die Ansicht.
    {
        const bhed::Scene s = sceneOf(
            "affect ( \"droide\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_SHOT_SPACING\", 750.000 );\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_FIRE_WEAPON\", \"true\" );\r\n"
            "\twait ( 2000.000 );\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_FIRE_WEAPON\", \"false\" );\r\n}\r\n",
            map);
        const bhed::Actor& a = s.actors.front();
        expect("nach SET_FIRE_WEAPON schiesst sie", a.at(1000.0).firing);
        // DER Bezugspunkt fuer den Takt: wann das Feuern begann, nicht wann
        // die Animation begann. Beim Nachrechnen eines Protokolls
        // aufgefallen - in md_ga_jedi steht animStartMs bei 0, das Feuern
        // beginnt aber bei 47400, und die Schuesse lagen damit auf
        // Vielfachen von 750 seit dem SKRIPTanfang.
        expect("und merkt sich, seit wann",
               near(static_cast<float>(a.at(1000.0).firingSinceMs), 0.0F,
                    0.1F));
        expect("und danach nicht mehr", !a.at(3000.0).firing);
        expect("der Schussabstand kommt aus dem Skript",
               near(a.at(1000.0).shotSpacingMs, 750.0F, 0.1F));
    }

    // Der Bezugspunkt wandert MIT dem Feuerbeginn.
    {
        const bhed::Scene s = sceneOf(
            "affect ( \"droide\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\twait ( 5000.000 );\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_FIRE_WEAPON\", \"true\" );\r\n"
            "\twait ( 1000.000 );\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_FIRE_WEAPON\", \"true\" );\r\n}\r\n",
            map);
        const bhed::Actor& a = s.actors.front();
        expect("der Takt beginnt beim ersten SET_FIRE_WEAPON",
               near(static_cast<float>(a.at(7000.0).firingSinceMs), 5000.0F,
                    0.1F));
        // Ein ZWEITES "true" waehrend des Feuerns setzt ihn NICHT zurueck.
        // Sonst begaenne der Takt mitten im Feuern neu, und die Schuesse
        // saessen versetzt.
        expect("ein zweites true setzt ihn nicht zurueck",
               !near(static_cast<float>(a.at(7000.0).firingSinceMs), 6000.0F,
                     0.1F));
    }

    // Ohne SET_SHOT_SPACING gilt eine Vorgabe - und die darf NICHT null
    // sein. Null waere eine Animation, die in jedem Bild neu anfaengt, also
    // ein Standbild auf dem ersten Bild.
    {
        const bhed::Scene s = sceneOf(
            "affect ( \"droide\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_FIRE_WEAPON\", \"true\" );\r\n}\r\n",
            map);
        expect("ohne Angabe bleibt ein brauchbarer Abstand stehen",
               s.actors.front().at(100.0).shotSpacingMs > 1.0F);
    }

    // --- weapons.dat: woher der Muendungsblitz kommt ------------------------
    //
    // Gefragt: "wo bekommen wir das Projektil her?"
    //
    // Aus ext_data/weapons.dat. Der Aufbau ist ANDERS als bei .npc und
    // .sab: dort steht der Name VOR der Klammer, hier als Schluessel
    // `weapontype` DARIN. Wer das uebersieht, liest lauter namenlose
    // Bloecke.
    {
        bhed::WeaponMap w;
        bhed::parseWeaponsDat(
            "// WP_BLASTER\r\n"
            "{\r\n"
            "weapontype       WP_BLASTER\r\n"
            "weaponmodel      models/weapons2/blaster_r/blaster.md3\r\n"
            "firetime         350\r\n"
            "muzzleEffect\t\tblaster/muzzle_flash\r\n"
            "}\r\n"
            "\r\n"
            "{\r\n"
            "weapontype       WP_SABER\r\n"
            "weaponmodel      models/weapons2/saber/saber_w.md3\r\n"
            "}\r\n",
            w);
        expect("beide Waffen gelesen", w.size() == 2);
        const auto it = w.find("WP_BLASTER");
        expect("der Blaster ist unter seinem Typ zu finden", it != w.end());
        if (it != w.end()) {
            expect("mit seinem Modell",
                   it->second.model ==
                       "models/weapons2/blaster_r/blaster.md3");
            // Der Schluessel steht in der Datei mit grossem E. Der Vergleich
            // muss also klein gerechnet werden, sonst faellt genau dieser
            // Wert durch - und ohne ihn gibt es keinen Muendungsblitz.
            expect("und seinem Muendungsblitz",
                   it->second.muzzleEffect == "blaster/muzzle_flash");
            expect("und der Schussdauer", it->second.fireTimeMs == 350);
        }
        // Eine Waffe ohne Blitz bleibt leer - die Aufrufstelle soll dann
        // nichts zeichnen statt eine erfundene Datei zu suchen.
        const auto sb = w.find("WP_SABER");
        expect("ohne Blitz bleibt es leer",
               sb != w.end() && sb->second.muzzleEffect.empty());
    }

    // --- Der weapon-Schluessel in der .npc ---------------------------------
    {
        bhed::NpcMap nm;
        bhed::parseNpcFile(
            "sbd\r\n{\r\n"
            "\tplayerModel\tSBD\r\n"
            "\tweapon\t\tWP_BLASTER\r\n}\r\n"
            "unbewaffnet\r\n{\r\n"
            "\tplayerModel\tjan\r\n}\r\n",
            nm);
        const auto a = nm.find("sbd");
        expect("der Droide traegt seine Waffe",
               a != nm.end() && a->second.weapon == "WP_BLASTER");
        const auto u = nm.find("unbewaffnet");
        expect("wer keine hat, hat keine",
               u != nm.end() && u->second.weapon.empty());
    }

    // --- customSkin: die Hautvariante --------------------------------------
    //
    // Gemeldet: "was noch fehlt, sind richtige Skinvarianten von den
    // Modellen."
    //
    // Daraus wird models/players/<playerModel>/model_<customSkin>.skin
    // (NPC_stats.cpp:1908), Vorgabe "default" (ebenda:1597).
    //
    // In assets1 nennen 73 NPC-Typen einen eigenen Skin, in 41
    // verschiedenen Paaren - darunter DASSELBE Modell mit verschiedenen:
    // cultist braun und rot, reborn_new blau und rot.
    {
        bhed::NpcMap nm;
        bhed::parseNpcFile(
            "cultist\r\n{\r\n"
            "\tplayerModel\tcultist\r\n"
            "\tcustomSkin\tbrown\r\n}\r\n"
            "cultist_red\r\n{\r\n"
            "\tplayerModel\tcultist\r\n"
            "\tcustomSkin\tred\r\n}\r\n"
            "schlicht\r\n{\r\n"
            "\tplayerModel\tjan\r\n}\r\n",
            nm);
        const auto b = nm.find("cultist");
        const auto r = nm.find("cultist_red");
        expect("der braune Kultist", b != nm.end() &&
                                         b->second.customSkin == "brown");
        expect("der rote ebenso", r != nm.end() &&
                                      r->second.customSkin == "red");
        // DAS ist der Fall, um den es geht: gleiches Modell, anderer Skin.
        // Ein Puffer, der nur nach dem Modellnamen schluesselt, gibt dem
        // zweiten den Skin des ersten.
        expect("gleiches Modell, verschiedene Skins",
               b != nm.end() && r != nm.end() &&
                   b->second.playerModel == r->second.playerModel &&
                   b->second.customSkin != r->second.customSkin);
        // Ohne Angabe gilt "default" - NICHT leer. Leer ergaebe
        // "model_.skin", und die gibt es nirgends.
        const auto d = nm.find("schlicht");
        expect("ohne Angabe gilt default",
               d != nm.end() && d->second.customSkin == "default");
    }

    // --- Wo ein Schuss anfaengt, ohne Waffenmodell -------------------------
    //
    // Berichtigt: "SBD schiesst es aus der Hand, deshalb gibt es kein
    // eigenes Waffenmodell."
    //
    // Damit faellt der Weg ueber tag_flash weg. Die Engine rechnet die
    // Muendung dann aus dem ENTITYURSPRUNG (CalcMuzzlePoint,
    // g_weapon.cpp:449 ff.), und fuer WP_BLASTER auf einem NPC:
    //
    //     muzzlePoint[2] += viewheight;   // 36
    //     muzzlePoint[2] -= 1;
    //     VectorMA( muzzlePoint, 2, forward, muzzlePoint );
    //     VectorMA( muzzlePoint, 1, right,   muzzlePoint );
    //
    // Also 35 hoch, 2 vor, 1 rechts. Diese Probe rechnet gegen genau diese
    // Zahlen - sonst waere jede davon beliebig.
    {
        const float o[3] = {100.0F, 200.0F, 300.0F};
        float m[3] = {};

        // Gierwinkel 0: vorn ist +x, rechts ist -y.
        bhed::muzzlePoint(o, 0.0F, "WP_BLASTER", m);
        expect("der Blaster liegt 35 ueber dem Ursprung",
               near(m[2], 335.0F, 0.01F));
        expect("zwei nach vorn", near(m[0], 102.0F, 0.01F));
        expect("und eine nach rechts", near(m[1], 199.0F, 0.01F));

        // Um 90 Grad gedreht wandert "vorn" auf +y und "rechts" auf +x.
        // Ohne diese Zusicherung koennte man vorn und rechts vertauschen,
        // ohne dass es bei Gierwinkel 0 auffiele.
        bhed::muzzlePoint(o, 90.0F, "WP_BLASTER", m);
        expect("gedreht wandert vorn auf +y", near(m[1], 202.0F, 0.01F));
        expect("und rechts auf +x", near(m[0], 101.0F, 0.01F));

        // Eine Pistole sitzt tiefer und weiter vorn - andere Zahlen, damit
        // auffaellt, wenn jemand alle Waffen gleich behandelt.
        bhed::muzzlePoint(o, 0.0F, "WP_BRYAR_PISTOL", m);
        expect("die Pistole liegt tiefer", near(m[2], 320.0F, 0.01F));
        expect("und deutlich weiter vorn", near(m[0], 128.0F, 0.01F));

        // Und eine unbekannte Waffe landet auf Blickhoehe, nicht am Boden.
        // Das ist naeher an der Wahrheit als der Ursprung - und es steht so
        // im Quelltext, statt eine Zahl zu erfinden.
        bhed::muzzlePoint(o, 0.0F, "WP_IRGENDWAS", m);
        expect("eine unbekannte Waffe landet auf Blickhoehe",
               near(m[2], 336.0F, 0.01F) && near(m[0], 100.0F, 0.01F));
    }

    // --- Die Klinge faehrt aus, sie springt nicht --------------------------
    //
    // Gemeldet: "die Animationsgeschwindigkeit, wie schnell das Saber
    // gezogen und gerendert wird - es wird naemlich momentan instant
    // gerendert."
    //
    // cg_players.cpp:7386:
    //
    //     length += lengthMax/10 * cg.frametime/100;
    //
    // Das sind lengthMax/1000 je Millisekunde - EINE SEKUNDE von null bis
    // voll, und zwar fuer JEDE Klinge gleich lang. Eine kurze faehrt also
    // langsamer aus als eine lange, nicht schneller.
    {
        const bhed::Scene s = sceneOf(
            "affect ( \"jedi\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\twait ( 2000.000 );\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_SABERACTIVE\", \"true\" );\r\n"
            "\twait ( 3000.000 );\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_SABERACTIVE\", \"true\" );\r\n}\r\n",
            map);
        const bhed::Actor& a = s.actors.front();
        expect("vorher ist sie aus", !a.at(1000.0).saberActive);
        expect("danach an", a.at(2500.0).saberActive);
        expect("und der Zeitpunkt steht fest",
               near(static_cast<float>(a.at(2500.0).saberSinceMs), 2000.0F,
                    0.1F));
        // Ein ZWEITES "true" darf sie nicht wieder einfahren lassen.
        // Sonst zoege eine Klinge mitten in der Einstellung erneut aus.
        expect("ein zweites true setzt nicht zurueck",
               near(static_cast<float>(a.at(6000.0).saberSinceMs), 2000.0F,
                    0.1F));
    }

    // --- Der Faktor kommt aus dem Gehtempo ---------------------------------
    //
    // Mit behaveds Vorgaben: 90 beim Gehen gegen 50, fuer die die
    // Animation gebaut ist - also Faktor 1,8. Sie lief bisher fast
    // ZWEIMAL zu langsam, und genau das sieht man als Rutschen.
    {
        const bhed::Scene s = sceneOf(
            "affect ( \"jedi\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_WALKING\", \"true\" );\r\n"
            "\tset ( /*@SET_TYPES*/ \"SET_NAVGOAL\", \"ziel1\" );\r\n}\r\n",
            map);
        const bhed::Actor& a = s.actors.front();
        const bhed::ActorState st = a.at(100.0);
        // Der genaue Faktor haengt vom walkSpeed der .npc ab, und die gibt
        // es in dieser Probe nicht. Festgehalten wird deshalb, WAS gelten
        // muss, egal welches Tempo:
        //
        //   - waehrend des Gehens weicht er von 1 ab (sonst gaebe es die
        //     Korrektur gar nicht)
        //   - er bleibt in den Grenzen der Engine
        //
        // Die Rechnung selbst ist in glatest.cpp auf die Nachkommastelle
        // geprueft; hier geht es nur darum, dass sie ueberhaupt ankommt.
        if (st.moving) {
            expect("waehrend des Gehens gilt ein eigener Faktor",
                   st.animSpeed > 0.0F && st.animSpeed != 1.0F);
            expect("und er bleibt in den Grenzen der Engine",
                   st.animSpeed >= bhed::kAnimSpeedMin &&
                       st.animSpeed <= bhed::kAnimSpeedMax);
        }
        // Steht die Figur, laeuft die Animation wieder normal - sonst
        // liefe eine Stehanimation im Gehtakt.
        expect("im Stehen wieder Faktor 1",
               near(a.at(1.0e9).animSpeed, 1.0F, 0.001F));
    }

    // =====================================================================
    // Animationen wie die Engine (rc568, Abgleich gegen OpenJK SP)
    // =====================================================================
    {
        // Hilfe mit festen Laengen: BOTH_GESTURE1 1000 ms, frameLerp 50.
        bhed::SzenenHilfe hilfe;
        hilfe.animDauer = [](const std::string&, const std::string& anim) {
            if (anim == "BOTH_GESTURE1") { return 1000.0; }
            if (anim == "BOTH_STAND1" || anim == "BOTH_WALK1" || anim == "BOTH_RUN1") { return 950.0; }
            return -1.0;
        };
        hilfe.bildDauer = [](const std::string&, const std::string& anim) {
            return (anim == "BOTH_RUN1") ? 34.0 : 50.0;   // RUN1: 30 fps
        };
        const auto mitHilfe = [&](const std::string& body) {
            bhed::Script s;
            std::vector<bhed::Diag> d;
            (void)bhed::readScript("//Generated by BehavEd\r\n" + body, s, d);
            return bhed::buildScene(s, map, &hilfe);
        };
        // --- Anim-Timer: nach der Animation zurueck in den Stand ---------
        {
            const bhed::Scene s = mitHilfe(
                "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
                "\tset ( /*@SET_TYPES*/ \"SET_ANIM_BOTH\", \"BOTH_GESTURE1\" );\r\n}\r\n");
            const bhed::Actor& a = s.actors.front();
            expect("Geste laeuft waehrend ihrer Laenge", a.at(500.0).animation == "BOTH_GESTURE1");
            expect("danach Grundhaltung (PM_Footsteps), nicht Endstellung",
                   a.at(1200.0).animation == "BOTH_STAND1");
            expect("... mit 100 ms Blende ab dem Ablauf",
                   a.at(1050.0).prevAnimation == "BOTH_GESTURE1" &&
                       near(static_cast<float>(a.at(1050.0).blendStartMs), 1000.0F));
        }
        {
            const bhed::Scene s = mitHilfe(
                "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
                "\tset ( /*@SET_TYPES*/ \"SET_ANIM_BOTH\", \"BOTH_GESTURE1\" );\r\n"
                "\tset ( /*@SET_TYPES*/ \"SET_ANIM_HOLDTIME_BOTH\", -1 );\r\n}\r\n");
            expect("HOLDTIME -1: bleibt in der Animation",
                   s.actors.front().at(5000.0).animation == "BOTH_GESTURE1");
        }
        {
            const bhed::Scene s = mitHilfe(
                "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
                "\tset ( /*@SET_TYPES*/ \"SET_ANIM_BOTH\", \"BOTH_GESTURE1\" );\r\n"
                "\tset ( /*@SET_TYPES*/ \"SET_ANIM_HOLDTIME_BOTH\", 400 );\r\n}\r\n");
            expect("HOLDTIME 400: Stand ab 400 ms (kuerzer als die Geste)",
                   s.actors.front().at(300.0).animation == "BOTH_GESTURE1" &&
                       s.actors.front().at(500.0).animation == "BOTH_STAND1");
        }
        // --- wait( "task" ) wartet die Animation ab; dowait ebenso ------
        {
            const bhed::Scene s = mitHilfe(
                "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
                "\ttask ( \"geste\" )\r\n\t{\r\n"
                "\t\tset ( /*@SET_TYPES*/ \"SET_ANIM_BOTH\", \"BOTH_GESTURE1\" );\r\n\t}\r\n"
                "\tdowait ( \"geste\" );\r\n"
                "\tset ( /*@SET_TYPES*/ \"SET_NAVGOAL\", \"ziel1\" );\r\n}\r\n");
            const bhed::Actor& a = s.actors.front();
            bool hatAnim = false;
            double wegAb = -1.0;
            for (const bhed::ActorStep& st : a.steps) {
                if (st.kind == bhed::ActorStep::Kind::Anim) { hatAnim = true; }
                if (st.kind == bhed::ActorStep::Kind::WalkTo) { wegAb = st.startMs; }
            }
            expect("dowait fuehrt den Task aus (vorher uebergangen)", hatAnim);
            expect("... und wartet, bis die Animation fertig ist", near(static_cast<float>(wegAb), 1000.0F));
        }
        // --- Gehen/Laufen: zwei Schalter, ueber Bloecke, RUNNING vorn -----
        {
            const bhed::Scene s = mitHilfe(
                "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
                "\tset ( /*@SET_TYPES*/ \"SET_WALKING\", \"true\" );\r\n}\r\n"
                "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
                "\tset ( /*@SET_TYPES*/ \"SET_NAVGOAL\", \"ziel1\" );\r\n}\r\n");
            expect("SET_WALKING gilt im naechsten affect weiter",
                   s.actors.front().at(100.0).animation == "BOTH_WALK1");
        }
        {
            const bhed::Scene s = mitHilfe(
                "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
                "\tset ( /*@SET_TYPES*/ \"SET_WALKING\", \"true\" );\r\n"
                "\tset ( /*@SET_TYPES*/ \"SET_RUNNING\", \"true\" );\r\n"
                "\tset ( /*@SET_TYPES*/ \"SET_NAVGOAL\", \"ziel1\" );\r\n}\r\n");
            expect("RUNNING geht vor WALKING", s.actors.front().at(100.0).animation == "BOTH_RUN1");
            // Tempo: absolut hoechstens 1,5 gegenueber 20 fps - RUN1 hat 30
            // fps (frameLerp 34), also Faktor <= 1,5*34/50 = 1,02.
            expect("Lauftempo wie die Engine begrenzt (nicht 45 fps)",
                   s.actors.front().at(100.0).animSpeed <= 1.03F);
        }
        {
            const bhed::Scene s = mitHilfe(
                "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
                "\tset ( /*@SET_TYPES*/ \"SET_RUNNING\", \"false\" );\r\n"
                "\tset ( /*@SET_TYPES*/ \"SET_NAVGOAL\", \"ziel1\" );\r\n}\r\n");
            expect("SET_RUNNING false heisst NICHT gehen (ohne WALKING wird gelaufen)",
                   s.actors.front().at(100.0).animation == "BOTH_RUN1");
        }
        // --- Nach dem Weg: Grundhaltung ab dem Wegende, nicht ab "jetzt" --
        {
            const bhed::Scene s = mitHilfe(
                "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
                "\tset ( /*@SET_TYPES*/ \"SET_NAVGOAL\", \"ziel1\" );\r\n}\r\n");
            const bhed::ActorState st = s.actors.front().at(20000.0);
            expect("nach dem Weg: BOTH_STAND1 mit Start am Wegende (nicht Bild 0 fuer immer)",
                   st.animation == "BOTH_STAND1" && st.animStartMs < 19000.0);
        }
        // --- Loslaufen: drehen mit der Drehrate, nicht springen -----------
        {
            // Die Figur schaut nach 90 Grad, das Ziel liegt bei 0 Grad.
            const bhed::Scene s = mitHilfe(
                "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
                "\tset ( /*@SET_TYPES*/ \"SET_NAVGOAL\", \"ziel1\" );\r\n}\r\n");
            const float bei0 = s.actors.front().at(0.0).angles[1];
            const float gleichDanach = s.actors.front().at(50.0).angles[1];
            expect("beim Loslaufen noch der alte Winkel", near(bei0, 90.0F, 1.0F));
            expect("... und nicht sofort die Laufrichtung", gleichDanach > 30.0F);
            expect("nach einer Weile in Laufrichtung", near(s.actors.front().at(2000.0).angles[1], 0.0F, 1.0F));
        }
        // --- Der Oberkoerper blendet fuer sich (eigene Knochenanimation) ---
        {
            const bhed::Scene s = mitHilfe(
                "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
                "\tset ( /*@SET_TYPES*/ \"SET_ANIM_UPPER\", \"BOTH_GESTURE1\" );\r\n}\r\n");
            const bhed::ActorState a = s.actors.front().at(50.0);
            expect("UPPER: der Oberkoerper blendet von dem, was er zeigte (hier den Beinen)",
                   a.torsoPrevAnimation == "BOTH_STAND1" &&
                       near(bhed::torsoBlendFraction(a, 50.0), 0.5F, 0.01F));
            expect("... und die Beine blenden dabei NICHT", bhed::blendFraction(a, 50.0) >= 1.0F);
            const bhed::ActorState b = s.actors.front().at(1050.0);
            expect("Oberkoerper-Timer abgelaufen: Uebergang zurueck zu den Beinen",
                   b.torsoAnimation.empty() && b.torsoPrevAnimation == "BOTH_GESTURE1" &&
                       near(static_cast<float>(b.torsoBlendStartMs), 1000.0F));
        }
        {
            const bhed::Scene s = mitHilfe(
                "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
                "\tset ( /*@SET_TYPES*/ \"SET_ANIM_UPPER\", \"BOTH_GESTURE1\" );\r\n"
                "\twait ( 300.000 );\r\n"
                "\tset ( /*@SET_TYPES*/ \"SET_ANIM_BOTH\", \"BOTH_WALK1\" );\r\n}\r\n");
            const bhed::ActorState a = s.actors.front().at(320.0);
            expect("BOTH nach UPPER: der Oberkoerper blendet von SEINER Animation",
                   a.torsoPrevAnimation == "BOTH_GESTURE1" && a.torsoAnimation.empty() &&
                       a.prevAnimation == "BOTH_STAND1");
        }
        // --- Weg waehrend einer Skriptanimation: sie bleibt, bis ihr Timer
        //     ablaeuft (PM_SetAnimFinal: bodyPlay = override || !timer) ----
        {
            const bhed::Scene s = mitHilfe(
                "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
                "\tset ( /*@SET_TYPES*/ \"SET_ANIM_BOTH\", \"BOTH_GESTURE1\" );\r\n"
                "\tset ( /*@SET_TYPES*/ \"SET_NAVGOAL\", \"ziel1\" );\r\n}\r\n");
            const bhed::Actor& a = s.actors.front();
            const bhed::ActorState mitten = a.at(500.0);
            expect("Weg mit laufender Geste: die Geste bleibt",
                   mitten.animation == "BOTH_GESTURE1");
            expect("... und die Figur gleitet trotzdem zum Ziel", mitten.pos[0] > 50.0F);
            const bhed::ActorState danach = a.at(1500.0);
            expect("Timer abgelaufen: jetzt die Laufanimation, ab dem Ablauf",
                   danach.animation == "BOTH_RUN1" &&
                       near(static_cast<float>(danach.animStartMs), 1000.0F));
            expect("am Ziel: Grundhaltung, nicht die alte Geste",
                   a.at(9000.0).animation == "BOTH_STAND1");
        }
        {
            const bhed::Scene s = mitHilfe(
                "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
                "\tset ( /*@SET_TYPES*/ \"SET_ANIM_BOTH\", \"BOTH_GESTURE1\" );\r\n"
                "\tset ( /*@SET_TYPES*/ \"SET_ANIM_HOLDTIME_BOTH\", -1 );\r\n"
                "\tset ( /*@SET_TYPES*/ \"SET_NAVGOAL\", \"ziel1\" );\r\n}\r\n");
            expect("HOLDTIME -1 und Weg: die Animation bleibt den ganzen Weg",
                   s.actors.front().at(2000.0).animation == "BOTH_GESTURE1" &&
                       s.actors.front().at(9000.0).animation == "BOTH_GESTURE1");
        }
        {
            // Ohne Skelett (keine Laenge bekannt) wie bisher: der Weg loest ab.
            const bhed::Scene s = sceneOf(
                "affect ( \"held\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
                "\tset ( /*@SET_TYPES*/ \"SET_ANIM_BOTH\", \"BOTH_GESTURE1\" );\r\n"
                "\tset ( /*@SET_TYPES*/ \"SET_NAVGOAL\", \"ziel1\" );\r\n}\r\n", map);
            expect("ohne bekannte Laenge: der Weg loest die Animation ab",
                   s.actors.front().at(500.0).animation == "BOTH_RUN1");
        }
    }

    // --- Bildtakt wie die Engine (gla.cpp, frameForAnimationIn) ----------
    {
        std::vector<bhed::AnimEntry> sek;
        bhed::AnimEntry rueck;
        rueck.name = "BOTH_STAND2TO1";
        rueck.firstFrame = 100;
        rueck.numFrames = 5;
        rueck.loopFrame = -1;
        rueck.fps = -10;   // rueckwaerts, frameLerp 100
        sek.push_back(rueck);
        bhed::AnimEntry schnell;
        schnell.name = "BOTH_RUN1";
        schnell.firstFrame = 200;
        schnell.numFrames = 10;
        schnell.loopFrame = 0;
        schnell.fps = 30;  // frameLerp ceil(33,3) = 34
        sek.push_back(schnell);
        expect("negative fps: beginnt beim LETZTEN Bild",
               bhed::frameForAnimationIn(sek, "BOTH_STAND2TO1", 0.0, false, 1.0F, nullptr, nullptr) == 104);
        expect("... und laeuft rueckwaerts mit 10 fps",
               bhed::frameForAnimationIn(sek, "BOTH_STAND2TO1", 250.0, false, 1.0F, nullptr, nullptr) == 102);
        expect("... und bleibt am ersten stehen",
               bhed::frameForAnimationIn(sek, "BOTH_STAND2TO1", 9000.0, false, 1.0F, nullptr, nullptr) == 100);
        expect("30 fps: frameLerp 34 ms, bei 33,5 ms noch Bild 0",
               bhed::frameForAnimationIn(sek, "BOTH_RUN1", 33.5, false, 1.0F, nullptr, nullptr) == 200);
        expect("... bei 34 ms Bild 1",
               bhed::frameForAnimationIn(sek, "BOTH_RUN1", 34.0, false, 1.0F, nullptr, nullptr) == 201);
    }

    std::printf("\n%s (%d Fehlschlaege)\n",
                fails != 0 ? "FEHLGESCHLAGEN" : "alle Szenenproben bestanden", fails);
    return fails != 0 ? 1 : 0;
}
