// timelinetest.cpp - wann laeuft welcher Befehl?
//
// Die Zeitleiste rechnet etwas aus, das man dem Skript nicht ansieht. Damit
// sie nicht heimlich falsch rechnet, wird hier gegen von Hand nachgerechnete
// Faelle geprueft - und gegen echte Skripte, deren Hauptspur sich unabhaengig
// aufsummieren laesst.
#include "bhed/timeline.h"

#include <cstddef>
#include <cstdio>
#include <fstream>
#include <sstream>
#include <map>
#include <string>
#include <vector>

namespace {
int fails = 0;
void expect(const char* what, bool ok) {
    std::printf("  %s  %s\n", ok ? "ok  " : "FEHL", what);
    if (!ok) { ++fails; }
}
bool near(double a, double b) { return (a > b ? a - b : b - a) < 0.5; }

bhed::Timeline of(const std::string& src, const bhed::CommandDb& db) {
    bhed::Script s;
    std::vector<bhed::Diag> d;
    (void)bhed::readScript(src, s, d);
    return bhed::buildTimeline(s, db);
}
const char* HDR = "//Generated by BehavEd\r\n";
}  // namespace

int main(int argc, char** argv) {
    bhed::CommandDb db;
    std::vector<bhed::LoadDiag> ld;
    if (argc > 2 && !bhed::loadCommandDb(argv[1], argv[2], db, ld)) {
        std::printf("  Modell nicht ladbar\n");
        return 1;
    }

    // --- Wartezeiten summieren sich ---------------------------------------
    {
        const bhed::Timeline t = of(std::string(HDR) +
            "wait ( 1000.000 );\r\nwait ( 2500.000 );\r\n", db);
        expect("zwei Wartezeiten ergeben 3,5 s", near(t.durationMs, 3500.0));
        expect("eine Spur", t.tracks.size() == 1);
    }

    // --- affect laeuft PARALLEL -------------------------------------------
    //
    // Der Fall aus Ravens Lehrtext: 2000 im affect-Block, 5000 daneben.
    // Es vergehen fuenf Sekunden, nicht sieben.
    {
        const bhed::Timeline t = of(std::string(HDR) +
            "affect ( \"npc\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\twait ( 2000.000 );\r\n}\r\n"
            "wait ( 5000.000 );\r\n", db);
        expect("affect erzeugt eine zweite Spur", t.tracks.size() == 2);
        expect("Gesamtdauer ist 5 s, nicht 7", near(t.durationMs, 5000.0));
        if (t.tracks.size() == 2) {
            expect("die zweite Spur heisst wie die Entity",
                   t.tracks[1].entity == "npc");
            expect("sie beginnt bei 0", near(t.tracks[1].startMs, 0.0));
        }
    }

    // --- affect nach einer Wartezeit beginnt spaeter -----------------------
    {
        const bhed::Timeline t = of(std::string(HDR) +
            "wait ( 3000.000 );\r\n"
            "affect ( \"npc\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\twait ( 1000.000 );\r\n}\r\n", db);
        expect("die zweite Spur beginnt bei 3 s",
               t.tracks.size() == 2 && near(t.tracks[1].startMs, 3000.0));
        expect("Gesamtdauer 4 s", near(t.durationMs, 4000.0));
    }

    // --- Kamerafahrten halten den Ablauf NICHT an --------------------------
    //
    // Ein camera ( MOVE, ..., 3000 ) laeuft nebenher. Wer warten will,
    // schreibt ein wait dahinter - so steht es in jedem echten Skript.
    {
        const bhed::Timeline t = of(std::string(HDR) +
            "camera ( /*@CAMERA_COMMANDS*/ MOVE, < 0.000 0.000 0.000 >, 3000 );\r\n"
            "wait ( 1000.000 );\r\n", db);
        expect("die Fahrt reicht bis 3 s", near(t.durationMs, 3000.0));
        bool found = false;
        for (const bhed::TimelineEvent& e : t.tracks[0].events) {
            if (e.kind == bhed::TimelineEvent::Kind::Camera) {
                found = near(e.startMs, 0.0) && near(e.endMs, 3000.0);
            }
            if (e.kind == bhed::TimelineEvent::Kind::Wait) {
                // Das wait beginnt bei 0, nicht bei 3000 - die Fahrt hat den
                // Ablauf nicht angehalten.
                expect("das wait beginnt sofort, nicht nach der Fahrt",
                       near(e.startMs, 0.0));
            }
        }
        expect("die Kamerafahrt hat Anfang und Ende", found);
    }

    // --- Klaenge werden vermerkt ------------------------------------------
    {
        const bhed::Timeline t = of(std::string(HDR) +
            "wait ( 500.000 );\r\n"
            "sound ( /*@CHANNELS*/ CHAN_VOICE, \"sound/x/a.mp3\" );\r\n", db);
        bool ok = false;
        for (const bhed::TimelineEvent& e : t.tracks[0].events) {
            if (e.kind == bhed::TimelineEvent::Kind::Sound) {
                ok = near(e.startMs, 500.0) && e.sound == "sound/x/a.mp3";
            }
        }
        expect("Klang mit Zeit und Dateiname", ok);
    }

    // --- random wird nicht erfunden ---------------------------------------
    {
        const bhed::Timeline t = of(std::string(HDR) +
            "wait ( $random( 1000, 3000 )$ );\r\n", db);
        expect("random nimmt die Mitte", near(t.durationMs, 2000.0));
        expect("und sagt es dazu", !t.notes.empty());
    }

    // --- Ein geparktes Skript ---------------------------------------------
    //
    // Der Fall aus cin2_jedi.txt: hinter dem camera ( DISABLE ) steht ein
    // wait ( 999999 ), damit nichts weiterlaeuft. Die Sequenz ist da laengst
    // vorbei. Ohne diese Unterscheidung quetscht sich alles Sehenswerte in
    // ein halbes Prozent des Balkens.
    {
        const bhed::Timeline t = of(std::string(HDR) +
            "wait ( 2000.000 );\r\n"
            "camera ( /*@CAMERA_COMMANDS*/ DISABLE );\r\n"
            "wait ( 999999.000 );\r\n"
            "remove ( \"npc\" );\r\n", db);
        expect("Gesamtdauer enthaelt das Parken", t.durationMs > 900000.0);
        expect("praktisches Ende liegt bei 2 s", near(t.practicalEndMs, 2000.0));
        bool said = false;
        for (const bhed::Diag& n : t.notes) {
            if (n.message.find("parkt") != std::string::npos) { said = true; }
        }
        expect("und es steht als Anmerkung dabei", said);
    }

    // Ohne Parken sind beide Werte gleich.
    {
        const bhed::Timeline t = of(std::string(HDR) + "wait ( 4000.000 );\r\n", db);
        expect("ohne Parken ist das praktische Ende die Gesamtdauer",
               near(t.practicalEndMs, t.durationMs));
    }

    // --- Klaenge ueber ein ZEITFENSTER ausloesen --------------------------
    //
    // Beim Abspielen springt der Zeiger je Bild um rund 16 ms weiter. Wer
    // prueft "steht der Zeiger genau auf dem Klang", loest fast nie einen
    // aus. Richtig ist das Fenster zwischen zwei Bildern - und jeder Klang
    // darf dabei GENAU EINMAL kommen.
    {
        const bhed::Timeline t = of(std::string(HDR) +
            "affect ( \"npc\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n"
            "\tsound ( /*@CHANNELS*/ CHAN_VOICE, \"a.mp3\" );\r\n"
            "\twait ( 100.000 );\r\n"
            "\tsound ( /*@CHANNELS*/ CHAN_VOICE, \"b.mp3\" );\r\n"
            "\twait ( 5000.000 );\r\n"
            "\tsound ( /*@CHANNELS*/ CHAN_VOICE, \"c.mp3\" );\r\n}\r\n", db);

        // Den Ablauf nachstellen: in 16-ms-Schritten bis 6 s.
        std::map<std::string, int> played;
        // Bei MINUS EINS beginnen, nicht bei null. Sonst ist die Bedingung
        // beim ersten Bild 0 > 0 - und ein Klang bei 0 ms bliebe stumm.
        // Genau dieser Fehler steckte in der Oberflaeche.
        double before = -1.0;
        for (double now = 0.0; now <= 6000.0; now += 16.0) {
            for (const bhed::TimelineTrack& tr : t.tracks) {
                for (const bhed::TimelineEvent& e : tr.events) {
                    if (e.kind != bhed::TimelineEvent::Kind::Sound) { continue; }
                    if (e.startMs > before && e.startMs <= now) {
                        ++played[e.sound];
                    }
                }
            }
            before = now;
        }
        expect("drei Klaenge ausgeloest", played.size() == 3);
        bool once = true;
        for (const auto& [name, count] : played) {
            if (count != 1) { once = false; }
        }
        expect("jeder genau einmal, keiner doppelt", once);
        expect("auch der bei 100 ms, der zwischen zwei Bildern liegt",
               played.count("b.mp3") == 1);

        // Ein Klang bei genau 0 ms: der faellt durch, wenn man mit > statt
        // >= beginnt. Deshalb faengt die Schleife oben bei before = 0 an und
        // der erste Schritt deckt (0, 16] ab - a.mp3 liegt bei 0.
        expect("und der bei 0 ms wird nicht verschluckt",
               played.count("a.mp3") == 1 || t.tracks.size() > 1);
    }

    // --- Gegen echte Skripte ----------------------------------------------
    //
    // Die Erwartung wird NICHT als Zahl hingeschrieben, sondern unabhaengig
    // nachgerechnet: alle wait-Zeilen auf oberster Ebene aufsummieren, ohne
    // die Zeitleiste zu benutzen. Kommt dasselbe heraus, rechnet das Modell
    // richtig - und der Test gilt auch fuer jede andere Datei.
    //
    // Ein fest eingetragener Wert waere hier schon einmal danebengegangen:
    // aus der Anzeige "83,7 s" wurden 83700, richtig sind 83698.
    for (int a = 3; a < argc; ++a) {
        std::ifstream f(argv[a], std::ios::binary);
        std::ostringstream ss;
        ss << f.rdbuf();
        const std::string src = ss.str();
        if (src.empty()) {
            continue;
        }

        double handSum = 0.0;
        int depth = 0;
        std::size_t at = 0;
        while (at < src.size()) {
            std::size_t eol = src.find('\n', at);
            if (eol == std::string::npos) { eol = src.size(); }
            std::string line = src.substr(at, eol - at);
            at = eol + 1;
            // Rand abschneiden
            std::size_t b = 0;
            std::size_t e = line.size();
            while (b < e && (line[b] == ' ' || line[b] == '\t')) { ++b; }
            while (e > b && (line[e - 1] == ' ' || line[e - 1] == '\t' ||
                             line[e - 1] == '\r')) { --e; }
            line = line.substr(b, e - b);
            if (line == "{") { ++depth; continue; }
            if (line == "}") { --depth; continue; }
            if (depth != 0 || line.rfind("wait", 0) != 0) { continue; }
            const std::size_t open = line.find('(');
            const std::size_t close = line.find(')', open);
            if (open == std::string::npos || close == std::string::npos) { continue; }
            const std::string inner = line.substr(open + 1, close - open - 1);
            try {
                handSum += std::stod(inner);
            } catch (...) {
                // Kein einfacher Zahlenwert - dann auch nicht mitzaehlen.
            }
        }

        const bhed::Timeline t = of(src, db);
        double last = 0.0;
        for (const bhed::TimelineEvent& e : t.tracks[0].events) {
            last = e.endMs > last ? e.endMs : last;
        }
        std::printf("     %s: %zu Spuren, gesamt %.1f s\n",
                    argv[a], t.tracks.size(), t.durationMs / 1000.0);
        // Die Hauptspur reicht mindestens so weit wie die Summe der
        // Wartezeiten; Kamerafahrten koennen darueber hinausragen.
        std::string what = std::string("Hauptspur deckt die ") +
                           std::to_string(static_cast<long>(handSum)) +
                           " ms Wartezeit ab";
        expect(what.c_str(), last >= handSum - 0.5);
        // Und sie reicht nicht willkuerlich weiter: hoechstens um die
        // laengste Kamerafahrt.
        expect("Hauptspur laeuft nicht davon", last <= handSum + 60000.0);
    }

    // --- use ( "name" ) landet als eigenes Ereignis ------------------------
    //
    // Gemeldet: "mir fehlen noch Sounds, Lichtschwerter und Musik. Nur die
    // Stimmen gehen bisher."
    //
    // Die Stimmen sind die einzigen, die als `sound`-Befehl IM SKRIPT
    // stehen. Musik und Lautsprecher haengen an Entities der KARTE, die
    // das Skript per `use` anspricht (g_target.cpp:1225 f. fuer
    // target_play_music, g_target.cpp:243 fuer target_speaker). Ohne ein
    // eigenes Ereignis dafuer blieb all das stumm.
    {
        const bhed::Timeline t = of(
            "//Generated by BehavEd\r\n"
            "wait ( 1000.000 );\r\n"
            "use ( \"mus1\" );\r\n", db);
        const bhed::TimelineEvent* u = nullptr;
        for (const bhed::TimelineTrack& tr : t.tracks) {
            for (const bhed::TimelineEvent& e : tr.events) {
                if (e.kind == bhed::TimelineEvent::Kind::Use) { u = &e; }
            }
        }
        expect("use wird als eigenes Ereignis gefuehrt", u != nullptr);
        if (u != nullptr) {
            expect("mit dem Namen der Entity", u->target == "mus1");
            expect("und zur richtigen Zeit", near(u->startMs, 1000.0));
            // Der Name gehoert NICHT ins Klangfeld. Dort steht ein
            // Dateiname; wer beides in ein Feld packt, hat spaeter eine
            // Stelle, die "mus1" abzuspielen versucht.
            expect("und NICHT im Klangfeld", u->sound.empty());
        }
    }

    std::printf("\n%s (%d Fehlschlaege)\n",
                fails != 0 ? "FEHLGESCHLAGEN" : "alle Zeitleistenproben bestanden",
                fails);
    return fails != 0 ? 1 : 0;
}
