// waffentest.cpp - Waffe und Lichtschwerter einer Figur ueber die Zeit
//
// Die Proben zu src/ausruestung.cpp: kleine, von Hand geschriebene Skripte,
// deren ActorState zu bestimmten Zeiten gegen das geprueft wird, was die
// Engine an der jeweils genannten Stelle tut.
//
// Aufruf ohne Argumente: nur die Proben.
// Mit  <behaved.bhc> <include-Ordner> <Ordner>:  zusaetzlich eine Durchsicht
// aller .ibi, .npc, .sab und weapons.dat unter <Ordner> (ausgepackte .pk3)
// - zaehlt, wie oft welcher Fall in den echten Skripten vorkommt.
#include "bhed/commands.h"
#include "bhed/glm.h"
#include "bhed/ibi.h"
#include "bhed/mapview.h"
#include "bhed/scene.h"

#include <cctype>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <map>
#include <set>
#include <sstream>
#include <string>
#include <vector>

namespace {
int fails = 0;
void expect(const char* what, bool ok) {
    std::printf("  %s  %s\n", ok ? "ok  " : "FEHL", what);
    if (!ok) { ++fails; }
}
bool near(float a, float b, float eps = 0.01F) { return std::fabs(a - b) < eps; }

// Karte mit drei Spawnern: ein Soldat, ein Jedi, ein Pistolero.
bhed::MapData karte() {
    bhed::MapData m;
    bhed::parseEntities(
        "{\n\"classname\" \"NPC_spawner\"\n\"npc_targetname\" \"soldat\"\n"
        "\"NPC_type\" \"md_trooper\"\n\"origin\" \"0 0 0\"\n}\n"
        "{\n\"classname\" \"NPC_spawner\"\n\"npc_targetname\" \"jedi\"\n"
        "\"NPC_type\" \"md_jedi\"\n\"origin\" \"100 0 0\"\n}\n"
        "{\n\"classname\" \"NPC_spawner\"\n\"npc_targetname\" \"jedi2\"\n"
        "\"NPC_type\" \"md_jedi\"\n\"origin\" \"150 0 0\"\n}\n"
        "{\n\"classname\" \"NPC_spawner\"\n\"npc_targetname\" \"duo\"\n"
        "\"NPC_type\" \"md_duo\"\n\"origin\" \"200 0 0\"\n}\n"
        "{\n\"classname\" \"NPC_spawner\"\n\"npc_targetname\" \"sturm\"\n"
        "\"NPC_type\" \"md_sturm\"\n\"origin\" \"300 0 0\"\n}\n"
        "{\n\"classname\" \"NPC_spawner\"\n\"npc_targetname\" \"zivil\"\n"
        "\"NPC_type\" \"md_zivil\"\n\"origin\" \"400 0 0\"\n}\n",
        m.entities);
    return m;
}

struct Daten {
    bhed::NpcMap npcs;
    bhed::SaberMap sabers;
    bhed::WeaponMap waffen;
    bhed::SzenenHilfe hilfe;
};

void fuelle(Daten& d) {
    bhed::parseNpcFile(
        "md_trooper\n{\n\tplayerModel\tclonetrooper\n\tweapon\tWP_BLASTER\n}\n"
        "md_jedi\n{\n\tplayerModel\tanakin\n\tweapon\tWP_SABER\n"
        "\tsaber\tdoppel\n}\n"
        "md_duo\n{\n\tplayerModel\tjango\n\tweapon\tWP_DUAL_PISTOL\n"
        "\tdualPistols\t1\n\tkotorWeapons\t1\n}\n"
        // Keine Waffe genannt: die Vorgabe nach Team (NPC_WeaponsForTeam).
        "md_sturm\n{\n\tplayerModel\tstormtrooper\n\tplayerTeam\tTEAM_ENEMY\n}\n"
        "md_zivil\n{\n\tplayerModel\tjan\n\tplayerTeam\tTEAM_NEUTRAL\n}\n",
        d.npcs);
    bhed::parseSaberFile(
        "doppel\n{\n"
        "\tsaberType\tSABER_STAFF\n"
        "\tsaberModel\t\"models/weapons2/saber_maul/saber_w.glm\"\n"
        "\tsoundLoop\t\"sound/weapons/saber/saberhum1.wav\"\n"
        "\tnumBlades\t2\n"
        "\tsaberColor\tred\n"
        "\tsaberLength\t40\n"
        "\ttwoHanded\t1\n}\n"
        "einzeln\n{\n"
        "\tsaberModel\t\"models/weapons2/saber_luke/saber_w.glm\"\n"
        "\tsaberColor\tgreen\n"
        "\tsaberLength\t32\n}\n"
        "stock\n{\n"
        "\tsaberModel\t\"models/weapons2/gaffi/gaffi.glm\"\n"
        "\tnoBlade\t1\n}\n",
        d.sabers);
    bhed::parseWeaponsDat(
        "{\nweapontype\tWP_BLASTER\nweaponmodel\tmodels/weapons2/blaster_r/blaster.md3\n}\n"
        "{\nweapontype\tWP_REPEATER\nweaponmodel\tmodels/weapons2/heavy_repeater/heavy_repeater.md3\n}\n"
        "{\nweapontype\tWP_DUAL_PISTOL\nweaponmodel\tmodels/weapons2/westar_if/westar.md3\n"
        "altweaponmodel\tmodels/weapons2/kotor_pistol1/kotor_pistol1.md3\n}\n"
        "{\nweapontype\tWP_MELEE\nweaponmodel\tmodels/weapons2/noweap/noweap.md3\n}\n",
        d.waffen);
    d.hilfe.npcs = &d.npcs;
    d.hilfe.sabers = &d.sabers;
    d.hilfe.waffen = &d.waffen;
}

bhed::Scene szene(const Daten& d, const bhed::MapData& m, const std::string& rumpf) {
    bhed::Script s;
    std::vector<bhed::Diag> diag;
    (void)bhed::readScript("//Generated by BehavEd\r\n" + rumpf, s, diag);
    return bhed::buildScene(s, m, &d.hilfe);
}

std::string affect(const char* wer, const std::string& inhalt) {
    return std::string("affect ( \"") + wer + "\", /*@AFFECT_TYPE*/ FLUSH )\r\n{\r\n" + inhalt +
           "}\r\n";
}
std::string setze(const char* was, const std::string& wert) {
    return std::string("\tset ( /*@SET_TYPES*/ \"") + was + "\", " + wert + " );\r\n";
}
std::string warte(int ms) {
    return "\twait ( " + std::to_string(ms) + ".000 );\r\n";
}

// Welches Modell haengt in der Hand? Leer: keines.
std::string hand(const bhed::Actor& a, const bhed::ActorState& st, int n) {
    const int m = st.hand[static_cast<std::size_t>(n)].modell;
    if (m < 0 || static_cast<std::size_t>(m) >= a.modelle.size()) {
        return {};
    }
    return a.modelle[static_cast<std::size_t>(m)];
}

bool zufallsFarbe(const std::string& f) {
    return f == "orange" || f == "yellow" || f == "green" || f == "blue" || f == "purple";
}

void proben() {
    Daten d;
    fuelle(d);
    const bhed::MapData m = karte();

    // --- Die Leser ---------------------------------------------------------
    {
        const auto it = d.sabers.find("doppel");
        expect(".sab: Doppelklinge gelesen", it != d.sabers.end());
        if (it != d.sabers.end()) {
            expect(".sab: numBlades 2", it->second.numBlades == 2);
            expect(".sab: saberType gross", it->second.type == "SABER_STAFF");
            expect(".sab: twoHanded", it->second.twoHanded);
            expect(".sab: saberColor gilt fuer ALLE Klingen",
                   it->second.bladeColor[0] == "red" && it->second.bladeColor[7] == "red");
            expect(".sab: saberLength ebenso", near(it->second.bladeLength[1], 40.0F));
        }
        bhed::SaberMap sm;
        bhed::parseSaberFile(
            "je\n{\n\tsaberColor\tred\n\tsaberColor2\tgreen\n\tsaberLength\t30\n"
            "\tsaberLength3\t2\n\tsaberRadius2\t0.1\n\tsaberColor8\tblue\n"
            "\tbladeStyle2Start\t1\n\tnoBlade2\t1\n\tboltToWrist\t1\n}\n",
            sm);
        const auto j = sm.find("je");
        expect(".sab: saberColor2 trifft nur Klinge 2",
               j != sm.end() && j->second.bladeColor[0] == "red" &&
                   j->second.bladeColor[1] == "green" && j->second.bladeColor[2] == "red");
        expect(".sab: saberLength unter 4 wird 4 (Saber_ParseSaberLength3)",
               j != sm.end() && near(j->second.bladeLength[2], 4.0F) &&
                   near(j->second.bladeLength[0], 30.0F));
        expect(".sab: saberRadius unter 0.25 wird 0.25",
               j != sm.end() && near(j->second.bladeRadius[1], 0.25F));
        expect(".sab: saberColor8 kennt die Tabelle nicht",
               j != sm.end() && j->second.bladeColor[7] == "red");
        expect(".sab: bladeStyle2Start, noBlade2, boltToWrist",
               j != sm.end() && j->second.bladeStyle2Start == 1 && j->second.noBlade2 &&
                   !j->second.noBlade && j->second.boltToWrist);

        bhed::NpcMap nm;
        bhed::parseNpcFile(
            "a\n{\n\tplayerModel\tx\n\tsaberColor\tblue\n\tsaber\ts1\n"
            "\tsaberColor2\tred\n\tsaberColor1\tgreen\n\tsaber2\ts2\n\tsaber2Color\tpurple\n"
            "\tsaber2Length\t2\n\tplayerTeam\tTEAM_ENEMY\n\tkotorWeapons\t0\n}\n",
            nm);
        const auto a = nm.find("a");
        expect(".npc: saber2 gelesen", a != nm.end() && a->second.saber2 == "s2");
        expect(".npc: saberColor VOR saber wird vom Schwert ueberschrieben",
               a != nm.end() && a->second.saberFarbe[0][0].empty());
        expect(".npc: saberColor2 ist Klinge 2, saberColor1 wird verworfen",
               a != nm.end() && a->second.saberFarbe[0][1] == "red" &&
                   a->second.saberFarbe[0][0].empty());
        expect(".npc: saber2Color fuer alle Klingen des zweiten",
               a != nm.end() && a->second.saberFarbe[1][0] == "purple" &&
                   a->second.saberFarbe[1][5] == "purple");
        expect(".npc: saber2Length unter 4 wird 4",
               a != nm.end() && near(a->second.saberLaenge[1][0], 4.0F));
        expect(".npc: playerTeam und kotorWeapons (auch mit 0)",
               a != nm.end() && a->second.team == "TEAM_ENEMY" && a->second.kotorWeapons);

        const auto w = d.waffen.find("WP_DUAL_PISTOL");
        expect("weapons.dat: altweaponmodel",
               w != d.waffen.end() &&
                   w->second.altModel == "models/weapons2/kotor_pistol1/kotor_pistol1.md3");
    }

    // --- Die Kampfhaltung mit brennender Klinge ---------------------------
    {
        bhed::SaberMap sm;
        bhed::parseSaberFile(
            "stab\n{\n\tsaberType\tSABER_STAFF\n\tnumBlades\t2\n\tsaberStyle\tstaff\n"
            "\tsingleBladeStyle\tstrong\n}\n"
            "frei\n{\n\tsaberStyleForbidden\tdual\n\tsaberStyleLearned\ttavion\n}\n",
            sm);
        const auto s = sm.find("stab");
        expect(".sab: saberStyle staff lernt Stab und verbietet den Rest",
               s != sm.end() && s->second.stylesLearned == (1 << 7) &&
                   s->second.stylesForbidden == 0x7E && s->second.singleBladeStyle == 3);
        const auto f = sm.find("frei");
        expect(".sab: saberStyleLearned/-Forbidden",
               f != sm.end() && f->second.stylesLearned == (1 << 5) &&
                   f->second.stylesForbidden == (1 << 6));
        bhed::NpcMap nm;
        bhed::parseNpcFile("v\n{\n\tplayerModel\tx\n\tsaberStyle\t9\n\tclass\tCLASS_VADER\n\trank\tlt\n}\n", nm);
        const auto v = nm.find("v");
        expect(".npc: saberStyle gekappt, class und rank",
               v != nm.end() && v->second.saberStil == 7 && v->second.klasse == "CLASS_VADER" &&
                   v->second.rang == "lt");
        expect("Haltung: SS_FAST, SS_MEDIUM, SS_STAFF",
               std::string(bhed::saberHaltungFuerStil(1)) == "BOTH_SABERFAST_STANCE" &&
                   std::string(bhed::saberHaltungFuerStil(2)) == "BOTH_STAND2" &&
                   std::string(bhed::saberHaltungFuerStil(7)) == "BOTH_SABERSTAFF_STANCE");

        // Der Jedi (Doppelklinge, ohne saberStyle, ohne Team) hat SS_MEDIUM.
        // Zuenden bei 1000 ms: vorher Stand, danach BOTH_STAND2 mit Blende;
        // Ausschalten bei 3000: eine Sekunde einfahren, dann zurueck.
        const bhed::Scene sz = szene(d, m, affect("jedi", warte(1000) + setze("SET_SABERACTIVE", "\"true\"") +
                                                          warte(2000) + setze("SET_SABERACTIVE", "\"false\"")));
        const bhed::Actor* j = sz.find("jedi");
        expect("Haltung: Figur da", j != nullptr);
        if (j != nullptr) {
            expect("Haltung: Startstil SS_MEDIUM", j->startStil == 2);
            const bhed::ActorState vor = j->at(900.0);
            const bhed::ActorState an = j->at(2000.0);
            const bhed::ActorState ein = j->at(3600.0);
            const bhed::ActorState aus = j->at(4500.0);
            expect("Haltung: vor dem Zuenden BOTH_STAND1", vor.animation == "BOTH_STAND1");
            expect("Haltung: gezuendet BOTH_STAND2, Blende ab dem Zuenden",
                   an.animation == "BOTH_STAND2" && an.prevAnimation == "BOTH_STAND1" &&
                       an.blendStartMs >= 1000.0 && an.blendStartMs <= 1100.0);
            expect("Haltung: beim Einfahren noch die Kampfhaltung", ein.animation == "BOTH_STAND2");
            expect("Haltung: eingefahren zurueck in BOTH_STAND1",
                   aus.animation == "BOTH_STAND1" && aus.prevAnimation == "BOTH_STAND2" &&
                       aus.blendStartMs > 3900.0 && aus.blendStartMs < 4200.0);
        }
        // Ein Schwert mit saberStyle staff zwingt den Stil, sobald es brennt.
        bhed::Actor stabFigur;
        bhed::SaberArt sa;
        sa.numBlades = 2;
        sa.stilVerboten = 0x7E;
        sa.stilGelernt = 1 << 7;
        stabFigur.saberArten.push_back(sa);
        stabFigur.startStil = 1;
        bhed::ActorState st;
        st.saber[0].art = 0;
        st.saber[0].numBlades = 2;
        st.saber[0].klinge[0].an = true;
        st.saber[0].klinge[1].an = true;
        expect("Stil: verbotener Stil wird zum ersten erlaubten (Stab)",
               bhed::saberStilJetzt(stabFigur, st) == 7);
        stabFigur.saberArten[0].stilEineKlinge = 3;
        st.saber[0].klinge[1].an = false;
        expect("Stil: nur die erste Klinge -> singleBladeStyle", bhed::saberStilJetzt(stabFigur, st) == 3);
        bhed::Actor duo;
        duo.saberArten.resize(2);
        duo.startStil = 2;
        bhed::ActorState ds;
        ds.dualSabers = true;
        ds.saber[0].art = 0;
        ds.saber[1].art = 1;
        ds.saber[0].numBlades = 1;
        ds.saber[1].numBlades = 1;
        ds.saber[0].klinge[0].an = true;
        ds.saber[1].klinge[0].an = true;
        expect("Stil: zwei brennende Schwerter -> SS_DUAL", bhed::saberStilJetzt(duo, ds) == 6);
        ds.saber[1].klinge[0].an = false;
        expect("Stil: zweites aus -> Startstil bleibt", bhed::saberStilJetzt(duo, ds) == 2);
    }

    // --- Der Spieler ist unsichtbar, solange die Skriptkamera laeuft ------
    {
        bhed::Actor spieler;
        spieler.name = "player";
        spieler.haveStart = true;
        spieler.kameraVerborgen = {{1000.0, 5000.0}, {8000.0, -1.0}};
        expect("Spieler: vor camera ENABLE sichtbar", spieler.at(500.0).visible);
        expect("Spieler: waehrend der Kamerafahrt unsichtbar", !spieler.at(3000.0).visible);
        expect("Spieler: nach DISABLE wieder sichtbar", spieler.at(6000.0).visible);
        expect("Spieler: ENABLE ohne DISABLE - bis zum Ende unsichtbar", !spieler.at(60000.0).visible);
    }

    // --- Der Name des Weltmodells (G_CreateG2AttachedWeaponModel) ----------
    {
        expect("blaster.md3 -> blaster_w.glm",
               bhed::waffenWeltmodell("models/weapons2/blaster_r/blaster.md3") ==
                   "models/weapons2/blaster_r/blaster_w.glm");
        expect("noweap bekommt kein _w",
               bhed::waffenWeltmodell("models/weapons2/noweap/noweap.md3") ==
                   "models/weapons2/noweap/noweap.glm");
        expect("ein _w irgendwo im Pfad verhindert das zweite",
               bhed::waffenWeltmodell("models/weapons2/saber/saber_w.md3") ==
                   "models/weapons2/saber/saber_w.glm");
        expect(".glm bleibt, wie es ist",
               bhed::waffenWeltmodell("models/weapons2/saber_1/saber_1.glm") ==
                   "models/weapons2/saber_1/saber_1.glm");
        expect("leer wird DEFAULT_SABER_MODEL",
               bhed::waffenWeltmodell("") == bhed::kStandardGriff);
    }

    // --- Farben (TranslateSaberColor, Q_parseSaberColor) --------------------
    {
        const std::string r1 = bhed::saberFarbeAufloesen("random", "jedi|0");
        expect("random: eine der fuenf, nie rot", zufallsFarbe(r1));
        expect("random: bei gleicher Saat dieselbe",
               bhed::saberFarbeAufloesen("RANDOM", "jedi|0") == r1);
        std::set<std::string> alle;
        for (int i = 0; i < 64; ++i) {
            alle.insert(bhed::saberFarbeAufloesen("random", "figur" + std::to_string(i)));
        }
        expect("random: verschiedene Figuren bekommen verschiedene", alle.size() >= 4);
        bool nieRot = true;
        for (const std::string& f : alle) { nieRot = nieRot && zufallsFarbe(f); }
        expect("random: ueber 64 Figuren nie rot", nieRot);
        const std::string p = bhed::saberFarbeAufloesen("prequel_random", "x");
        expect("prequel_random: gruen oder blau", p == "green" || p == "blue");
        expect("benannte Farben klein, unveraendert",
               bhed::saberFarbeAufloesen(" Red ", "x") == "red");
        float rgb[3] = {};
        expect("xff3f00 ist eine RGB-Farbe", bhed::saberFarbeRgb("xff3f00", rgb));
        expect("... und zwar 255/63/0", near(rgb[0], 1.0F) && near(rgb[1], 63.0F / 255.0F) &&
                                            near(rgb[2], 0.0F));
        expect("red ist keine", !bhed::saberFarbeRgb("red", rgb));
        expect("unstable_red auch nicht", !bhed::saberFarbeRgb("unstable_red", rgb));
    }

    // --- Vorgabewaffe nach Team (NPC_WeaponsForTeam) -------------------------
    {
        expect("Feind ohne Angabe: Blaster",
               bhed::npcTeamWaffe("TEAM_ENEMY", "md_sturm", 0) == "WP_BLASTER");
        expect("reborn*: Schwert", bhed::npcTeamWaffe("enemy", "reborn_new", 0) == "WP_SABER");
        expect("gran: Thermal vor Melee", bhed::npcTeamWaffe("enemy", "gran", 0) == "WP_THERMAL");
        expect("Spieler jedi*: Schwert", bhed::npcTeamWaffe("TEAM_PLAYER", "jedi2", 0) == "WP_SABER");
        expect("Spieler mit SFB_RIFLEMAN: Repeater",
               bhed::npcTeamWaffe("TEAM_PLAYER", "rebel", 2) == "WP_REPEATER");
        expect("neutral und frei: keine",
               bhed::npcTeamWaffe("TEAM_NEUTRAL", "x", 0) == "WP_NONE" &&
                   bhed::npcTeamWaffe("", "x", 0) == "WP_NONE");
    }

    // --- Spawnen: Waffe aus der .npc -----------------------------------------
    {
        const bhed::Scene s = szene(d, m, affect("soldat", setze("SET_WALKING", "\"true\"")) +
                                              affect("sturm", setze("SET_WALKING", "\"true\"")) +
                                              affect("zivil", setze("SET_WALKING", "\"true\"")) +
                                              affect("duo", setze("SET_WALKING", "\"true\"")));
        const bhed::Actor* so = s.find("soldat");
        const bhed::Actor* st = s.find("sturm");
        const bhed::Actor* zi = s.find("zivil");
        const bhed::Actor* du = s.find("duo");
        expect("vier Figuren", so && st && zi && du);
        if (so && st && zi && du) {
            const bhed::ActorState a = so->at(0.0);
            expect("Soldat: WP_BLASTER aus der .npc", a.waffe == "WP_BLASTER");
            expect("... blaster_w.glm in der rechten Hand",
                   hand(*so, a, 0) == "models/weapons2/blaster_r/blaster_w.glm" &&
                       !a.hand[0].istSaber);
            expect("... die linke leer", hand(*so, a, 1).empty());
            expect("... kein Schwert, keine Klinge", !a.hatSaber && !a.saberActive);
            const bhed::ActorState b = st->at(0.0);
            expect("ohne weapon: Vorgabe nach Team (Blaster)", b.waffe == "WP_BLASTER" &&
                       hand(*st, b, 0) == "models/weapons2/blaster_r/blaster_w.glm");
            expect("neutral ohne weapon: nichts in der Hand",
                   zi->at(0.0).waffe == "WP_NONE" && hand(*zi, zi->at(0.0), 0).empty());
            const bhed::ActorState c = du->at(0.0);
            expect("dualPistols: beide Haende, kotorWeapons: altweaponmodel",
                   hand(*du, c, 0) == "models/weapons2/kotor_pistol1/kotor_pistol1_w.glm" &&
                       hand(*du, c, 1) == hand(*du, c, 0));
        }
    }

    // --- SET_WEAPON ueber die Zeit ------------------------------------------
    {
        const bhed::Scene s = szene(
            d, m,
            affect("soldat", warte(1000) + setze("SET_WEAPON", "\"WP_NONE\"") + warte(1000) +
                                 setze("SET_WEAPON", "\"WP_REPEATER\"") + warte(1000) +
                                 setze("SET_SABERACTIVE", "\"true\"") + warte(1000) +
                                 setze("SET_WEAPON", "\"WP_MELEE\"") + warte(1000) +
                                 setze("SET_WEAPON", "\"drop\"")));
        const bhed::Actor& a = s.actors.front();
        expect("vor SET_WEAPON: der Blaster",
               hand(a, a.at(500.0), 0) == "models/weapons2/blaster_r/blaster_w.glm");
        expect("WP_NONE: Hand leer, Waffe WP_NONE",
               hand(a, a.at(1500.0), 0).empty() && a.at(1500.0).waffe == "WP_NONE");
        expect("WP_REPEATER: heavy_repeater_w.glm",
               hand(a, a.at(2500.0), 0) ==
                   "models/weapons2/heavy_repeater/heavy_repeater_w.glm");
        expect("SET_SABERACTIVE ohne Schwert: nichts (Q3_SetSaberActive bricht ab)",
               !a.at(3500.0).saberActive && a.at(3500.0).waffe == "WP_REPEATER");
        expect("WP_MELEE: noweap.glm (die Engine haengt es an)",
               hand(a, a.at(4500.0), 0) == "models/weapons2/noweap/noweap.glm");
        expect("drop: WP_NONE, Hand leer",
               a.at(5500.0).waffe == "WP_NONE" && hand(a, a.at(5500.0), 0).empty());
    }

    // --- Doppelklinge: SET_SABERACTIVE, BLADEON/OFF, Wachsen ----------------
    //
    // Jede Klinge waechst mit lengthMax/1000 je ms (cg_players.cpp:16306 ff.)
    // und schrumpft ebenso (ebenda:16233 ff.).
    {
        const bhed::Scene s = szene(
            d, m,
            affect("jedi", warte(1000) + setze("SET_SABERACTIVE", "\"true\"") + warte(2000) +
                               setze("SET_SABER1BLADEOFF", "1.000") + warte(1000) +
                               setze("SET_SABER1BLADEON", "1.000") + warte(1000) +
                               setze("SET_SABERACTIVE", "\"false\"") + warte(2000) +
                               setze("SET_SABER1BLADEON", "7.000")));
        const bhed::Actor& a = s.actors.front();
        const bhed::ActorState s0 = a.at(0.0);
        expect("Jedi: WP_SABER, Griff in der rechten Hand",
               s0.waffe == "WP_SABER" &&
                   hand(a, s0, 0) == "models/weapons2/saber_maul/saber_w.glm" &&
                   s0.hand[0].istSaber);
        expect("... zwei Klingen, beide rot, beide aus",
               s0.saber[0].numBlades == 2 && s0.saber[0].klinge[0].farbe == "red" &&
                   s0.saber[0].klinge[1].farbe == "red" && !s0.saberActive);
        expect("... beim Spawnen aus: Laenge 0", near(bhed::klingenLaenge(s0, 0, 0, 0.0), 0.0F));
        const bhed::ActorState s1 = a.at(1500.0);
        expect("nach einer halben Sekunde: halbe Laenge (20 von 40), beide Klingen",
               near(bhed::klingenLaenge(s1, 0, 0, 1500.0), 20.0F) &&
                   near(bhed::klingenLaenge(s1, 0, 1, 1500.0), 20.0F));
        expect("nach einer Sekunde voll", near(bhed::klingenLaenge(s1, 0, 0, 2000.0), 40.0F) &&
                                              near(bhed::klingenLaenge(s1, 0, 0, 2500.0), 40.0F));
        expect("der Summton des Schwerts (soundLoop)",
               s1.saberLoop == "sound/weapons/saber/saberhum1.wav");
        const bhed::ActorState s2 = a.at(3250.0);
        expect("BLADEOFF 1: nur Klinge 2 schrumpft",
               near(bhed::klingenLaenge(s2, 0, 0, 3250.0), 40.0F) &&
                   near(bhed::klingenLaenge(s2, 0, 1, 3250.0), 30.0F) &&
                   !s2.saber[0].klinge[1].an);
        expect("... und es summt weiter", s2.saberActive && !s2.saberLoop.empty());
        const bhed::ActorState s3 = a.at(4250.0);
        expect("BLADEON 1 nach einer Sekunde: waechst wieder von 0",
               near(bhed::klingenLaenge(s3, 0, 1, 4250.0), 10.0F));
        const bhed::ActorState s4 = a.at(5500.0);
        expect("SET_SABERACTIVE false: beide schrumpfen",
               near(bhed::klingenLaenge(s4, 0, 0, 5500.0), 20.0F) && !s4.saberActive);
        expect("... und kein Summton mehr", s4.saberLoop.empty());
        expect("... nach einer Sekunde weg", near(bhed::klingenLaenge(s4, 0, 0, 6000.0), 0.0F));
        expect("BLADEON 7 gibt es nicht (numBlades 2): nichts",
               !a.at(7500.0).saberActive);
        expect("saberSinceMs bleibt die Kurzfassung",
               near(static_cast<float>(a.at(2500.0).saberSinceMs), 1000.0F, 0.1F));
    }

    // --- SET_SABER2: zweites Schwert links, InitBladeData -----------------------
    {
        const bhed::Scene s = szene(
            d, m,
            affect("jedi", setze("SET_SABER1", "\"einzeln\"") + warte(2000) +
                               setze("SET_SABER2", "\"einzeln\"") + warte(2000) +
                               setze("SET_SABER2_COLOR1", "\"purple\"") +
                               setze("SET_SABER1_COLOR2", "\"random\"") + warte(1000) +
                               setze("SET_SABER2", "\"doppel\"") + warte(1000) +
                               setze("SET_SABER2", "\"einzeln\"") + warte(1000) +
                               setze("SET_SABER2", "\"none\"")));
        const bhed::Actor& a = s.actors.front();
        const bhed::ActorState s0 = a.at(500.0);
        expect("SET_SABER1 mit dem Schwert in der Hand: neuer Griff",
               hand(a, s0, 0) == "models/weapons2/saber_luke/saber_w.glm");
        expect("... und er ZUENDET (WP_SetSaber: SetLength(0), Activate())",
               s0.saberActive && near(bhed::klingenLaenge(s0, 0, 0, 500.0), 16.0F));
        expect("... eine Klinge, gruen", s0.saber[0].numBlades == 1 &&
                                             s0.saber[0].klinge[0].farbe == "green");
        const bhed::ActorState s1 = a.at(2500.0);
        expect("SET_SABER2: dualSabers, Griff links",
               s1.dualSabers && hand(a, s1, 1) == "models/weapons2/saber_luke/saber_w.glm");
        expect("... das zweite zuendet", near(bhed::klingenLaenge(s1, 1, 0, 2500.0), 16.0F));
        expect("... und das ERSTE faengt wieder bei null an (WP_SaberInitBladeData)",
               near(bhed::klingenLaenge(s1, 0, 0, 2500.0), 16.0F));
        const bhed::ActorState s2 = a.at(4500.0);
        expect("SET_SABER2_COLOR1: die erste Klinge des zweiten",
               s2.saber[1].klinge[0].farbe == "purple");
        expect("SET_SABER1_COLOR2 random: Klinge 2 des ersten, eine der fuenf",
               zufallsFarbe(s2.saber[0].klinge[1].farbe) &&
                   s2.saber[0].klinge[0].farbe == "green");
        const bhed::ActorState s3 = a.at(5500.0);
        expect("SET_SABER2 mit einem Zweihaender: sofort wieder entfernt",
               !s3.dualSabers && hand(a, s3, 1).empty());
        const bhed::ActorState s4 = a.at(6500.0);
        expect("wieder ein Einhaender links", s4.dualSabers && !hand(a, s4, 1).empty());
        const bhed::ActorState s5 = a.at(7500.0);
        expect("SET_SABER2 none: kein zweites mehr, Hand leer",
               !s5.dualSabers && hand(a, s5, 1).empty());
        expect("... das erste bleibt in der Hand", !hand(a, s5, 0).empty());
    }

    // --- WP_NONE und zurueck: die Engine laesst ps.weapons stehen ------------
    //
    // SET_WEAPON WP_NONE entfernt den Griff, laesst aber ps.weapons[WP_SABER].
    // SET_SABERACTIVE schaltet danach auf WP_SABER, haengt den Griff aber NICHT
    // wieder an - also keine Klinge. Erst SET_WEAPON WP_SABER bringt ihn
    // zurueck, und die Klinge steht, wie sie beim Weglegen stand.
    {
        const bhed::Scene s = szene(
            d, m,
            affect("jedi", setze("SET_SABERACTIVE", "\"true\"") + warte(500) +
                               setze("SET_WEAPON", "\"WP_NONE\"") + warte(1000) +
                               setze("SET_SABERACTIVE", "\"true\"") + warte(1000) +
                               setze("SET_WEAPON", "\"WP_SABER\"") + warte(1000) +
                               setze("SET_WEAPON", "\"WP_BLASTER\"") + warte(1000) +
                               setze("SET_WEAPON", "\"WP_SABER\"")));
        const bhed::Actor& a = s.actors.front();
        const bhed::ActorState s0 = a.at(1000.0);
        expect("WP_NONE: Hand leer, hatSaber bleibt",
               hand(a, s0, 0).empty() && s0.hatSaber && s0.waffe == "WP_NONE");
        expect("... die Klinge wird nicht gezeichnet und steht (20 von 40)",
               !bhed::haeltSaber(s0) && near(bhed::klingenLaenge(s0, 0, 0, 1000.0), 20.0F));
        const bhed::ActorState s1 = a.at(2000.0);
        expect("SET_SABERACTIVE danach: WP_SABER, aber KEIN Griff",
               s1.waffe == "WP_SABER" && hand(a, s1, 0).empty());
        const bhed::ActorState s2 = a.at(2500.0);
        expect("SET_WEAPON WP_SABER: Griff wieder da, Klinge laengst voll",
               !hand(a, s2, 0).empty() && near(bhed::klingenLaenge(s2, 0, 0, 2500.0), 40.0F));
        const bhed::ActorState s3 = a.at(3500.0);
        expect("WP_BLASTER: Blaster in der Hand, hatSaber weg",
               hand(a, s3, 0) == "models/weapons2/blaster_r/blaster_w.glm" && !s3.hatSaber);
        const bhed::ActorState s4 = a.at(4750.0);
        expect("WP_SABER nach einer ANDEREN Waffe: Klinge bei null (InitBladeData)",
               near(bhed::klingenLaenge(s4, 0, 0, 4750.0), 10.0F));
    }

    // --- SET_SABER1 mit einer Waffe in der Hand --------------------------------
    {
        const bhed::Scene s = szene(
            d, m, affect("soldat", warte(1000) + setze("SET_SABER1", "\"stock\"")));
        const bhed::Actor& a = s.actors.front();
        const bhed::ActorState s0 = a.at(2000.0);
        expect("SET_SABER1 entfernt das Modell im Fach - auch den Blaster",
               hand(a, s0, 0).empty() && s0.waffe == "WP_BLASTER");
        expect("... und zuendet nichts, die Figur haelt kein Schwert", !s0.saberActive);
    }

    // --- random aus der .sab: je Figur fest ------------------------------------
    {
        bhed::SaberMap sm;
        bhed::parseSaberFile("bunt\n{\n\tsaberColor\trandom\n\tnumBlades\t2\n}\n"
                             "grau\n{\n\tnumBlades\t2\n}\n",
                             sm);
        Daten e;
        fuelle(e);
        e.sabers = sm;
        e.hilfe.sabers = &e.sabers;
        const std::string skript = affect("jedi", setze("SET_SABER1", "\"bunt\"")) +
                                   affect("jedi2", setze("SET_SABER1", "\"grau\""));
        const bhed::Scene s1 = szene(e, m, skript);
        const bhed::Scene s2 = szene(e, m, skript);
        const bhed::ActorState j1 = s1.find("jedi")->at(100.0);
        const bhed::ActorState j2 = s2.find("jedi")->at(100.0);
        expect("saberColor random: eine der fuenf",
               zufallsFarbe(j1.saber[0].klinge[0].farbe));
        expect("... EIN Wurf fuer alle Klingen (Saber_ParseSaberColor)",
               j1.saber[0].klinge[0].farbe == j1.saber[0].klinge[1].farbe);
        expect("... und bei jedem Aufbau dieselbe",
               j1.saber[0].klinge[0].farbe == j2.saber[0].klinge[0].farbe);
        const bhed::ActorState g = s1.find("jedi2")->at(100.0);
        expect("ohne saberColor: jede Klinge fuer sich zufaellig (WP_SaberSetDefaults)",
               zufallsFarbe(g.saber[0].klinge[0].farbe) &&
                   zufallsFarbe(g.saber[0].klinge[1].farbe));
    }

    // --- Kinomodelle (SET_ADD*HANDBOLT_MODEL) -----------------------------------
    {
        const bhed::Scene s = szene(
            d, m,
            affect("soldat", warte(1000) +
                                 setze("SET_ADDLHANDBOLT_MODEL", "\"models/items/datapad.glm\"") +
                                 warte(1000) +
                                 setze("SET_REMOVERHANDBOLT_MODEL", "\"models/items/datapad.glm\"") +
                                 warte(1000) +
                                 setze("SET_ADDRHANDBOLT_MODEL", "\"models/items/a.glm\"") +
                                 setze("SET_ADDLHANDBOLT_MODEL", "\"models/items/b.glm\"") +
                                 warte(1000) +
                                 setze("SET_REMOVELHANDBOLT_MODEL", "\"x\"")));
        const bhed::Actor& a = s.actors.front();
        const auto kino = [&a](const bhed::ActorState& st) {
            std::vector<std::string> v;
            for (const bhed::KinoModell& k : st.kino) {
                if (k.modell >= 0) {
                    v.push_back((k.links ? "L:" : "R:") +
                                a.modelle[static_cast<std::size_t>(k.modell)]);
                }
            }
            return v;
        };
        expect("vorher nichts", kino(a.at(500.0)).empty());
        const auto k1 = kino(a.at(1500.0));
        expect("ADDLHANDBOLT: das Datapad links",
               k1.size() == 1 && k1[0] == "L:models/items/datapad.glm");
        expect("... die Waffe bleibt daneben",
               hand(a, a.at(1500.0), 0) == "models/weapons2/blaster_r/blaster_w.glm");
        expect("REMOVERHANDBOLT nimmt es weg - die Seite zaehlt nicht",
               kino(a.at(2500.0)).empty());
        const auto k2 = kino(a.at(3500.0));
        expect("zwei Adds hintereinander: BEIDE haengen (das erste wird nur vergessen)",
               k2.size() == 2);
        const auto k3 = kino(a.at(4500.0));
        expect("Remove nimmt nur das zuletzt angehaengte",
               k3.size() == 1 && k3[0] == "R:models/items/a.glm");
    }

    // --- Ohne .npc: das alte Verhalten -------------------------------------------
    {
        bhed::Script sc;
        std::vector<bhed::Diag> diag;
        (void)bhed::readScript(
            "//Generated by BehavEd\r\n" +
                affect("jedi", setze("SET_SABERACTIVE", "\"true\"")),
            sc, diag);
        const bhed::Scene s = bhed::buildScene(sc, m);
        const bhed::ActorState st = s.actors.front().at(2000.0);
        expect("ohne .npc: Waffe unbekannt, die Klinge brennt trotzdem",
               st.waffe.empty() && st.saberActive && bhed::haeltSaber(st));
        expect("... mit der Vorgabe von 32", near(bhed::klingenLaenge(st, 0, 0, 2000.0), 32.0F));
        expect("... und dem Vorgabeton", st.saberLoop == "sound/weapons/saber/saberhum3.wav");
    }
}

// --- Durchsicht echter Daten -----------------------------------------------
std::string lies(const std::filesystem::path& p) {
    std::ifstream f(p, std::ios::binary);
    std::ostringstream o;
    o << f.rdbuf();
    return o.str();
}

int durchsicht(const char* bhc, const char* inc, const char* ordner) {
    namespace fs = std::filesystem;
    bhed::CommandDb db;
    std::vector<bhed::LoadDiag> ld;
    if (!bhed::loadCommandDb(bhc, inc, db, ld)) {
        std::printf("Befehlsliste nicht lesbar: %s\n", bhc);
        return 2;
    }
    Daten d;
    std::vector<fs::path> ibis;
    std::map<std::string, fs::path> glms;
    for (const auto& e : fs::recursive_directory_iterator(ordner)) {
        if (!e.is_regular_file()) { continue; }
        std::string ext = e.path().extension().string();
        for (char& c : ext) { c = static_cast<char>(std::tolower(static_cast<unsigned char>(c))); }
        const std::string name = e.path().filename().string();
        if (ext == ".npc") { bhed::parseNpcFile(lies(e.path()), d.npcs); }
        if (ext == ".sab") { bhed::parseSaberFile(lies(e.path()), d.sabers); }
        if (name == "weapons.dat") { bhed::parseWeaponsDat(lies(e.path()), d.waffen); }
        if (ext == ".ibi") { ibis.push_back(e.path()); }
        if (ext == ".glm") {
            // Der Pfad ab "models/" - so nennen ihn .sab und weapons.dat.
            std::string rel = e.path().generic_string();
            for (char& c : rel) { c = static_cast<char>(std::tolower(static_cast<unsigned char>(c))); }
            const std::size_t at = rel.find("/models/");
            if (at != std::string::npos) { glms[rel.substr(at + 1)] = e.path(); }
        }
    }
    d.hilfe.npcs = &d.npcs;
    d.hilfe.sabers = &d.sabers;
    d.hilfe.waffen = &d.waffen;
    std::printf("Durchsicht: %zu NPC-Typen, %zu Schwerter, %zu Waffen, %zu Skripte\n",
                d.npcs.size(), d.sabers.size(), d.waffen.size(), ibis.size());
    int skripte = 0;
    std::map<std::string, int> zaehler;
    std::vector<std::string> beispiele;
    const bhed::MapData leer;
    for (const fs::path& p : ibis) {
        std::vector<bhed::IbiBlock> bl;
        std::vector<bhed::Diag> dg;
        if (!bhed::readIbi(lies(p), bl, dg)) { continue; }
        bhed::Script sc;
        if (!bhed::decompile(bl, db, sc, dg)) { continue; }
        ++skripte;
        const bhed::Scene s = bhed::buildScene(sc, leer, &d.hilfe);
        for (const bhed::Actor& a : s.actors) {
            for (const bhed::ActorStep& st : a.steps) {
                const bhed::ActorState z = a.at(st.startMs);
                using K = bhed::ActorStep::Kind;
                if (st.kind == K::Saber && st.value > 0.5F) {
                    ++zaehler["SET_SABERACTIVE true"];
                    // Der Fall "WP_NONE, dann SET_SABERACTIVE": die Engine
                    // schaltet um, zeigt aber keinen Griff und keine Klinge.
                    if (z.waffe == "WP_SABER" && z.hand[0].modell < 0) {
                        ++zaehler["... danach WP_SABER ohne Griff (keine Klinge sichtbar)"];
                        if (beispiele.size() < 8) {
                            beispiele.push_back(p.filename().string() + " " + a.name + " @" +
                                                std::to_string(static_cast<int>(st.startMs)));
                        }
                    }
                    if (!z.waffe.empty() && z.waffe != "WP_SABER") {
                        ++zaehler["... mit anderer Waffe (wirkungslos)"];
                    }
                }
                if (st.kind == K::Waffe && st.text != "WP_NONE" && st.text != "WP_SABER" &&
                    st.text != "drop") {
                    ++zaehler["SET_WEAPON mit Modell"];
                    if (st.index < 0) { ++zaehler["... Waffe NICHT in weapons.dat"]; }
                }
                if (st.kind == K::SaberWahl) {
                    ++zaehler["SET_SABER1/2"];
                    const std::string k = st.text;
                    if (k != "none" && k != "remove" && st.index >= 0 &&
                        !a.saberArten[static_cast<std::size_t>(st.index)].gefunden) {
                        ++zaehler["... Schwert NICHT in den .sab"];
                    }
                }
            }
        }
    }
    // --- Die Modelle dazu, soweit ausgepackt ------------------------------
    //
    // Haengt an jedem Griff jede Klinge? Und gibt es jedes Waffenmodell?
    // Dieselbe Rechnung wie beim Zeichnen (klingenStrecke).
    {
        std::set<std::string> griffe;
        std::set<std::string> waffenModelle;
        std::map<std::string, std::pair<std::string, int>> griffArt;   // Pfad -> Typ, Klingen
        for (const auto& [name, def] : d.sabers) {
            (void)name;
            if (!def.model.empty()) {
                std::string k = def.model;
                for (char& c : k) { c = static_cast<char>(std::tolower(static_cast<unsigned char>(c))); }
                griffe.insert(k);
                griffArt[k] = {def.type, def.numBlades};
            }
        }
        for (const auto& [typ, def] : d.waffen) {
            (void)typ;
            std::string k = bhed::waffenWeltmodell(def.model);
            for (char& c : k) { c = static_cast<char>(std::tolower(static_cast<unsigned char>(c))); }
            waffenModelle.insert(k);
        }
        int geladen = 0;
        int fehlt = 0;
        int mitTag = 0;
        int mitHack = 0;
        int ohneBolzen = 0;
        int stabUmgedreht = 0;
        int stabFalsch = 0;
        for (const std::string& g : griffe) {
            const auto it = glms.find(g);
            if (it == glms.end()) { ++fehlt; continue; }
            bhed::GlmModel mdl;
            std::string err;
            if (!bhed::readGlm(lies(it->second), mdl, &err)) { ++fehlt; continue; }
            ++geladen;
            const auto& [typ, n] = griffArt[g];
            const bhed::KlingenLage lage = bhed::klingenLageFuer(typ);
            float w0[3] = {};
            float s0[3] = {};
            for (int b = 0; b < n; ++b) {
                float w[3];
                float sp[3];
                if (!bhed::klingenStrecke(mdl, lage, b, 32.0F, w, sp)) {
                    ++ohneBolzen;
                    if (beispiele.size() < 16) { beispiele.push_back("ohne Bolzen: " + g); }
                    break;
                }
                const bool tag = bhed::surfaceIndex(mdl, "*blade" + std::to_string(b + 1)) >= 0;
                (tag ? mitTag : mitHack) += 1;
                if (b == 0) {
                    for (int k = 0; k < 3; ++k) { w0[k] = w[k]; s0[k] = sp[k]; }
                } else if (b == 1 && lage == bhed::KlingenLage::Stab) {
                    // Die zweite Klinge eines Stabs zeigt in die GEGENRICHTUNG.
                    float dot = 0.0F;
                    for (int k = 0; k < 3; ++k) { dot += (s0[k] - w0[k]) * (sp[k] - w[k]); }
                    (dot < 0.0F ? stabUmgedreht : stabFalsch) += 1;
                }
            }
        }
        int wGeladen = 0;
        int wFehlt = 0;
        for (const std::string& w : waffenModelle) {
            const auto it = glms.find(w);
            if (it == glms.end()) {
                ++wFehlt;
                if (beispiele.size() < 16) { beispiele.push_back("Waffenmodell fehlt: " + w); }
                continue;
            }
            bhed::GlmModel mdl;
            std::string err;
            (bhed::readGlm(lies(it->second), mdl, &err) ? wGeladen : wFehlt) += 1;
        }
        zaehler["Griffe geladen"] = geladen;
        zaehler["Griffe nicht ausgepackt/lesbar"] = fehlt;
        zaehler["Klingen am eigenen *bladeN"] = mitTag;
        zaehler["Klingen ueber *flash (tag_hack)"] = mitHack;
        zaehler["Griffe ohne *bladeN und *flash"] = ohneBolzen;
        zaehler["Stab: zweite Klinge gegenlaeufig"] = stabUmgedreht;
        zaehler["Stab: zweite Klinge NICHT gegenlaeufig"] = stabFalsch;
        zaehler["Waffenmodelle geladen"] = wGeladen;
        zaehler["Waffenmodelle fehlen"] = wFehlt;
    }
    std::printf("%d Skripte gelesen\n", skripte);
    for (const auto& [k, n] : zaehler) {
        std::printf("  %6d  %s\n", n, k.c_str());
    }
    for (const std::string& b : beispiele) {
        std::printf("    z.B. %s\n", b.c_str());
    }
    return 0;
}
}  // namespace

int main(int argc, char** argv) {
    proben();
    int r = 0;
    if (argc >= 4) {
        r = durchsicht(argv[1], argv[2], argv[3]);
    }
    std::printf("\n%s (%d Fehlschlaege)\n",
                fails != 0 ? "FEHLGESCHLAGEN" : "alle Waffenproben bestanden", fails);
    return (fails != 0 || r != 0) ? 1 : 0;
}
