// script.h - Baummodell fuer .icarus-Skripte
//
// Der Baum haelt AUCH Leerzeilen und //-Kommentare als Knoten fest.
// Grund: ein Editor darf die Datei des Nutzers beim Oeffnen-und-Speichern
// nicht umformatieren. BehavEd macht das ebenso - anders waere ein
// bytegleicher Rundlauf ueber die 1510 Raven-Skripte nicht moeglich.
#ifndef BHED_SCRIPT_H
#define BHED_SCRIPT_H

#include <string>
#include <vector>
#include <cstddef>
#include <cstdint>

namespace bhed {

// Ein Argument innerhalb der Klammern eines Befehls.
struct Arg {
    enum class Kind : std::uint8_t {
        String,   // "text"          - in Anfuehrungszeichen
        Ident,    // FLUSH           - blank, aus einer %i-Typmenge
        Number,   // 1000.000 / -1
        Vector,   // < 0.000 0.000 0.000 >
        Expr,     // $get( FLOAT, "x" )$
    };
    Kind kind = Kind::String;
    std::string text;      // ohne Anfuehrungszeichen / ohne $ / ohne < >
    std::string typeset;   // aus /*@SET_TYPES*/, leer wenn keine Annotation
    bool locked = false;   // /*!*/ - Feld aus einer Makroausklappung, gesperrt
};

// Eine Kennung, die einen Knoten ueberdauert - ueber Zuege, Einfuegen,
// Loeschen und Rueckgaengig hinweg.
//
// Warum es sie gibt
// -----------------
// Der Aufklapp-Zustand der Baumansicht hing frueher an WEGEN. Ein Weg ist
// aber keine Eigenschaft des Knotens, sondern seiner Stelle - und die
// aendert sich bei jeder Strukturaenderung. Fuenf Runden lang wurde das
// einzeln nachgefuehrt, und elf Stellen taten es trotzdem nicht.
//
// Vergeben wird sie NICHT hier, sondern von `Document::vergibKennungen()`
// in einem Durchlauf. So muss keine der fuenfzehn Stellen, an denen ein
// Node entsteht, etwas davon wissen. 0 heisst "noch keine".
//
// Sie wird NICHT in die Datei geschrieben - der Rundlauf ueber die 1510
// Raven-Skripte muss bytegleich bleiben.
using Kennung = std::uint64_t;

struct Node {
    enum class Kind : std::uint8_t {
        Command,      // befehl ( ... );  oder  befehl ( ... ) { ... }
        Blank,        // Leerzeile
        LineComment,  // //...
        Macro,        // //$"walkOnly"@5 - ausgeklapptes Makro, count Zeilen
    };
    Kind kind = Kind::Command;
    std::string name;            // Befehlsname
    std::vector<Arg> args;
    bool hasBlock = false;       // { } folgt
    int count = 0;               // bei Macro: Anzahl der erzeugten Befehle
    std::vector<Node> children;
    std::string raw;             // Rohtext bei LineComment
    // Bleibt beim Kopieren erhalten - genau das traegt den Zustand ueber
    // Zuege und Schnappschuesse. Doppelte werden beim Vergeben aufgeloest.
    Kennung kennung = 0;
};

// Ein Knoten wird ueber seinen Weg von der Wurzel angesprochen: je Ebene der
// Index innerhalb der Geschwister. Steht hier und nicht in edit.h, damit auch
// die Baumansicht ihn benutzen kann, ohne die Bearbeitung einzubinden.
using Path = std::vector<std::size_t>;

struct Script {
    std::string header;          // uebliche erste Zeile
    std::vector<Node> nodes;
};

struct Diag {
    int line = 0;
    std::string message;
    // Fuer die Oberflaeche: ein Code (etwa "C004") und sein Argument, damit
    // sie die Meldung in der eingestellten Sprache zeigen kann - wie die
    // Pruefcodes V001... Leer: nur `message` gilt.
    std::string code;
    std::string arg;
    // Welcher Knoten (beim Uebersetzen). Leer, wenn unbekannt.
    Path path;
};

// Liest den Text eines .icarus-Skripts. Gibt false zurueck, wenn ein
// harter Strukturfehler auftrat; erkannte Auffaelligkeiten stehen in diag.
[[nodiscard]] bool readScript(const std::string& text, Script& out, std::vector<Diag>& diag);

// Fuer den Knopf "Export" des Originals.
//
// Belegt durch ein Bildschirmfoto: BehavEd schreibt eine Textdatei und
// oeffnet sie im Standardeditor. Der Inhalt ist echter .icarus-Text mit
// einer Kopfzeile davor:
//
//     ( Original filename: "" )
//
//     //Generated by BehavEd
//
//     rem ( "comment" );
//     move ( < 0 0 0 >, < 0 0 0 >, 1000 );
//
// Die Zahlen stehen dabei in der %g-Form, wenn der gleichnamige Schalter
// gesetzt ist - "1000" statt "1000.000". Die Zeichenketten behalten ihre
// Anfuehrungszeichen, anders als in der Baumansicht.
[[nodiscard]] std::string writeExport(const Script& s, const std::string& originalName,
                                      bool gFloats);

// Schreibt das Skript in Ravens Formatierung zurueck (CRLF, Tabulatoren).
[[nodiscard]] std::string writeScript(const Script& s);

// Einzelne Knoten ab der angegebenen Einruecktiefe schreiben. Wird fuer den
// REM-Knopf gebraucht, der einen Teilbaum in Kommentarzeilen verwandelt.
[[nodiscard]] std::string writeNodes(const std::vector<Node>& ns, int depth);

// Ist `raw` eine von BehavEd auskommentierte Zeile ("<Tabs>//(BHVDREM)  ...")?
// Dann steht in `inhalt` der Text dahinter, ohne Leerraum am Rand.
[[nodiscard]] bool remInhalt(const std::string& raw, std::string* inhalt);

} // namespace bhed
#endif
