// script.cpp - .icarus lesen und schreiben
//
// Die Formatierung ist an 1510 Raven-Skripten gemessen, nicht geraten:
//   Kopfzeile   "//Generated by BehavEd"          1510/1510
//   Zeilenende  CRLF, Einrueckung nur Tabulator   1510/1510
//   Klammern    "befehl ( a, b );"                30158/30158
//   Kommazahl   drei Nachkommastellen             15286 Belege
//   Vektor      "< 0.000 0.000 0.000 >"           3100 Belege
//   Annotation  "/*@TYP*/ Wert", ein Leerzeichen  ausnahmslos

#include "bhed/script.h"

#include <cstddef>
#include <cctype>
#include <cstdio>
#include <cstring>
#include <charconv>
#include <string>

namespace bhed {
namespace {

bool isSpace(char c) { return c == ' ' || c == '\t' || c == '\r'; }

std::string trim(const std::string& s) {
    std::size_t a = 0;
    std::size_t b = s.size();
    while (a < b && isSpace(s[a])) { ++a;
}
    while (b > a && isSpace(s[b - 1])) { --b;
}
    return s.substr(a, b - a);
}

// Argumentliste an Kommas der obersten Ebene zerlegen. Innerhalb von
// "..." , $...$ und < ... > wird nicht getrennt - $get( FLOAT, "x" )$
// enthaelt selbst ein Komma.
std::vector<std::string> splitArgs(const std::string& s) {
    std::vector<std::string> out;
    std::string cur;
    bool inStr = false;
    bool inExpr = false;
    bool inVec = false;
    int paren = 0;
    for (std::size_t k = 0; k < s.size(); ++k) {
        const char c = s[k];
        if (inStr) {
            cur += c;
            // Ein '"' schliesst den Text nur, wenn danach (bis auf
            // Leerzeichen) ein Komma oder das Ende kommt. Das Format kennt
            // kein Maskieren; ein Text wie  sag "hallo, du"  wurde sonst am
            // Komma in seiner Mitte zerlegt (Code-Pruefung 03.10.).
            if (c == '"') {
                const std::size_t naechstes = s.find_first_not_of(" \t", k + 1);
                if (naechstes == std::string::npos || s[naechstes] == ',') { inStr = false; }
            }
            continue;
        }
        if (inExpr) {
            cur += c;
            if (c == '$') { inExpr = false;
}
            continue;
        }
        if (c == '"') { inStr = true; cur += c; continue; }
        if (c == '$') { inExpr = true; cur += c; continue; }
        if (c == '<') { inVec = true; cur += c; continue; }
        if (c == '>') { inVec = false; cur += c; continue; }
        if (!inVec && c == '(') { ++paren; cur += c; continue; }
        if (!inVec && c == ')') { --paren; cur += c; continue; }
        if (c == ',' && !inVec && paren == 0) {
            out.push_back(trim(cur));
            cur.clear();
            continue;
        }
        cur += c;
    }
    std::string last = trim(cur);
    if (!last.empty() || !out.empty()) { out.push_back(last);
}
    return out;
}

Arg parseArg(const std::string& in) {
    Arg a;
    std::string s = in;
    // /*!*/ markiert ein Feld aus einer Makroausklappung: gesperrt.
    // Entspricht dem %r-Vorsatz in den Makrorumpfen der .bhc.
    if (s.starts_with("/*!*/")) {
        a.locked = true;
        s = trim(s.substr(5));
    }
    // fuehrende Typannotation abziehen
    if (s.starts_with("/*@")) {
        std::size_t e = s.find("*/");
        if (e != std::string::npos) {
            a.typeset = s.substr(3, e - 3);
            s = trim(s.substr(e + 2));
        }
    }
    if (s.size() >= 2 && s.front() == '"' && s.back() == '"') {
        a.kind = Arg::Kind::String;
        a.text = s.substr(1, s.size() - 2);
    } else if (s.size() >= 2 && s.front() == '$' && s.back() == '$') {
        a.kind = Arg::Kind::Expr;
        a.text = s.substr(1, s.size() - 2);
    } else if (s.size() >= 2 && s.front() == '<' && s.back() == '>') {
        a.kind = Arg::Kind::Vector;
        a.text = trim(s.substr(1, s.size() - 2));
    } else if (!s.empty() && ((std::isdigit(static_cast<unsigned char>(s[0])) != 0) ||
                              s[0] == '-' || s[0] == '+' || s[0] == '.')) {
        a.kind = Arg::Kind::Number;
        a.text = s;
    } else {
        a.kind = Arg::Kind::Ident;
        a.text = s;
    }
    return a;
}

// Wo beginnt ein "//"-Kommentar HINTER Code? Nicht in "..." oder $...$.
// npos, wenn keiner da ist.
std::size_t kommentarAnfang(const std::string& s) {
    bool inStr = false;
    bool inExpr = false;
    for (std::size_t k = 0; k + 1 < s.size(); ++k) {
        const char c = s[k];
        if (c == '"' && !inExpr) { inStr = !inStr; continue; }
        if (c == '$' && !inStr) { inExpr = !inExpr; continue; }
        if (!inStr && !inExpr && c == '/' && s[k + 1] == '/') { return k; }
    }
    return std::string::npos;
}

// Eine Zeile in Code und Kommentar dahinter zerlegen (beides getrimmt).
struct Zeile {
    std::string code;
    std::string kommentar;   // mit "//", leer wenn keiner
    std::string einzug;      // fuehrende Leerzeichen/Tabs der Zeile
};

Zeile zerlege(const std::string& raw) {
    Zeile z;
    const std::size_t erst = raw.find_first_not_of(" \t");
    z.einzug = raw.substr(0, erst == std::string::npos ? raw.size() : erst);
    const std::string s = trim(raw);
    const std::size_t k = s.starts_with("//") ? std::string::npos : kommentarAnfang(s);
    if (k == std::string::npos) {
        z.code = s;
    } else {
        z.code = trim(s.substr(0, k));
        z.kommentar = s.substr(k);
    }
    return z;
}

struct Reader {
    std::vector<std::string> lines;
    std::size_t pos = 0;
    std::vector<Diag>* diag = nullptr;

    void note(const std::string& m) {
        if (diag != nullptr) { diag->push_back({static_cast<int>(pos) + 1, m});
}
    }

    // Ein Kommentar, der hinter Code stand, als eigene Zeile danach.
    static void kommentarDanach(std::vector<Node>& out, const Zeile& z) {
        if (z.kommentar.empty()) { return; }
        Node n;
        n.kind = Node::Kind::LineComment;
        n.raw = z.einzug + z.kommentar;
        out.push_back(std::move(n));
    }

    // Eine Zeile, die sich nicht lesen laesst, WORTGETREU behalten (als
    // Kommentarknoten, der Schreiber gibt `raw` unveraendert aus). Bisher
    // fiel sie still weg und war nach dem naechsten Speichern verloren
    // (Code-Pruefung 03.10.).
    static void wortgetreu(std::vector<Node>& out, const std::string& raw) {
        Node n;
        n.kind = Node::Kind::LineComment;
        n.raw = raw;
        out.push_back(std::move(n));
    }

    // Liest Knoten bis zum passenden '}' (oder Dateiende bei depth==0).
    //
    // Kommentare HINTER Code (`wait ( 1000 ); // Tuer`, `} // ende`) werden
    // abgetrennt und als eigene Kommentarzeile dahinter behalten. Vorher
    // ging der Kommentar verloren, und `} // ende` schloss den Block nicht -
    // der Rest der Datei rutschte hinein.
    bool readNodes(std::vector<Node>& out, int depth) {
        while (pos < lines.size()) {
            const std::string raw = lines[pos];
            const Zeile z = zerlege(raw);
            const std::string& s = z.code;
            if (s == "}") {
                if (depth == 0) {
                    note("unerwartete schliessende Klammer");
                    ++pos;
                    wortgetreu(out, raw);
                    continue;
                }
                return true;                       // Aufrufer verbraucht die Zeile
            }
            ++pos;
            if (s.empty()) { { Node b; b.kind = Node::Kind::Blank; out.push_back(std::move(b)); } continue; }
            // Makromarker:  //$"walkOnly"@5
            // Die erzeugten Befehle bleiben Geschwister - die Datei ist flach.
            // Das Zusammenfalten im Baum ist Sache der Anzeige, nicht des
            // Formats; so bleibt der Rundlauf trivial bytegleich.
            if (s.starts_with("//$\"")) {
                std::size_t q = s.find('"', 4);
                std::size_t at = q == std::string::npos ? std::string::npos : s.find('@', q);
                if (q != std::string::npos && at != std::string::npos) {
                    Node m;
                    m.kind = Node::Kind::Macro;
                    m.name = s.substr(4, q - 4);
                    int cnt = 0;
                    std::from_chars(s.data() + at + 1, s.data() + s.size(), cnt);
                    m.count = cnt;
                    m.raw = raw;
                    out.push_back(std::move(m));
                    continue;
                }
            }
            if (s.starts_with("//")) {
                // Wortgetreu behalten, samt Einrueckung: BehavEds
                // "//(BHVDREM)"-Auskommentierung ruecken tiefer ein als der
                // Block, in dem sie steht.
                Node n; n.kind = Node::Kind::LineComment; n.raw = raw;
                out.push_back(std::move(n));
                continue;
            }
            std::size_t op = s.find('(');
            if (op == std::string::npos) { note("Zeile ohne Klammer: " + s); wortgetreu(out, raw); continue; }
            std::size_t cl = s.rfind(')');
            if (cl == std::string::npos || cl < op) {
                note("Klammer nicht geschlossen: " + s);
                wortgetreu(out, raw);
                continue;
            }

            Node n;
            n.kind = Node::Kind::Command;
            n.name = trim(s.substr(0, op));
            for (const std::string& a : splitArgs(s.substr(op + 1, cl - op - 1))) {
                if (!a.empty()) { n.args.push_back(parseArg(a));
}
}

            const std::string after = trim(s.substr(cl + 1));
            if (after == ";") {
                out.push_back(std::move(n));
                kommentarDanach(out, z);
                continue;
            }
            // Blockbefehl: '{' steht in der naechsten Zeile (Raven-Stil)
            // oder direkt dahinter.
            if (after == "{" || after.empty()) {
                Zeile auf;   // die Zeile mit '{', falls sie eine eigene ist
                if (after.empty()) {
                    while (pos < lines.size() && trim(lines[pos]).empty()) { ++pos;
}
                    if (pos < lines.size()) { auf = zerlege(lines[pos]); }
                    if (pos >= lines.size() || auf.code != "{") {
                        note("Blockbefehl ohne '{': " + n.name);
                        out.push_back(std::move(n));
                        kommentarDanach(out, z);
                        continue;
                    }
                    ++pos;
                }
                n.hasBlock = true;
                if (!readNodes(n.children, depth + 1)) {
                    note("Block nicht geschlossen: " + n.name);
                    out.push_back(std::move(n));
                    kommentarDanach(out, z);
                    return false;
                }
                const Zeile zu = zerlege(lines[pos]);
                ++pos;                              // '}' verbrauchen
                out.push_back(std::move(n));
                kommentarDanach(out, z);
                kommentarDanach(out, auf);
                kommentarDanach(out, zu);
                continue;
            }
            note("unbekannter Zeilenrest '" + after + "' bei " + n.name);
            out.push_back(std::move(n));
            kommentarDanach(out, z);
        }
        return depth == 0;
    }
};

std::string fmtNumber(const std::string& t) {
    // Zahlen unveraendert uebernehmen. BehavEd schreibt %.3f, aber es gibt
    // handbearbeitete Dateien mit sechs Stellen - die wollen wir nicht
    // stillschweigend aendern.
    return t;
}

// Nachkommastellen kuerzen: 1000.000 -> 1000, 0.500 -> 0.5
std::string trimZeros(const std::string& t) {
    if (t.find('.') == std::string::npos) {
        return t;
    }
    std::size_t e = t.size();
    while (e > 0 && t[e - 1] == '0') { --e; }
    if (e > 0 && t[e - 1] == '.') { --e; }
    return e == 0 ? "0" : t.substr(0, e);
}

std::string shortenAll(const std::string& text) {
    std::string out;
    std::size_t i = 0;
    while (i < text.size()) {
        const std::size_t sp = text.find(' ', i);
        const std::size_t end = (sp == std::string::npos) ? text.size() : sp;
        if (!out.empty()) { out += ' '; }
        out += trimZeros(text.substr(i, end - i));
        i = (sp == std::string::npos) ? text.size() : sp + 1;
    }
    return out;
}

void writeArg(std::string& o, const Arg& a, bool gFloats) {
    if (a.locked) { o += "/*!*/ ";
}
    if (!a.typeset.empty()) { o += "/*@"; o += a.typeset; o += "*/ "; }
    switch (a.kind) {
        case Arg::Kind::String: o += '"'; o += a.text; o += '"'; break;
        case Arg::Kind::Expr:   o += '$'; o += a.text; o += '$'; break;
        case Arg::Kind::Vector:
            o += "< ";
            o += gFloats ? shortenAll(a.text) : a.text;
            o += " >";
            break;
        case Arg::Kind::Number:
            o += gFloats ? trimZeros(a.text) : fmtNumber(a.text);
            break;
        case Arg::Kind::Ident:  o += a.text; break;
    }
}

void writeNodesInto(std::string& o, const std::vector<Node>& ns, int depth,
                    bool gFloats) {
    const std::string ind(static_cast<std::size_t>(depth), '\t');
    for (const Node& n : ns) {
        if (n.kind == Node::Kind::Blank) { o += "\r\n"; continue; }
        if (n.kind == Node::Kind::LineComment) {
            o += n.raw; o += "\r\n"; continue;
        }
        if (n.kind == Node::Kind::Macro) {
            // Die Zahl hinter '@' ist die AKTUELLE Zeilenzahl, nicht die beim
            // Einlesen: wer einen Befehl aus dem Makro loescht, sonst steht
            // weiter @3 in der Datei, und beim naechsten Laden schluckt das
            // Makro den Befehl dahinter. Der Rest der Zeile bleibt wortgetreu.
            const std::size_t at = n.raw.rfind('@');
            if (at == std::string::npos) {
                o += n.raw;
            } else {
                std::size_t ende = at + 1;
                while (ende < n.raw.size() && n.raw[ende] >= '0' && n.raw[ende] <= '9') { ++ende; }
                o.append(n.raw, 0, at + 1);
                o += std::to_string(n.count);
                o.append(n.raw, ende, std::string::npos);
            }
            o += "\r\n"; continue;
        }
        o += ind;
        o += n.name;
        o += " ( ";
        for (std::size_t i = 0; i < n.args.size(); ++i) {
            if (i != 0U) { o += ", ";
}
            writeArg(o, n.args[i], gFloats);
        }
        o += " )";
        if (!n.hasBlock) { o += ";\r\n"; continue; }
        o += "\r\n";
        o += ind; o += "{\r\n";
        writeNodesInto(o, n.children, depth + 1, gFloats);
        o += ind; o += "}\r\n";
    }
}

} // namespace

bool readScript(const std::string& text, Script& out, std::vector<Diag>& diag) {
    Reader r;
    r.diag = &diag;
    std::string cur;
    // UTF-8-BOM (Notepad speichert so): sonst hiesse der erste Befehl
    // "<BOM>wait" und waere unbekannt. Die Marke gehoert nicht zum Skript.
    const std::size_t start = text.starts_with("\xEF\xBB\xBF") ? 3 : 0;
    for (std::size_t k = start; k < text.size(); ++k) {
        const char c = text[k];
        if (c == '\n') { r.lines.push_back(cur); cur.clear(); }
        else if (c != '\r') { cur += c;
}
    }
    if (!cur.empty()) { r.lines.push_back(cur);
}
    if (!r.lines.empty() && trim(r.lines[0]).starts_with("//Generated by")) {
        out.header = trim(r.lines[0]);
        r.pos = 1;
    }
    out.nodes.clear();
    return r.readNodes(out.nodes, 0);
}

bool remInhalt(const std::string& raw, std::string* inhalt) {
    std::size_t t = 0;
    while (t < raw.size() && (raw[t] == '\t' || raw[t] == ' ')) {
        ++t;
    }
    if (raw.compare(t, 11, "//(BHVDREM)") != 0) {
        return false;
    }
    std::size_t a = t + 11;
    std::size_t e = raw.size();
    while (a < e && (raw[a] == ' ' || raw[a] == '\t')) { ++a; }
    while (e > a && (raw[e - 1] == ' ' || raw[e - 1] == '\t' || raw[e - 1] == '\r')) { --e; }
    if (inhalt != nullptr) {
        *inhalt = raw.substr(a, e - a);
    }
    return true;
}

std::string writeNodes(const std::vector<Node>& ns, int depth) {
    std::string o;
    writeNodesInto(o, ns, depth, false);
    return o;
}

std::string writeScript(const Script& s) {
    std::string o;
    o += s.header.empty() ? "//Generated by BehavEd" : s.header;
    o += "\r\n";
    writeNodesInto(o, s.nodes, 0, false);
    return o;
}

std::string writeExport(const Script& s, const std::string& originalName,
                        bool gFloats) {
    // Aufbau aus dem Bildschirmfoto des Originals: Kopfzeile mit dem
    // urspruenglichen Dateinamen, Leerzeile, die uebliche //Generated-Zeile,
    // Leerzeile, dann der Text.
    std::string o = "( Original filename: \"" + originalName + "\" )\r\n\r\n";
    o += s.header.empty() ? "//Generated by BehavEd" : s.header;
    o += "\r\n\r\n";
    writeNodesInto(o, s.nodes, 0, gFloats);
    return o;
}

} // namespace bhed
