// script.cpp - .icarus lesen und schreiben
//
// Die Formatierung ist an 1510 Raven-Skripten gemessen, nicht geraten:
//   Kopfzeile   "//Generated by BehavEd"          1510/1510
//   Zeilenende  CRLF, Einrueckung nur Tabulator   1510/1510
//   Klammern    "befehl ( a, b );"                30158/30158
//   Kommazahl   drei Nachkommastellen             15286 Belege
//   Vektor      "< 0.000 0.000 0.000 >"           3100 Belege
//   Annotation  "/*@TYP*/ Wert", ein Leerzeichen  ausnahmslos

#include "bhed/script.h"

#include <cstddef>
#include <cctype>
#include <cstdio>
#include <cstring>
#include <charconv>

namespace bhed {
namespace {

bool isSpace(char c) { return c == ' ' || c == '\t' || c == '\r'; }

std::string trim(const std::string& s) {
    std::size_t a = 0;
    std::size_t b = s.size();
    while (a < b && isSpace(s[a])) { ++a;
}
    while (b > a && isSpace(s[b - 1])) { --b;
}
    return s.substr(a, b - a);
}

// Argumentliste an Kommas der obersten Ebene zerlegen. Innerhalb von
// "..." , $...$ und < ... > wird nicht getrennt - $get( FLOAT, "x" )$
// enthaelt selbst ein Komma.
std::vector<std::string> splitArgs(const std::string& s) {
    std::vector<std::string> out;
    std::string cur;
    bool inStr = false;
    bool inExpr = false;
    bool inVec = false;
    int paren = 0;
    for (char c : s) {
        if (inStr) {
            cur += c;
            if (c == '"') { inStr = false;
}
            continue;
        }
        if (inExpr) {
            cur += c;
            if (c == '$') { inExpr = false;
}
            continue;
        }
        if (c == '"') { inStr = true; cur += c; continue; }
        if (c == '$') { inExpr = true; cur += c; continue; }
        if (c == '<') { inVec = true; cur += c; continue; }
        if (c == '>') { inVec = false; cur += c; continue; }
        if (!inVec && c == '(') { ++paren; cur += c; continue; }
        if (!inVec && c == ')') { --paren; cur += c; continue; }
        if (c == ',' && !inVec && paren == 0) {
            out.push_back(trim(cur));
            cur.clear();
            continue;
        }
        cur += c;
    }
    std::string last = trim(cur);
    if (!last.empty() || !out.empty()) { out.push_back(last);
}
    return out;
}

Arg parseArg(const std::string& in) {
    Arg a;
    std::string s = in;
    // /*!*/ markiert ein Feld aus einer Makroausklappung: gesperrt.
    // Entspricht dem %r-Vorsatz in den Makrorumpfen der .bhc.
    if (s.starts_with("/*!*/")) {
        a.locked = true;
        s = trim(s.substr(5));
    }
    // fuehrende Typannotation abziehen
    if (s.starts_with("/*@")) {
        std::size_t e = s.find("*/");
        if (e != std::string::npos) {
            a.typeset = s.substr(3, e - 3);
            s = trim(s.substr(e + 2));
        }
    }
    if (s.size() >= 2 && s.front() == '"' && s.back() == '"') {
        a.kind = Arg::Kind::String;
        a.text = s.substr(1, s.size() - 2);
    } else if (s.size() >= 2 && s.front() == '$' && s.back() == '$') {
        a.kind = Arg::Kind::Expr;
        a.text = s.substr(1, s.size() - 2);
    } else if (s.size() >= 2 && s.front() == '<' && s.back() == '>') {
        a.kind = Arg::Kind::Vector;
        a.text = trim(s.substr(1, s.size() - 2));
    } else if (!s.empty() && ((std::isdigit(static_cast<unsigned char>(s[0])) != 0) ||
                              s[0] == '-' || s[0] == '+' || s[0] == '.')) {
        a.kind = Arg::Kind::Number;
        a.text = s;
    } else {
        a.kind = Arg::Kind::Ident;
        a.text = s;
    }
    return a;
}

struct Reader {
    std::vector<std::string> lines;
    std::size_t pos = 0;
    std::vector<Diag>* diag = nullptr;

    void note(const std::string& m) {
        if (diag != nullptr) { diag->push_back({static_cast<int>(pos) + 1, m});
}
    }

    // Liest Knoten bis zum passenden '}' (oder Dateiende bei depth==0).
    bool readNodes(std::vector<Node>& out, int depth) {
        while (pos < lines.size()) {
            const std::string raw = lines[pos];
            const std::string s = trim(raw);
            if (s == "}") {
                if (depth == 0) { note("unerwartete schliessende Klammer"); ++pos; continue; }
                return true;                       // Aufrufer verbraucht die Zeile
            }
            ++pos;
            if (s.empty()) { { Node b; b.kind = Node::Kind::Blank; out.push_back(std::move(b)); } continue; }
            // Makromarker:  //$"walkOnly"@5
            // Die erzeugten Befehle bleiben Geschwister - die Datei ist flach.
            // Das Zusammenfalten im Baum ist Sache der Anzeige, nicht des
            // Formats; so bleibt der Rundlauf trivial bytegleich.
            if (s.starts_with("//$\"")) {
                std::size_t q = s.find('"', 4);
                std::size_t at = q == std::string::npos ? std::string::npos : s.find('@', q);
                if (q != std::string::npos && at != std::string::npos) {
                    Node m;
                    m.kind = Node::Kind::Macro;
                    m.name = s.substr(4, q - 4);
                    int cnt = 0;
                    std::from_chars(s.data() + at + 1, s.data() + s.size(), cnt);
                    m.count = cnt;
                    m.raw = raw;
                    out.push_back(std::move(m));
                    continue;
                }
            }
            if (s.starts_with("//")) {
                // Wortgetreu behalten, samt Einrueckung: BehavEds
                // "//(BHVDREM)"-Auskommentierung ruecken tiefer ein als der
                // Block, in dem sie steht.
                Node n; n.kind = Node::Kind::LineComment; n.raw = raw;
                out.push_back(std::move(n));
                continue;
            }
            std::size_t op = s.find('(');
            if (op == std::string::npos) { note("Zeile ohne Klammer: " + s); continue; }
            std::size_t cl = s.rfind(')');
            if (cl == std::string::npos || cl < op) { note("Klammer nicht geschlossen: " + s); continue; }

            Node n;
            n.kind = Node::Kind::Command;
            n.name = trim(s.substr(0, op));
            for (const std::string& a : splitArgs(s.substr(op + 1, cl - op - 1))) {
                if (!a.empty()) { n.args.push_back(parseArg(a));
}
}

            const std::string after = trim(s.substr(cl + 1));
            if (after == ";") {
                out.push_back(std::move(n));
                continue;
            }
            // Blockbefehl: '{' steht in der naechsten Zeile (Raven-Stil)
            // oder direkt dahinter.
            if (after == "{" || after.empty()) {
                if (after.empty()) {
                    while (pos < lines.size() && trim(lines[pos]).empty()) { ++pos;
}
                    if (pos >= lines.size() || trim(lines[pos]) != "{") {
                        note("Blockbefehl ohne '{': " + n.name);
                        out.push_back(std::move(n));
                        continue;
                    }
                    ++pos;
                }
                n.hasBlock = true;
                if (!readNodes(n.children, depth + 1)) {
                    note("Block nicht geschlossen: " + n.name);
                    out.push_back(std::move(n));
                    return false;
                }
                ++pos;                              // '}' verbrauchen
                out.push_back(std::move(n));
                continue;
            }
            note("unbekannter Zeilenrest '" + after + "' bei " + n.name);
            out.push_back(std::move(n));
        }
        return depth == 0;
    }
};

std::string fmtNumber(const std::string& t) {
    // Zahlen unveraendert uebernehmen. BehavEd schreibt %.3f, aber es gibt
    // handbearbeitete Dateien mit sechs Stellen - die wollen wir nicht
    // stillschweigend aendern.
    return t;
}

// Nachkommastellen kuerzen: 1000.000 -> 1000, 0.500 -> 0.5
std::string trimZeros(const std::string& t) {
    if (t.find('.') == std::string::npos) {
        return t;
    }
    std::size_t e = t.size();
    while (e > 0 && t[e - 1] == '0') { --e; }
    if (e > 0 && t[e - 1] == '.') { --e; }
    return e == 0 ? "0" : t.substr(0, e);
}

std::string shortenAll(const std::string& text) {
    std::string out;
    std::size_t i = 0;
    while (i < text.size()) {
        const std::size_t sp = text.find(' ', i);
        const std::size_t end = (sp == std::string::npos) ? text.size() : sp;
        if (!out.empty()) { out += ' '; }
        out += trimZeros(text.substr(i, end - i));
        i = (sp == std::string::npos) ? text.size() : sp + 1;
    }
    return out;
}

void writeArg(std::string& o, const Arg& a, bool gFloats) {
    if (a.locked) { o += "/*!*/ ";
}
    if (!a.typeset.empty()) { o += "/*@"; o += a.typeset; o += "*/ "; }
    switch (a.kind) {
        case Arg::Kind::String: o += '"'; o += a.text; o += '"'; break;
        case Arg::Kind::Expr:   o += '$'; o += a.text; o += '$'; break;
        case Arg::Kind::Vector:
            o += "< ";
            o += gFloats ? shortenAll(a.text) : a.text;
            o += " >";
            break;
        case Arg::Kind::Number:
            o += gFloats ? trimZeros(a.text) : fmtNumber(a.text);
            break;
        case Arg::Kind::Ident:  o += a.text; break;
    }
}

void writeNodesInto(std::string& o, const std::vector<Node>& ns, int depth,
                    bool gFloats) {
    const std::string ind(static_cast<std::size_t>(depth), '\t');
    for (const Node& n : ns) {
        if (n.kind == Node::Kind::Blank) { o += "\r\n"; continue; }
        if (n.kind == Node::Kind::LineComment || n.kind == Node::Kind::Macro) {
            o += n.raw; o += "\r\n"; continue;
        }
        o += ind;
        o += n.name;
        o += " ( ";
        for (std::size_t i = 0; i < n.args.size(); ++i) {
            if (i != 0U) { o += ", ";
}
            writeArg(o, n.args[i], gFloats);
        }
        o += " )";
        if (!n.hasBlock) { o += ";\r\n"; continue; }
        o += "\r\n";
        o += ind; o += "{\r\n";
        writeNodesInto(o, n.children, depth + 1, gFloats);
        o += ind; o += "}\r\n";
    }
}

} // namespace

bool readScript(const std::string& text, Script& out, std::vector<Diag>& diag) {
    Reader r;
    r.diag = &diag;
    std::string cur;
    for (char c : text) {
        if (c == '\n') { r.lines.push_back(cur); cur.clear(); }
        else if (c != '\r') { cur += c;
}
    }
    if (!cur.empty()) { r.lines.push_back(cur);
}
    if (!r.lines.empty() && trim(r.lines[0]).starts_with("//Generated by")) {
        out.header = trim(r.lines[0]);
        r.pos = 1;
    }
    out.nodes.clear();
    return r.readNodes(out.nodes, 0);
}

bool remInhalt(const std::string& raw, std::string* inhalt) {
    std::size_t t = 0;
    while (t < raw.size() && (raw[t] == '\t' || raw[t] == ' ')) {
        ++t;
    }
    if (raw.compare(t, 11, "//(BHVDREM)") != 0) {
        return false;
    }
    std::size_t a = t + 11;
    std::size_t e = raw.size();
    while (a < e && (raw[a] == ' ' || raw[a] == '\t')) { ++a; }
    while (e > a && (raw[e - 1] == ' ' || raw[e - 1] == '\t' || raw[e - 1] == '\r')) { --e; }
    if (inhalt != nullptr) {
        *inhalt = raw.substr(a, e - a);
    }
    return true;
}

std::string writeNodes(const std::vector<Node>& ns, int depth) {
    std::string o;
    writeNodesInto(o, ns, depth, false);
    return o;
}

std::string writeScript(const Script& s) {
    std::string o;
    o += s.header.empty() ? "//Generated by BehavEd" : s.header;
    o += "\r\n";
    writeNodesInto(o, s.nodes, 0, false);
    return o;
}

std::string writeExport(const Script& s, const std::string& originalName,
                        bool gFloats) {
    // Aufbau aus dem Bildschirmfoto des Originals: Kopfzeile mit dem
    // urspruenglichen Dateinamen, Leerzeile, die uebliche //Generated-Zeile,
    // Leerzeile, dann der Text.
    std::string o = "( Original filename: \"" + originalName + "\" )\r\n\r\n";
    o += s.header.empty() ? "//Generated by BehavEd" : s.header;
    o += "\r\n\r\n";
    writeNodesInto(o, s.nodes, 0, gFloats);
    return o;
}

} // namespace bhed
